common/translations/markup.js
spec/translations/markup.spec.js

Notably, LID "VIEWWALLET_Subtitle" was causing an issue here, since it
had more than one link. React was complaining about it but now it's all
good.

linkify in markup.js now adds keys to multiple links.

---

webpack_config/webpack.prod.js

Noticed that we were using `exec` to run unix-style commands for clearing up old builds.
This'll use FS so it'll work on everyone's machine :)

Use `fs` library so even Windows users can run build.

---

common/components/BalanceSidebar/TokenRow.jsx
common/components/Footer/index.jsx
common/components/Header/index.jsx
package.json
webpack_config/config.js
webpack_config/webpack.base.js
webpack_config/webpack.dev.js

Implemented `image-webpack-loader` on top of `file-loader` to handle image resources linked to in CSS and JSX. Addresses #43. These compression settings were just some suggested ones I found, but are easily tweaked. This also removes inlining, which may not have been desired.

Bundle and compress images with Webpack

---

.prettierrc
package.json

- Adjust 'lint-staged' to pass single-quote via CLI
- remove unneeded .prettierrc (no longer needed)

Make Husky use single quotes.

---

.eslintrc.json
.prettierrc
common/actions/generateWallet.js
common/actions/wallet.js
common/components/BalanceSidebar/AddCustomTokenForm.jsx
common/components/BalanceSidebar/TokenBalances.jsx
common/components/BalanceSidebar/TokenRow.jsx
common/components/PaperWallet/index.jsx
common/components/PrintableWallet/index.jsx
common/components/WalletDecrypt/PrivateKey.jsx
common/components/index.js
common/components/ui/Identicon.jsx
common/components/ui/QRCode.jsx
common/components/ui/index.js
common/containers/Tabs/GenerateWallet/components/EnterPassword.jsx
common/containers/Tabs/GenerateWallet/components/PaperWallet.jsx
common/containers/Tabs/GenerateWallet/components/SaveWallet.jsx
common/containers/Tabs/GenerateWallet/index.js
common/libs/keystore.js
common/libs/nodes/base.js
common/libs/nodes/rpc.js
common/libs/wallet/privkey.js
common/reducers/generateWallet.js
common/sagas/bity.js
common/sagas/wallet.js
common/utils/printElement.js
package.json

Addresses the following from #38:
* Generic print function for any react element
* Use ReactDOMServer renderToString instead of an element ref for printing
* Handle prop changes to regenerate QR codes for address / pkey in PrintableWallet component
* Reworded some comments for clarity
It does not address:
* Inline styles. I know this was contentious (And even I'm not thrilled with it) but reworking that to work with a proper stylesheet will take a long time of figuring out dev-specific issues for an isolated component that's finished.
* QR Code generic component. See https://github.com/MyEtherWallet/MyEtherWallet/pull/38#discussion_r127597274 for reasoning. There's also a lot to consider here that's print specific, such as needing to wait for it to be generated before allowing the print …

Wallet pr fixes

---

common/containers/Tabs/GenerateWallet/index.js

Update GenerateWallet `hasDownloadedWalletFile` prop type from invalid `boolean` type to valid `bool` type.

Bugfix: Invalid proptype in GenerateWallet

---

common/actions/config.js
common/components/Header/components/GasPriceDropdown.jsx
common/components/Header/components/GasPriceDropdown.scss
common/components/Header/components/gasPriceDropdown.jsx
common/components/Header/index.jsx
common/config/data.js
common/containers/App/index.jsx
common/reducers/config.js

Implements the gas price slider in the header. I'm very new to React, Redux, and Flow, so please point out anything silly I might have done :smile:

Gas price dropdown

---

package-lock.json

Looks like this dependency didn't make it into package lock from the previous PR. My bad.

Added missing qr code dependency to package lock

---

common/libs/signing.js
common/libs/validators.js
common/libs/wallet/base.js
common/libs/wallet/privkey.js
package.json

Inspired by the discussion from issue #103 a few days ago:
* Implements promise-based methods on the `BaseWallet` & `PrivKeyWallet` classes
* Creates new `signing.js` file that handles private key TX & message signing
* Adds raw TX validation to `validators.js`
* Implements `signRawTransaction` and `signMessage` methods on `PrivKeyWallet` class
* Adds dependency to `ethereumjs-tx` in `package.json` (used in v3)
Transaction signing was modeled from v3 file [uiFuncs.js](https://github.com/kvhnuke/etherwallet/blob/3ab97999a157b1e0410de49b40080bcd35a1f5b3/app/scripts/uiFuncs.js) (~line 96).
Message signing was modeled from v3 file [signMsgCtrl.js](https://github.com/kvhnuke/etherwallet/blob/75157b1279f31d13ab975af97eefbed098265990/app/scripts/controllers/signMsgCtrl.js) (~line 22).
It does …

Add Promises & Signing to Wallet Classes 

---

common/components/BalanceSidebar/BalanceSidebar.jsx
common/components/PaperWallet/index.jsx
common/containers/Tabs/GenerateWallet/components/DownloadWallet.jsx
common/libs/wallet/base.js
common/libs/wallet/privkey.js
common/sagas/wallet.js

Addresses the flow type errors introduced by the previous wallet decrypt PR. Essentially moves component-based async calls to `componentDidMount` and sets `address` property in state. 
Stays clear of `SendTransaction/index.jsx` to avoid conflicts with @wbobeirne. 
As always, let me know if anything could be improved! :smile:

Fix flow errors

---

common/libs/keystore.js
common/libs/wallet/keystore.js

* Ports keystore decrypt function from v3
* Adds `KeystoreWallet` class
---
I've deviated slightly from the v3 keystore decrypt function. Here are some changes that I'd like to highlight for discussion:
* In v3, the keystore could be passed in as an object or a string. It can now only be a string.
* The v3 version accepted a boolean as a third argument that lowercased the keystore. This argument has been removed and the lowercasing now happens by default. 
I went this route because (1) stringified & lowercased keystores seem to be exclusively used in v3. I could not find instances where objects were passed in, nor where the third arg wasn't set to `true`. (2) Simple is often better, and this seems to be a good opportunity to standardize how we interact with keystore files.
[The function …

Add KeystoreWallet Class & Decrypt

---

common/components/Header/components/Navigation.jsx
common/components/Header/components/Navigation.scss
common/components/Header/components/NavigationLink.jsx
common/components/Header/components/NavigationLink.scss
common/components/Header/index.jsx
common/components/Header/index.scss
common/components/WalletDecrypt/index.jsx
common/config/data.js
package-lock.json
package.json

This addresses #132 and a few other things. The complete list is:
* Add an alpha warning banner
* Used warning color instead of danger to differentiate from v3 more
* Text and color configurable in `config/data.js`
* Set package.json semver to `4.0.0-alpha.1`
* Set the header version to `4.0.0`
* Disable links that haven't been implemented yet
* Considered "View Wallet Info" disabled because it's basically a stub (#92)
* Disable wallet options that haven't been implemented yet
This screenshot showcases all of the changes:

Visual Alpha Prep

---

common/components/ui/SimpleDropDown.jsx
common/components/ui/SimpleDropdown.jsx
common/components/ui/SimpleSelect.jsx
common/containers/Tabs/GenerateWallet/components/EnterPassword.jsx
common/containers/Tabs/SendTransaction/components/UnitDropdown.jsx
common/containers/Tabs/SendTransaction/index.jsx
common/containers/Tabs/Swap/components/CurrencySwap.jsx
common/sass/styles/overrides.scss
common/sass/styles/overrides/dropdowns.scss
common/sass/styles/overrides/input-groups.scss

As I was playing with the latest develop, I noticed we had encountered several regressions (listed here https://github.com/MyEtherWallet/MyEtherWallet/issues/169).
This PR fixes both of these regressions, while also simplifying the unit dropdown by making use of the `SimpleDropdown` component.
It also clears out a javascript warning in the console for using the `translate` prop incorrectly.

Fix Send Regressions

---

webpack_config/webpack.base.js
webpack_config/webpack.dev.js
webpack_config/webpack.prod.js

I was able to improve build speed by doing the following things:
* Removing eslint-loader. I think this should be a pre-commit hook to enforce (ala prettier) and should be handled by the user's IDE, rather than this slow-ish loader.
* Changing the development devtool. This was the biggest gain, and only results in some minor usability changes with sourcemaps.
| Config                                           | Avg build speed | Avg rebuild speed |
|--------------------------------------------------|-----------------|-------------------|
| Eslint Loader / source-map devtool (current)     | 33.81s          | 3.81s             |
| No Eslint / source-map devtool                   | 28.76s          | 3.51s             |
| No Eslint / cheap-module-eval-source-map devtool | 25.13s          | …

Improve Build Speed

---

common/reducers/wallet.js

Remove `isBroadcasting` from top-level wallet state. `isBroadcasting` is kept at the BroadcastTransactionStatus level, with a different state for each transaction.

Remove Un-needed isBroadcasting Wallet State

---

common/components/WalletDecrypt/Trezor.jsx
common/libs/decrypt.js
common/libs/transaction.js
common/libs/values.js
common/libs/wallet/deterministic.js
common/libs/wallet/privkey.js
common/libs/wallet/trezor.js

This fixes Trezor (And any deterministic wallet that extends that class) to use the index of the wallet as a part of the dpath. This was causing Trezor sends to fail.
In the process of debugging, I also trued up a few spots in the send process to better match v3. I'll drop notes linking to where they exist in v3.

Trezor DPath Fix

---

common/containers/Tabs/Swap/components/CurrencySwap.tsx
common/containers/Tabs/Swap/components/PaymentInfo.scss

Fixes https://github.com/MyEtherWallet/MyEtherWallet/issues/259
- center align payment address in payment info
- use updated DropDown component instead of SimpleSelect
(Dropdown) Before
" alt="screen shot 2017-10-03 at 8 02 33 pm" src="https://user-images.githubusercontent.com/7861465/31158333-dd9386d8-a875-11e7-8821-fd603071ed80.png">
(Dropdown) After
Payment Address (Before)
Payment Address (After)

Swap UX Cleanup

---

package-lock.json
package.json
webpack_config/webpack.prod.js

Some of our modules end up with ES6+ code in them as they're meant for a purely node environment. We could pull request and fix every problem, but it's killing our `npm run build` right now. As a quick stopgap for that, I've switched the prod webpack config to use babel-minify / babili now. In addition to handling those cases, I'm also seeing some huge file size improvement:
Time: 32712ms
```
Asset                 Size          Chunks               Chunk Names
client.113ef751.js    4.88 MB       0  [emitted]  [big]  client
vendor.a1d0626c.js     196 kB       1  [emitted]         vendor
```
Time: 122573ms
```
Asset                 Size          Chunks               Chunk Names
client.9e40b3d7.js    3.42 MB       0  [emitted]  [big]  client
vendor.3a2c4d92.js     198 kB       1  [emitted] …
```

Use babel minifier instead of uglify

---

common/containers/Tabs/Contracts/components/Deploy/index.tsx
common/containers/Tabs/Contracts/components/Interact/components/InteractExplorer/index.tsx
common/containers/Tabs/Contracts/components/Interact/components/InteractForm/index.tsx
common/utils/helpers.ts

addProperties was used before so that components would stop firing their event handlers even when they were disabled, turns out this was a React bug so it can be removed now.
https://github.com/facebook/react/issues/8308
Diff noise is due to the files being written with width 80 beforehand, when it should be 100 now. #314

Remove addProperties helper

---

common/components/WalletDecrypt/Trezor.tsx

> `Cannot read property 'handleConnect' of undefined`
Was being thrown due to lack of arrow function. This is a quick fix.

Fix Trezor throwing on connect

---

common/components/WalletDecrypt/DeterministicWalletsModal.scss
common/containers/Tabs/SendTransaction/components/ConfirmationModal.scss
common/containers/Tabs/SendTransaction/components/ConfirmationModal.tsx
common/containers/Tabs/SendTransaction/index.tsx

Closes #189. Fixes some weird spacing in the deterministic wallet modal (Not pictured), the send transaction modal at smaller sizes, and the hanging send transaction button.
---
---

Various unlock / send style fixes

---

common/components/ui/NewTabLink.tsx
common/containers/Tabs/GenerateWallet/components/CryptoWarning.scss
common/containers/Tabs/GenerateWallet/components/CryptoWarning.tsx
common/containers/Tabs/GenerateWallet/index.tsx
common/utils/isMobile.ts

Closes #210. Unfortunately, despite looking very similar to the bad browser block (#274) it can't share a whole lot of code, because that feature exists largely outside of the codebase, inside of `index.html`. Fortunately it's not a whole lot of code.
One thing that I did not do, but might be nice, is to default to a different tab (Send? View wallet?) I'd imagine at some point we'll have a more proper "homepage" so I didn't invest too much thought into this, but let me know if you think that's the way to go. Personally, I think it's good to prompt the upgrade anyhow.
Here's a screenshot:

Warn / Prevent Outdated Browsers from Wallet Generation

---

common/store.ts

Closes https://github.com/MyEtherWallet/MyEtherWallet/issues/392
* Replace `swap.bityRates` with initial value when storing in local storage
* Change initial value of `state.bityRates` from `{}` to `null`
bityRates no longer persist in localstorage and are updated on each page load.

Remove Bity Rates from Local Storage

---

common/containers/Tabs/GenerateWallet/components/EnterPassword.tsx
common/containers/Tabs/GenerateWallet/components/PasswordInput.tsx
common/reducers/index.ts
common/vendors.js
package.json

Refactors `redux-form` dependency out of `Generate Wallet` tab and removes package from app. Closes #345.

Remove Redux-Form in Generate Wallet

---

common/components/ui/UnitDisplay.tsx

Pretty simple one that closes #425. Some balances if they were smaller than the digit count would display `0`. Now they'll show `< 0.001`, where the number of sigdigs matches the max digits. I did this at the `UnitDisplay` component level rather than the `formatNumber` util function level since I wasn't sure of all of the use cases for that one. We can move it back if need be.

Display less than for low balances

---

common/actions/rates/actionPayloads.ts
common/components/BalanceSidebar/EquivalentValues.tsx

Closes #510. The fix made on CryptoCompare's side from #462 led to tokens that weren't recognized (Ala beercoin, unicorn etc.) to end up with bogus NaN rates objects. It didn't get caught in testing as this wasn't a change to the code, but to the API instead.
This fix simply excludes them from the rates object, and from the select list of equivalent values.

Fix EquivalentValue.tsx crash on invalid tokens

---

package.json

Force downgrade `webpack-sources` (sup-dependency) to fix build error as described in https://github.com/webpack/webpack/issues/5931
closes https://github.com/MyEtherWallet/MyEtherWallet/issues/509

Fix Production Build

---

common/Root.tsx
common/components/ErrorScreen/index.scss
common/components/ErrorScreen/index.tsx

closes https://github.com/MyEtherWallet/MyEtherWallet/issues/479
Any runtime error that crashes a component will result in a white-screen with no addition details. 
This PR employs React 16's Error Boundary via `componentDidCatch`. We show an error screen when an exception bubbles up to the `Root` component. In the future, we can create more specific error boundaries at lower component to maintain application functionality in the case of an error.

Error Screen on Exception

---

.travis.yml

Currently CI is failing on most builds due to external service issues related to integration testing.
The long-term fix is described in https://github.com/MyEtherWallet/MyEtherWallet/issues/549, but in the meantime I'd like to disable integration testing in CI to prevent frequent CI failures.
Additionally, I've enabled node_module caching in an attempt to reduce npm install failures breaking CI

Minimize CI Failures

---

common/components/Header/components/CustomNodeModal.tsx
common/components/Header/components/Navigation.scss
common/containers/TabSection/Notifications.scss
common/containers/Tabs/Swap/components/CurrencySwap.tsx
common/sass/styles/overrides/buttons.scss
common/sass/styles/overrides/forms.scss
common/sass/styles/tab.scss
common/sass/variables/buttons.scss
common/sass/variables/forms.scss
common/sass/variables/transitions.scss

Closes #521. In an effort to modernize the site a bit, differentiate it from v3, and generally just make things look better, I've made a quick hit-list of visual improvements to the site. Each is its own commit, so if there's anything that people don't like, it should be easy to revert. Please check out the branch and browse around, it's hard to capture _everything_ in screenshots. But here are the changes with screenshots:
I've always hated that this was floating in space, so I gave it a background.
They're now slightly rounded, have quick animations to transition between states, and the default color is now white. I'm also on a mission to remove as many of the `btn-info`s as I can, I really don't think we need that additional tier of color information. We should ideally only ever be …

Minor Visual Touchups

---

common/containers/Tabs/GenerateWallet/components/Template.scss

Closes #592. I just got rid of the equal height column behavior, it was always kind of janky anyway.

Fix generate in safari / get rid of flex behavior

---

common/Root.tsx
common/components/ErrorScreen/index.scss
common/components/ErrorScreen/index.tsx
common/index.html
common/index.tsx
package.json

Fixes the whitescreen mentioned in #512 by adding polyfills. Unfortunately these balloon up the size a bit, but iOS safari is missing a ton in the last version or two. This adds the standard babel-polyfill, and a fetch polyfill. Not my favorite fix, but I think this is better than rejecting a ton of our mobile users.
While I was in the neighborhood, I also added error messages to the red screen of death. Makes it a ton easier to debug on mobile, and should make our user reports 100x better. Feel free to massage the copy:

Fix iOS Safari with Polyfills

---

common/store.ts

We want to prevent spamming the localStorage API during times of frequent store updates, but 1s is too large of a throttle (some parts of the application rely on refreshing directly after changing state).
This PR reduces the throttle to a *better* magical number, 50ms!

Lower LocalStorage Store Throttle

---

common/components/WalletDecrypt/index.tsx
common/containers/Tabs/SignAndVerifyMessage/components/SignMessage/index.tsx

Completes the remaining task on #86 by:
- Making `WalletDecrypt` accept a `disabledWallets` prop that conditionally disables wallet radio buttons.
- Disabling Trezor in the `Sign & Verify Message` tab's `WalletDecrypt`.

Disable Trezor in Sign & Verify Message Tab

---

spec/sagas/swap/liteSend.spec.ts

Quick fix to make `npm test -- liteSend.spec` pass.

Lite Send Test Fix

---

webpack_config/webpack.freezer.js

Freezer will now compile, but we're running into another issue with webpack not exiting. This will probably cause Travis to stall out, so we'll either need to solve that bug or figure out a different way to run this program (perhaps through the `ts-node` package).
Also, the same fix will need to be applied to `webpack.derivation-checker.js`. I would have updated the file but am having issues with Docker and couldn't properly test the changes.

Webpack Upgrade Freezer Fix

---

common/containers/TabSection/Notifications.tsx

Unnecessary nesting caused the notifications to stick around waiting to animate out (Which they never did.)

Fix Notification Close 

---

common/components/Header/components/CustomNodeModal.tsx

https://github.com/MyEtherWallet/MyEtherWallet/commit/f39787152#diff-0fb63f2ecec1a1d8998af37ee70ac8e7R236 hard coded it, so all fields use the `name` field's value. This just undoes that.

Fix custom node form

---

common/components/WalletDecrypt/WalletDecrypt.tsx

MEW + MetaMask is now single click in the happy path (🎉 to the UX) with no degradation to UX on the sad path.
- 250ms is chosen as the magical number to give time for web3 decryption. This works well enough on my machine, but time to unlock may (likely slightly) vary for others. If the unlock time exceeds 250ms, the secondary unlock screen will be shown and then disappear without user action as soon as the wallet is unlocked. I've found 250ms to work well on my testing, but open to feedback on how to increase robustness (hopefully without the corresponding increase in complexity). *This can be solved concretely by using sagas and dispatching state updates based on the web3 unlock response, and I may end up implementing that if this doesn't sit right after a night of sleep 😁)*
- (Minor) …

Attempt Web3 Unlock OnClick

---

common/index.tsx
package.json
webpack_config/webpack.prod.js

Closes #570. This is probably the highest benefit to lowest effort PR I've ever made. Implements the [`offline-plugin`](https://github.com/NekR/offline-plugin) on the production build to cache assets via service workerss, or fallback to app cache. This is really cool for two reasons:
1) Subsequent visits the the site will not re-request assets, and will instead use a cache, resulting in hella fast page loads.
2) You can load myetherwallet.com even if you're offline.
This will be exceptionally good for Android phone users, but will still be great for anyone using Chrome or Firefox. It falls back to AppCache apparently, but I'm not really sure how that behaves.
Here's what a second page load looks like on a 3g connection today:
Here's what it looks like with the service worker installed: …

Implement `offline-plugin` for Service Workers / App Cache

---

.prettierrc
.travis.yml
package.json

Closes https://github.com/MyEtherWallet/MyEtherWallet/issues/601
- Add npm scripts to list formatting diffs 
- [list-difference flag](https://prettier.io/docs/en/cli.html#list-different)
- Check prettier diff in ci

Ensure CI fails on non-prettier compliant PRs

---

webpack_config/webpack.prod.js

When we have mangling enabled, we get the following error:
```
vendor.7f07fec2.js:15 uncaught at  at  
at  
SyntaxError: Identifier 'a' has already been declared
at i (http://127.0.0.1:8080/vendor.7f07fec2.js:24:159237)
at x (http://127.0.0.1:8080/vendor.7f07fec2.js:24:162288)
at y (http://127.0.0.1:8080/vendor.7f07fec2.js:24:161048)
at http://127.0.0.1:8080/vendor.7f07fec2.js:24:163141
at Array.forEach (<anonymous>)
at D (http://127.0.0.1:8080/vendor.7f07fec2.js:24:163114)
at y (http://127.0.0.1:8080/vendor.7f07fec2.js:24:160951)
at a (http://127.0.0.1:8080/vendor.7f07fec2.js:24:159881)
at d (http://127.0.0.1:8080/vendor.7f07fec2.js:24:165548)
at t.a (http://127.0.0.1:8080/vendor.7f07fec2.js:24:158234)
o @ vendor.7f07fec2.js:15
```
(The missing words, ` at at ` are what show up in …

Disable mangle (temporarily?) to fix prod build

---

common/components/WalletDecrypt/components/DeterministicWalletsModal.tsx
common/sagas/deterministicWallets.ts
spec/sagas/deterministicWallets.spec.ts

Closes #692. Frustratingly, Typescript did not catch a change in types because of the way we type Redux Saga `yield call`s explicitly. There are also tests for this functionality, which I was surprised to see didn't catch this either. I'm not intimately familiar with saga testing, so maybe @skubakdj could shed some light on that bit of weirdness.
Either way, this fixes it up and tightens up some of the typing.

Fix deterministic modal token values

---

common/libs/wallet/deterministic/ledger.ts
common/libs/wallet/deterministic/trezor.ts

Closes #718. Also adds some stronger typing to trezor.ts and ledger.ts to make it harder for this to happen again.

Fix Trezor signing + stronger typing

---

common/Root.tsx
common/components/LogOutPrompt.tsx
common/components/WalletDecrypt/WalletDecrypt.tsx
common/components/WalletDecrypt/components/index.tsx

Closes #707. This splits out the NavigationPrompt component into a more self-sufficient connected LogOutPrompt component. Rendered at Root so it's always there, this checks if redux has a wallet whenever the base path changes. If so, it does the normal logout prompt thing.
I think this should be somewhat more robust, since we no longer have the implicit dependency on rendering DecryptWallet all the time to get the logout behavior. It should also allow for the logout prompt if we ever set the wallet state in a non-DecryptWallet way.
Let me know if I bastardized the component beyond recognition.

Fix Logout Prompt

---

common/components/WalletDecrypt/WalletDecrypt.tsx
common/config/data.ts

- Increase timeout for web3 auto-login to 1s.
- NOTE: timeout is only the maximum wait time before secondary view is shown. Send view will be shown immediately on web3 resolve, so 1s is the upper-bound on how long the UI will be unresponsive while web3 is resolving. On a fast connection, I get a resolution in < 250ms, but we can opt to show a loading indicator and a higher upper-bound if we discover that the user experience is poor in practice.
- Don't attempt login when web3 provider is not available

Web3 Improvements

---

webpack_config/webpack.prod.js

Closes https://github.com/MyEtherWallet/MyEtherWallet/issues/512
Discovered it was a minifier rule + moment issue. Posted the fix here: https://github.com/webpack/webpack/issues/4510#issuecomment-355868894
>Confirmed that removing babel-minify-webpack-plugin stopped the error from showing up.
>
>EDIT: Turns out this is from the property literals minifier rule. I had moment locales in my build, and one of the properties was the Â character. Most browser could handle it, not Safari!

Fix Safari / iOS illegal character syntax error

---

webpack_config/webpack.prod.js

Closes #512 (No, really.)
I was on the right track before, but missed the right fix due to caching. Unfortunately file hashes come _before_ minification, not after, so altering the uglifier doesn't bust cache.
It turns out it's a _combination_ of `evaluate` and `propertyLiterals`. [This line in Lodash](https://github.com/lodash/lodash/blob/6cb3460fcefe66cb96e55b82c6febd2153c992cc/.internal/deburrLetter.js#L6) was getting eval'd from `\xc2` to `Â`. You can actually try it in your browser if you want.
```
npm run build
http-server dist # or whatever your server of choice is
```
Open in Safari or iOS simulator. Make sure you clear the cache (In safari it's Develop -> Empty Cache) and completely restart the browser, otherwise you may be loading cached JS.

Fix Safari / iOS illegal character error (forreal this time)

---

common/index.tsx
package.json
webpack_config/webpack.prod.js

This reverts commit ef506c54d6ee94ec5756c8d403ffdbe9b94881d4. 
Cache invalidation issues discovered with testing in the wild and the general difficulties related to cache invalidation call for a temporary revert. 
When we have more resources to ensure that the optimizations related to app caching don't have unintended negative consequences, we can re-enable.

Revert "Implement `offline-plugin` for Service Workers / App Cache"

---

common/sagas/swap/orders.ts

This PR closes #770 
I did not remove the action dispatcher to stop the timer when the destination kind is sent. In the case that our network is slow and fails to catch the received order, I think it's fairly harmless to leave it in the completion of the order (when the destination kind is sent).

Stop Timer when Swap Order is Received

---

common/components/WalletDecrypt/WalletDecrypt.tsx
common/components/WalletDecrypt/components/WalletButton.scss

Digital Bitbox is currently unsupported, so we can remove it from the account view until that functionality is developed.
I've made the simplest change to remove it while maintaining most of the existing configuration for an easy re-addition when it's ready.

Remove Digital Bitbox from account view

---

common/components/ui/Modal.scss
common/components/ui/Modal.tsx
common/containers/OnboardModal/components/BlockchainSlide.tsx
common/containers/OnboardModal/components/FinalSlide.tsx
common/containers/OnboardModal/components/InterfaceSlide.tsx
common/containers/OnboardModal/components/NotABankSlide.tsx
common/containers/OnboardModal/components/OnboardSlide.scss
common/containers/OnboardModal/components/OnboardSlide.tsx
common/containers/OnboardModal/components/SecureSlideOne.tsx
common/containers/OnboardModal/components/SecureSlideThree.tsx
common/containers/OnboardModal/components/SecureSlideTwo.tsx
common/containers/OnboardModal/components/WelcomeSlide.scss
common/containers/OnboardModal/components/WelcomeSlide.tsx
common/containers/OnboardModal/components/WhyMewSlide.tsx
common/containers/OnboardModal/components/WhySlide.tsx
common/containers/OnboardModal/index.scss
common/containers/OnboardModal/index.tsx
package.json

Onboarding is our first introduction to most users, so it's good to put our best foot forward. This PR revisits #611 and puts a bit of polish on it. The full list of changes are:
* Increases Modal's width to better fit in the content.
* Restore the image side behavior so that images are sometimes on the left, not always on the right
* Allows modal to dynamically size its height.
* This reduces some awkward whitespace, and makes it so you can't just jam on the "Next" button since it moves a bit, should slow some people down to at least catch the headlines.
* Restore the alert style on the opening modal
* Provide a mobile-friendly progress stepper.
* This module's markup kind of sucks, so the restyling code is heinous. Sorry.
* Scrolls the user to the top after hitting "Next" or "Previous" …

Onboarding Style Improvements

---

common/Root.tsx
common/components/AddressField.tsx
common/components/AmountField.tsx
common/components/ConfirmationModal/components/Details/Addresses.tsx
common/components/GasLimitField.tsx
common/components/NonceField/NonceInput.tsx
common/components/SendButtonFactory/OnlineSend.tsx
common/components/SendButtonFactory/SendButtonFactory.tsx
common/components/ui/AuxComponent.tsx
common/components/ui/Expandable.tsx
common/components/ui/index.ts
common/containers/Tabs/Contracts/components/Interact/components/InteractExplorer/components/Fields.tsx
common/containers/Tabs/Contracts/components/Interact/components/InteractExplorer/index.tsx
common/containers/Tabs/SendTransaction/components/Fields/Fields.tsx
common/containers/Tabs/Swap/components/LiteSend/Fields.tsx
common/containers/Tabs/Swap/components/LiteSend/LiteSend.tsx

Closes https://github.com/MyEtherWallet/MyEtherWallet/issues/803
`Aux` was being as used a pass-through component to nest children without creating an unnecessary div. With React 16, we now have React Fragments which is the standard way of accomplishing this.

Replace <Aux> with React Fragements

---

common/config/data.ts

As of https://github.com/kvhnuke/etherwallet/issues/1400, RSK node is no longer being maintained. 
It has been removed on V3, and we can follow suite on V4.
While we intend to support UBIQ, EXP, and ETC, the current integration is not robust enough for a release candidate (as seen in issues such as https://github.com/MyEtherWallet/MyEtherWallet/issues/814 and unhandled wallet format accessibility issues).
We also make assumptions about Ethereum as the network in the Payment request tab, and potentially other yet unknown areas.
After a more complete integration and testing we can re-enable these networks.

Remove non-Ethereum networks

---

common/components/ui/UnlockHeader.tsx
common/sagas/config.ts
spec/sagas/config.spec.ts

Closes https://github.com/MyEtherWallet/MyEtherWallet/issues/642
I believe wallet and transaction state is the only state that needs to get reset when changing networks. I couldn't think of any any other state that would be need to be reset during a network change, but please comment if you think there is.
Branched off of https://github.com/MyEtherWallet/MyEtherWallet/pull/813, will re-base branch after merge.

Change network without window refresh

---

common/components/BalanceSidebar/PromoComponents/Bity.tsx
common/components/BalanceSidebar/PromoComponents/Coinbase.tsx
common/components/BalanceSidebar/PromoComponents/HardwareWallets.tsx
common/components/BalanceSidebar/PromoComponents/index.ts
common/components/BalanceSidebar/Promos.scss
common/components/BalanceSidebar/Promos.tsx

Closes https://github.com/MyEtherWallet/MyEtherWallet/issues/750
- Seperate promos into individual components
- creating banners is becoming too difficult with a one-size-fits-all component, separating them makes them easier to write and compose
- Rotate promos every 10 seconds
- Add fade animation when transitioning between promos

Rotate promos

---

common/containers/Tabs/SignAndVerifyMessage/components/SignMessage/SignButton.tsx
common/containers/Tabs/SignAndVerifyMessage/components/VerifyMessage/index.tsx
common/containers/Tabs/SignAndVerifyMessage/index.tsx
common/libs/signing.ts
spec/libs/signing.spec.ts

Closes #869 
* Renames fields on the signed message object to match V3, so that messages are compatible
* Adds unit tests for signing
* (Subjective) Renames subtabs from "Sign" and "Verify" to "Sign Message" and "Verify Message"
* OK, I kind of slipped this one in there. Those strings are already translated, and the single words alone had a small click target and looked kind of awkward IMO. Will revert if this is undesirable.
1. Go to /sign-and-verify-message/sign and sign a message
2. Go to /sign-and-verify-message/verify and verify that message
3. Go to https://www.myetherwallet.com/signmsg.html and verify the same message
4. Go to https://www.myetherwallet.com/signmsg.html and sign a new message
5. Go back to /sign-and-verify-message/verify and verify the new message

Sign Message v3 compatibility

---

common/components/GasSlider/components/AdvancedGas.scss
common/components/GasSlider/components/AdvancedGas.tsx

Closes #834 
Very small fix, aligns the nonce field with the gas price and gas limit fields in the advanced gas price selector.

Fix nonce field alignment

---

package.json

We don't use `store2`, but it's listed in `package.json`.

Remove store2 dependency

---

.travis.yml

From testing, this brings down CI completion time from ~5 minutes to ~2.
- remove docker dependency (due to integration tests no longer being run in CI)
- streamline jobs

Improve CI Performance

---

common/containers/Tabs/SignAndVerifyMessage/components/VerifyMessage/index.tsx

Closes #945. Run any pasted text into the validator textarea through a JSON.parse / JSON.stringify cycle. This will make sure the user sees the actual JSON that ends up in the validator.
Note that the validator always showed the correct validated message in the green textbox below. This just makes it so that the JSON visually lines up with that as well.

MEW-01-003 - Parse JSON pasted into signed message verifier

---

webpack_config/makeConfig.js

This changes the dev tool to `'cheap-module-source-map'` which makes debug builds much faster for people wanting to use the chrome debug plugin on vscode. It loses column breakpoints but should be worth the tradeoff in build speed performance.

Change debugging option for vscode users

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Closes #1028. The main contributor guidelines [live on the wiki](https://github.com/MyCryptoHQ/MyCrypto/wiki/Contributor-Guidelines) so they can be updated without needing to PR. I definitely expect edits and suggestions to this, so don't be shy.
One thing that was lacking was test-writing documentation. I think we should probably go into that more somewhere.

Contributor Guidelines

---

common/components/WalletDecrypt/components/InsecureWalletWarning.tsx

Closes #1059
Adds the missing `key` attribute to the insecure wallet checkboxes.

Add missing key attribute

---

common/components/Header/components/CustomNodeModal.tsx
common/components/ui/Modal.scss
common/components/ui/Modal.tsx

Built on top of #1141.
Allows specifying a `maxWidth` parameter to modals, that forces the modal to be 100% wide, maxxing out at that width. Currently modals use flex sizing which is great when it works, but can be awful when it decides to shrink inexplicably. That behavior will still be there by default, but you can now specify a max width for the modal to try to target. Note that it's a maxWidth and not width, because all modals should be designed to be responsive for smaller sizes.
* Add `maxWidth` param to modals
* Set `maxWidth` for custom node modals to prevent weirdness
1. Run app on `modal-max-width` branch
2. Open up add custom modal
3. Shrink down your browser
4. Make sure it never looks weird
The difference in banner is just because I was running the old one on …

Allow modals to specify max width

---

common/components/Footer/PreFooter.scss
common/containers/TabSection/index.tsx
common/sass/styles/scaffolding.scss

No issue currently open for this.
Align the footer to the bottom of the page 
- Add flexbox styles to `.page-layout` to align the footer to the bottom of the page
- added `display: flex; flex-direction: column; flex-wrap: nowrap;`
- added `<div className="flex-spacer" />` to fill empty space and push the footer (and prefooter) to the bottom of the page
- reduce the margin on `<Prefooter />` from `5rem` to `2rem`
Before: 
After:

Align footer to bottom

---

common/components/BalanceSidebar/AccountInfo.scss
common/components/BalanceSidebar/AccountInfo.tsx

Just some minor touchups and fixes to copying addresses
* Checksum the copied address
* Convert classnames to SuitCSS
* Adjust size and spacing to de-emphasize the copy button

Copy address touchups

---

common/containers/Tabs/SendTransaction/components/RequestPayment.tsx

Payment Request QR code doesn't show due to changing the default unit value from `ether` to `ETH`. 
This PR updates the hard-coded check for `ether` to `ETH`.
A more in-depth long-term fix should include the use of a selector to check against ether unit's instead of hard-coding in the component.

Fix unit value

---

common/components/ui/Input.tsx

Closes #1201.
Blurs number inputs when scrolled on. While preventing default was an option, it had the annoying side effect of making focused number inputs no scroll zones, stopping your page from scrolling if you were moused over one. I found that behavior to be _really_ annoying, so I went with blurring instead. My assumption is that if you're scrolling, you're probably done with the input anyway.
* Blur number inputs when scrolled while focused.
1. Run app on `fix-amount-scroll`
2. Go to /account page
3. Unlock wallet
4. Focus and set amount field to some numeric value
5. Scroll on it
6. Confirm number doesn't change

Prevent Scrolling From Altering Amount Field

---

common/components/ui/Modal.scss

Closes #1026
Aligns modals to the top of the page, rather than the center, to avoid modals going "blurry" on lower dpi devices. This would happen when the height of the modal plus the height of the window is an odd number, or if the modal is a decimal height.
* Align modal to the top of the page, plus some gutter (30px)
* Reduce the gutter around modals on mobile to reduce content wrapping (10px gutters on all sides)

Fix Blurry Modals

---

package.json

@HenryNguyen5 and myself have both experienced issues with fresh node_modules installs with the last two version bumps of `hard-source-webpack-plugin`.
This PR reverts the last two version bumps.

Revert hard-source-webpack-plugin updates

---

common/components/BalanceSidebar/PromoComponents/Coinbase.tsx
common/components/BalanceSidebar/Promos.tsx

Closes https://github.com/MyCryptoHQ/MyCrypto/issues/1284
The Coinbase widget does not currently pass the correct instantiated wallet address, and instead passes a hardcoded address (presumably added during testing).
This PR connects `Promos` to redux state to grab the wallet instance, and then passes the correct address to `Coinbase` when the wallet instance exists.

Fix Coinbase Widget

---

package.json

Apparently the maintainer of this package released a breaking update, and rather than patch again to fix it, rolled back the version, so 3.3.2 no longer exists: https://github.com/adriantoine/enzyme-to-json/issues/98. This breaks the build.

Roll Back enzyme-to-json Revoked Version

---

package.json

Closes #1344.
Bump node-sass to `4.8.3` to fix the malloc crash.

Fix failing builds from node-sass

---

common/components/ui/Input.scss

Closes #1392 
Fixes textarea height being set to `3rem`. Adds truncation on input placeholders
- Add `.input-group-input[placeholder] { text-overflow: ellipsis }`
- Add `textarea.input-group-input { height: initial }`

Fix textarea styles

---

jenkins/Jenkinsfile.darwin
jenkins/Jenkinsfile.linux.develop
jenkins/Jenkinsfile.linux.master

In the past, there have been NPM-based [attacks that steal environment variables](https://www.bleepingcomputer.com/news/security/javascript-packages-caught-stealing-environment-variables/) on `npm install`. This PR hardens our Jenkins setup by separating out the build pipeline into three steps: (1) module install, (2) project build, and (3) build artifact upload. For each step, sensitive environment variables are explicitly overwritten with `REDACTED` if they're not required for that step.

Harden Jenkins Pipelines

---

common/api/shapeshift.ts
common/containers/Tabs/Swap/components/CurrencySwap.scss
common/containers/Tabs/Swap/components/CurrencySwap.tsx
common/containers/Tabs/Swap/components/CurrentRates.scss
common/containers/Tabs/Swap/components/CurrentRates.tsx

Closes #1354
This was an intensely satisfying PR. It reduces the number of requests to Shapeshift by n<sup>2</sup> where n is the number of swappable tokens. It does so by simply removing the requests for each and every pair, and instead using the data we get initially from https://shapeshift.io/marketinfo. That endpoint already includes rates for every swap pair, so the extra requests are unnecessary.
While I was in the neighborhood, I resized the spinners to be the same size as the content that loads in. This'll prevent the page from "jumping" when they load.
* Remove unnecessary swap rates requests
* Add explicit heights to loaders to make them match the size of the content that will load in
1. Load /swap
2. Confirm content doesn't jump
3. Confirm rates are correct
4. Initiate swap
5. …

Reduce Shapeshift Requests

---

webpack_config/makeConfig.js

Closes #1464
As of Webpack 4, workers unfortunately get some HMR code injected with them. These refer to the global `window` object, which doesn't exist in the worker context. So in dev, the global object will be changed to `self` which works in all newer JS environments.
1. Generate a keystore file in dev

Fix keystore worker in dev

---

common/Root.tsx
common/containers/Tabs/SendTransaction/index.tsx

Closes #1481
Renders QR signer modal always, in case there's a tx to be signed.
1. Deploy or interact with contract with parity signer wallet
2. Confirm QR signer pops up

Fix Parity QR Signer on Non Send Pages

---

common/components/WalletDecrypt/components/Keystore.tsx
common/components/WalletDecrypt/components/ViewOnly.scss
common/components/WalletDecrypt/components/ViewOnly.tsx
common/components/ui/Input.scss
common/reducers/wallet.ts
common/sass/styles/overrides/react-select.scss
common/sass/variables/forms.scss
common/selectors/wallet.ts
common/store/store.ts
common/translations/lang/en.json
spec/reducers/wallet.spec.ts

Closes #855
This is an MVP for #855 before we implement global unlock / address book. I think this feature is valuable enough to have a quick implementation to make it into our first release candidate.
This simply keeps track of the last 10 addresses you've unlocked in order, persists them to local storage, and presents them on the View Only unlock screen. I think this feature will be replaced / enhanced by the aforementioned, but it should be easy to remove and replace without much fuss.
* Add `recentAddresses` array to `state.wallet`
* On WALLET_SET, add the address to the front of the `recentAddresses` array, dedupe and trim to 10
* Added conditionally rendered select list to view only, on select unlocks that address
* Convert view only address to input from textarea
* Update view only …

Show Recent Addresses on View Only

---

jenkins/Jenkinsfile.darwin.signing

Adds config to enable the signing of Mac builds directly in Jenkins.

Add Jenkins Config for Mac Signing

---

common/sagas/config/node.ts
spec/reducers/config/config.spec.ts

Closes #1681
I think this is a fair compromise between the UX of not letting users switch to nodes that won't connect vs allowing users to switch to other networks when offline. Allows a user to switch without fail if they're currently offline. Still attempts to fetch a block and get them back online, even if offline though.
However, maybe the UX tradeoff isn't worth it, and we should just let users switch to offline nodes no matter what. I'm definitely open to that discussion!
1. Load the page and make sure you're connected to a network
2. Attempt to switch to another node, make sure that works
3. Set yourself offline, and quickly switch to another node (Simulating connecting to an "offline node"), confirm it doesn't allow you to connect
4. Get yourself into the offline state (triggered …

Allow Network Change Offline

---

common/components/WalletDecrypt/components/DeterministicWalletsModal.scss
common/components/WalletDecrypt/components/DeterministicWalletsModal.tsx
common/components/WalletDecrypt/components/LedgerNano.tsx
common/components/WalletDecrypt/components/Mnemonic.tsx
common/components/WalletDecrypt/components/Trezor.tsx
common/selectors/config/wallet.ts

Closes #1563
Removes duplicate dpaths, and treats each option as a unique option rather than always selecting the first instance of the dpath. Also made some quick improvements to the modal while I was here.
* Fixes de-duplication in the dpaths selector function
* Pass around full `DPath` objects to wallet decrypt components & deterministic modal, rather than just the dpath string.
* This makes it so that if you select `Default (POA)`, that it shows up as the selected option, whereas before it would should `Default (ETH)` since they have the same dPath, and ETH is the first in the list.
* Improve deterministic wallet modal UI
* When no token is selected, show small, light `N/A` text instead of `???`
* Token balances now show spinner while loading
* Gets rid of constantly persistent …

Fix Duplicate DPaths & Deterministic Modal Improvements

---

common/libs/nodes/rpc/utils.ts
common/sagas/transaction/network/gas.ts

Patches #1617
After testing, only `estimateGas` is affected by this issue. So whenever an estimation call is sent, a zero value `to` value e.g `0x` is set to undefined instead.

Fix Estimate Gas

---

common/api/rates.ts

No [public] issue associated with this PR.
Replaces cryptocompare with proxy.mycryptoapi.com for rate requests.
In an effort to increase user privacy, an effort is made to reduce requests to third parties directly.
1. Open dev tools
2. Unlock any wallet format
3. Check to make sure equivalent values still load
4. Verify that requests is are being made proxy.mycryptoapi.com instead of min-api.cryptocompare.com

Use proxy.mycryptoapi.com for rates

---

common/containers/Tabs/SupportPage/index.tsx
electron-app/main/menu.ts

Closes #1728
Adds version to help menu and on support us page that more or less has all of the same footer information.

Show version in Electron

---

jest_config/jest.config.json

If jest tests ever get copied to dist, they'll get matched and run (and promptly fail). This ignores the directory for jest.
* Add `dist` as a ignored directory for jest
1. Transpile tests into dist
2. Run `yarn test`
3. Tests should run and complete

Ignore dist for jest tests

---

common/components/BalanceSidebar/EquivalentValues.tsx
common/components/BalanceSidebar/TokenBalances/Balances.tsx
common/components/CurrentCustomMessage.tsx
common/components/GenerateKeystoreModal/index.tsx
common/components/SendButtonFactory/OnlineSend.tsx
common/components/SubTabs/index.tsx
common/components/TXMetaDataPanel/TXMetaDataPanel.tsx
common/components/TXMetaDataPanel/components/SimpleGas.tsx
common/components/TogglablePassword.tsx
common/components/TransactionStatus/TransactionStatus.tsx
common/components/WalletDecrypt/WalletDecrypt.tsx
common/components/WalletDecrypt/components/DeterministicWalletsModal.tsx
common/components/WalletDecrypt/components/LedgerNano.tsx
common/components/WalletDecrypt/components/Mnemonic.tsx
common/components/WalletDecrypt/components/Trezor.tsx
common/components/renderCbs/UnitConverter.tsx
common/components/ui/QRCode.tsx
common/components/ui/SwapDropdown.tsx
common/containers/Tabs/CheckTransaction/components/TxHashInput.tsx
common/containers/Tabs/CheckTransaction/index.tsx
common/containers/Tabs/Contracts/components/Interact/components/InteractForm/index.tsx
common/containers/Tabs/SendTransaction/components/RequestPayment.tsx
common/containers/Tabs/SendTransaction/components/WalletInfo.tsx
common/containers/Tabs/Swap/components/CurrencySwap.tsx
common/containers/Tabs/Swap/components/CurrentRates.tsx

In preparation of React's [async rendering](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#updating-state-based-on-props) and depreciation of bug prone lifecycle methods, all unsafe lifecycle methods have been marked as such for better visibility. 
* componentWillMount -> UNSAFE_componentWillMount
* componentWillReceiveProps -> UNSAFE_componentWillReceiveProps
* componentWillUpdate -> UNSAFE_componentWillUpdate

Mark depreciated react lifecycles as unsafe

---

common/Root.tsx

Electron hasn't yet graduated to a stable launch, and as such, we shouldn't show the stable welcome message on Electron.

Don't show new welcome message on Electron

---

common/libs/contracts/ABIFunction.ts

Closes #1726
We weren't stripping the hex prefix before turning it into a buffer. Unfortunately, a hex prefixed hex string is invalid in the context of `Buffer.from(<hexstring>, 'hex')`, which returns an empty buffer(!) instead of throwing.

Strip hex prefix for bytes inputs

---

common/containers/Tabs/Contracts/components/Deploy.tsx
common/containers/Tabs/Contracts/components/Interact/components/InteractExplorer/index.tsx
common/containers/Tabs/Contracts/index.tsx

Closes #1849
* Clears transaction state on tab change
* Moves contract interaction state flag to only occur in the contract interact component, this is so the `to` field is still cleared between tab changes, but when resets occur in component (like accessing a wallet) the `to` field will still persist to make a transaction within the contract interact component

Clear transaction state on tab changes

---

common/libs/nodes/configs.ts

Node used and maintained by Chainkorea (https://github.com/chainkorea)
+ HTTPS & Load Balancing through AWS (https://github.com/chainkorea/docker-etc-lb)
+ Blockchain up to date.
+ Response time ~150-350ms
+ KR servers
+ Live stats page on https://classicstats.net

Add ETC Chainkorea node

---

common/components/WalletDecrypt/components/LedgerNano.tsx

closes https://github.com/MyCryptoHQ/MyCrypto/issues/1914
0. Connect to your computer your Ledger device (with Ethereum App runnung and web browser setting Enabled) 
1. Go to: https://www.mycrypto.com/account
2. Click on "Ledger - Connect & sign via your hardware wallet"
3. Click on "Connect to Ledger Wallet"
4. From the "Addresses" dropdown menu select "Custom", then enter `m/44'/60'/0'/0` and click on green tick button.
5. Select address `#1` (or any other) and click "Unlock".
6. Click "Display address on Ledger".
7. Compare the address displayed on Ledger device and the address on MyCrypto. **They should now be the same, instead of differently as before**

Set custom dPath for address verification on ledger

---

common/components/PaperWallet/index.tsx
common/components/ui/Identicon.tsx

Closes #1824
Fixes the paper wallet by hex prefixing and checksumming the address
1. Generate keystore file wallet
2. Proceed to print wallet phase
3. Confirm address is hex prefixed, checksummed, and has an identicon

Fix paper wallet address & icon

---

common/Root.tsx

Preserves query params by using the `RedirectWithQuery` routing component instead of `Redirect`. Closes #1863.

Bug Fix for #1863

---

common/components/TXMetaDataPanel/TXMetaDataPanel.tsx

Moves `resetTransactionRequested()` call from `componentDidMount` to `componentWillMount` in `TXMetaDataPanel.tsx`. Closes #1813.
Query params are parsed and set inside components, so resetting transaction state _after_ render was wiping it out.

Bug Fix for #1813

---

common/components/NonceField.tsx
common/components/ui/Input.scss
common/components/ui/Input.tsx
common/sass/styles/overrides/react-select.scss

Resolves https://github.com/MyCryptoHQ/MyCrypto/pull/1917#discussion_r194201214
Cleans up the way inputs show valid and invalid to be a little bit less class-soupy, and provide more control from props.
* Adds a `showInvalidWithoutValue` prop to inputs to do just that.
* Removes the `has-blurred` and `has-value` classes in favor of only adding `invalid` if those cases are satisfied.
* This should reduce style complexity and not lead to "untrue" classes, e.g. not having the `has-blurred` class even if you have blurred.
* Minor type cleanups and comments for clarity.
* Select `invalid` would never occur with the old classes, and input `valid` was removed, but no comments indicated these two cases.
1. Erase nonce and blur the input

Clean up input validation logic & classes

---

common/components/ui/Input.tsx

Shows red border highlight around the Nonce field when empty. Primarily used to help users who are used to the flow with a working internet connection be alerted that they need to enter an addition field (nonce) while offline.

Show invalid for Nonce Field when empty

---

spec/reducers/config/__snapshots__/config.spec.ts.snap

After merging the fix for [#1938](https://github.com/MyCryptoHQ/MyCrypto/pull/1938), a single snapshot was not updated to reflect the additions. This PR simply adjusts the snapshot with the newer generated snapshot, fixing the test.

Update config snapshot

---

common/sagas/config/node.ts

Closes #1949
Adds a `CHANGE_NODE_SUCCEEDED` if the requested node to change to matches our current one. Otherwise it would get stuck in the requested state forever.
* High level
* Changes that
* You Made
1. Log in with metamask
2. Change tabs (logout)
3. Confirm you're on the node you want to be

Fix Stuck Node on Metamask Logout

---

common/containers/Tabs/Contracts/components/Interact/components/InteractExplorer/index.tsx
common/libs/contracts/ABIFunction.ts

Closes #1872
Adds support for multiple undefined input names by substituting their names for an index. This guarantees that each input name will still be unique. Before, this substitution did not happen, so if there was >1 undefined input name for a function, then they would have their states bound together since they would be under the same key in a map.
* Use index for unique name during ABI function instantiation 
* Change contract interaction to generate its mappings the same way so function calls get properly encoded
1. Go to contract -> interact tab
2. Use the following ABI 
```json
[ 
{
"constant": true,
"inputs": [{ "name": "", "type": "uint256" }, { "name": "", "type": "address" }],
"name": "whitelist",
"outputs": [{ "name": "", "type": "bool" }],
"payable": false, …
```

Support undefined input names

---

common/config/dpaths.ts
common/features/config/__snapshots__/sagas.spec.ts.snap
common/features/config/networks/static/reducer.ts
common/libs/nodes/configs.ts
shared/types/network.d.ts

EOS Classic is a combination of EOS & ETH protocol
+ Homepage: https://eos-classic.io
+ Node: https://node.eos-classic.io
+ BIP44 2018 / Chainid 20 ( https://github.com/satoshilabs/slips/pull/279 )
+ Already merged on MyEtherWallet ( https://github.com/kvhnuke/etherwallet/pull/1903 )
* This PR adds EOS Classic node support
* Fixed chain id from the old pr
* Fixed snapshot

[EOSC] Add EOS Classic node support

---

common/features/config/__snapshots__/sagas.spec.ts.snap
common/features/deterministicWallets/__snapshots__/sagas.spec.ts.snap
common/features/handleMetaMaskPolling.ts

Closes #2013
A mistake in the MetaMask refresh implementation caused the plage to refresh when the `web3Wallet` instance had no `network` property.
* Unnecessary refresh is avoided by checking for existence of network in the refresh check.
1. Access any wallet besides MetaMask.
2. The wallet should not boot you out after unlocking.

Tighten web3 network change refresh validation

---

common/features/store.ts

Closes #2016 
Browsers without MetaMask were caught in a refresh loop due to the web3 check failing.
* The poll doesn't start unless `web3` is detected.
1. Load the app in a browser without MetaMask.
2. Use the app as normal without infinite refreshing.

Check for `web3` before polling network status for MetaMask

---

common/index.html
webpack_config/makeConfig.js

Closes #2003.
The CSP is injected only when building for production as a few of our dev tools use `eval` for hot reloading.

MC-01-003: Add CSP to Meta Tag

---

common/features/config/networks/static/reducer.ts

Closes #2010
This change hides tabs not supported (up to now) by both RSK testnet and mainnet. It avoids errors and misundertstandings.
* Adds `TAB.ENS` and `TAB.SWAP` to `unsuppportedTabs` field in `StaticNetworksState`
1. Select RSK network and check that ENS and Swap tabs are not visible.
2. Change to other network and check that ENS and Swap tabs do are visible.

Hide unsupported tabs by RSK

---

common/translations/index.tsx

Closes #(none, reported in dream-team by @Azarielle)
Translation algorithm was changed to avoid the issue of overwriting other variables.
* `translateRaw` now replaces all `$` with `__` prior to replacing variables.
1. Open the TXStatus tab.
2. Ensure the blockchain links are accurate.

Adjust translation algorithm

---

common/components/ConfirmationModal/components/Body/Body.tsx
common/containers/Tabs/SendTransaction/components/Fields/Fields.tsx
common/translations/lang/en.json

Closes #1992
Attempting to send two back-to-back transactions to an address triggered a Red Screen of Death because of an uncaught error in a selector.
* When the `getSerializedParams` selector fails because the nonce value did not change, the `<Fields />` component now handles that error by showing a notification to the user and updating to clear the confirmation modal.
1. Log in to a wallet that is not Web3 (e.g. via keyfile)
2. Make a small transaction to an address.
3. Switch to the `Request Payment` tab, then switch back.
4. Re-enter the same address and value as before.
5. Press the 'Send' button, then press 'Send' in the confirmation modal.
6. The confirmation modal should disappear, the `<Fields />` component should be clear, and a notification should alert the user about the …

Handle back-to-back similar transactions

---

common/config/tokens/eth.json

Current GBX token decimal is incorrect and should be changed to 8, will currently display an incorrect balance in MYC.
https://etherscan.io/token/0x12fcd6463e66974cf7bbc24ffc4d40d6be458283

Update GBX token decimal

---

shared/enclave/server/views/passphrase.html

Closes #2073
Empty passphrase was not allowed for Trezor.
* Empty passphrase is now allowed for Trezor.
1. Attempt to authenticate via a Trezor with passphrase enabled.
2. When the passphrase prompt appears, press "Enter"
3. You should still be allowed in.

Remove empty check

---

common/components/WalletDecrypt/WalletDecrypt.tsx

Closes #1965
The new wallet order should be `Hardware` -> `Secure` -> `Insecure`.
* Changed first row to `Hardware`
* Changed second row to `Secure`
* Added a third row to `<WalletDecrypt /> as `Insecure`
1. Visit the site.
2. Make sure all nine options appear.
3. Make sure all unlockable options can unlock.

Change order of wallet unlock options

---

common/components/WalletDecrypt/WalletDecrypt.tsx

Quickfix for making sure icons appear on middle row for wallets.

Add icon for middle row

---

package.json
yarn.lock

There was an issue with our version of `electron`.

Change dangerous electron version

---

package.json
yarn.lock

Whoops! It looks like we have tests that prevent unsure versioning. It makes sense from a security standpoint.

Remove non-exact dependency on electron

---

common/libs/wallet/deterministic/trezor.ts

for some larger chainId, Trezor returns signature_v bit only. simply recalc signature_v

support full 32bit chainId for Trezor

---

common/components/BalanceSidebar/EquivalentValues.tsx
common/components/TXMetaDataPanel/components/FeeSummary.tsx
common/features/config/networks/static/reducer.ts
common/features/selectors.ts
shared/types/network.d.ts

Closes #2091
RSK currency symbol is SBTC "Smart Bitcoin" that crashes to SBTC "Super Bitcoin". This generates mistakes in rate conversions because MyCrypto API returns "Super Bitcoin" rate for SBTC.
* Addition of new configuration parameter hideEquivalentValues (optional boolean) that avoids showing rate conversions and, consequently, misunderstandings operating with RSK network.
1. Select RSK network
2. Go to "View&Send" / "Contracts" tab and prepare a transaction.
3. Check that no USD values are shown.
4. Check that "Equivalent Values" box shows a message about not showing values for this unit.

Hide equivalent values for RSK network

---

common/config/dpaths.ts
common/features/config/__snapshots__/sagas.spec.ts.snap
common/features/config/networks/static/reducer.ts
common/libs/nodes/configs.ts
shared/types/network.d.ts

Closes #2157
bitcointalk ANN    : https://bitcointalk.org/index.php?topic=2844280.0
homepage           : https://akroma.io
block explorer     : https://akroma.io/explorer
network statistics : http://stats.akroma.io
slip0044 index     : 200625
chainId            : 200625
[Akroma (AKA) is supported in Trezor ONE firmware version 1.6.3](https://blog.trezor.io/trezor-one-firmware-update-1-6-3-73894c0506d)
The official Ledger Nano S Akroma application was released last week:
[![ledger announcement tweet](https://pbs.twimg.com/media/DmQUzLaW4AAwnI7.jpg:large)](https://twitter.com/LedgerHQ/status/1036976685579685894)
cc: @detroitpro
cc: @akroma-project

Add support for Akroma

---

common/features/config/networks/static/reducer.ts

Closes #2168 
Closes #2170 
Closes #2172 
Closes #2174 
This was originally sent as individual pull requests, but, as requested, I am resending them now all at once.
* Enable Ledger Nano S support for Callisto
* Enable Ledger Nano S support for Musicoin
* Enable Ledger Nano S support for EtherGem
* Enable Ledger Nano S support for GoChain
This pull request supercedes #2169 , #2171 , #2173 and #2175 -- Please refer to those individual pull requests for the corresponding screenshots.
Merging this PR also:
Closes #2169 
Closes #2171 
Closes #2173 
Closes #2175

Enable Ledger Nano S support for Callisto, Musicoin, EtherGem & GoChain

---

common/components/ui/UnlockHeader.scss
common/components/ui/UnlockHeader.tsx

Removes unnecessary (X) button on the wallet selection screen after a user clicks "Change Wallet". Users should not be able to log back in without first going through the proper method.
* Removed the (X) button from UnlockHeader.tsx
* Removed styles for the (X) button since they aren't being used anywhere else
1. Login with the wallet of your choice
2. Click change wallet
3. The (X) button should be gone
*Before*
*After*

Remove (X) button when changing wallets

---

common/config/tokens/eth.json

Adding CARD token.
Website: https://cardstack.com
ENS: `cardstack.eth`
Medium: https://medium.com/cardstack
Telegram: http://t.me/cardstack
Twitter: https://twitter.com/cardstack
GitHub: https://github.com/cardstack
Blog post discussing our recent token upgrade: https://cardstack.com/zos-upgrade
Thanks!

Added CARD token address

---

common/config/dpaths.ts
common/features/config/__snapshots__/sagas.spec.ts.snap
common/features/config/networks/static/reducer.ts
common/libs/nodes/configs.ts
shared/types/network.d.ts

Closes #2166
homepage : https://atheios.com
block explorer : http://explorer.atheios.com | https://scan.atheios.com
network statistics : http://stats.atheios.com
slip0044 index : 1620
chainId : 1620
[Atheios is supported in Trezor ONE firmware version 1.6.3](https://blog.trezor.io/trezor-one-firmware-update-1-6-3-73894c0506d)
Atheios support has been merged to LedgerHQ's official repository:
https://github.com/LedgerHQ/ledger-app-eth/pull/31 (merged)
Atheios is on LedgerHQ's official roadmap:
https://trello.com/c/bZOQq2ho/121-atheios-support
cc: @atheioschain
cc: @atheios-berran

Add support for Atheios

---

common/features/ens/helpers.ts
common/features/transaction/sagas.spec.ts
common/features/transaction/sagas.ts
common/libs/ens/index.ts

Closes #1977 
As of now, the ENS resolution process doesn't work for subdomains (e.g. "wallet.mydomain.eth"). This PR aims to solve this issue.
Additionally, the changes allow new tlds to be added (e.g. [.xyz](https://medium.com/the-ethereum-name-service/announcing-support-for-xyz-on-ens-7f5bc7fe1b24)), since resolution is no longer forced under the `.eth` tld.
Don't split the input address into `{name}.{tld}` in `/transaction/sagas.ts` and leave it to `/ens/sagas.ts`. This change also removes the hardcoded `.eth` used for the resolution process.
Add an auxiliary function to extract the domain from the address to perform the auction status check with.
1. Go to `account/send`
2. Type `fantastique.eth` (or any other known domain) in the address input. It should resolve to an address.
3. …

Fix ENS subdomain resolution

---

common/config/dpaths.ts

Closes #2252
The BIP44 HD derivation path for Musicoin on MyCrypto and MyEtherWallet disagree with each other.
MyEtherWallet uses the correct registered BIP44 path: `"m/44'/184'/0'/0"`
MyCrypto is currently using Ethereum's BIP44 path: `"m/44'/60'/0'/0"`
Update Musicoin to use the correct registered BIP44 path, `"m/44'/184'/0'/0"`, based on:
https://github.com/satoshilabs/slips/blame/71332b0/slip-0044.md#L215

Update Musicoin to use the correct registered BIP44 path

---

common/features/config/networks/static/reducer.ts

Closes #2230
Just changes RSK testnet name to avoid confusions.
* Field `name` in `RSK_TESTNET` configuration
1. Expand Network & Node selection and validate that is listed `RSK` for mainnet and `RSK Testnet` for testnet.

Changes RSK testnet network name

---

common/components/WalletDecrypt/components/DeterministicWalletsModal.tsx

Closes #2242 
I often use the "select an address" dialog box to take a quick glance across multiple wallets.  I noticed that the "more" link brings us to ethplorer, which isn't helpful for most chains.
The "more" link in "Select an Address" modal always uses ethplorer, rather than the provided block explorer for the given chain
Instead, use the provided block explorer.
Fall back to ethplorer if `network.isCustom`

Link to the correct block explorer in "Select an Address" "more" link

---

common/features/config/networks/static/reducer.ts

It's a network configuration change.
RSK's ticker changed, the Smart BTC is known as RBTC.
Replace SBTC with RBTC

RSK ticker: renaming SBTC with RBTC

---

common/components/Header/NewHeader/components/DesktopHeader.scss
common/components/Header/NewHeader/components/MobileHeader.scss

A complaint was made that the navigation dropdown items were hard to select. This change expands their hitbox and changes the background color when hovered.

Make selecting navigation dropdown items easier

---

common/components/AddressField.tsx
common/components/AddressFieldFactory/AddressFieldFactory.tsx
common/components/AddressFieldFactory/AddressInputFactory.tsx
common/components/WalletDecrypt/components/ViewOnly.tsx
common/translations/lang/en.json

This PR enables the user to enter an ENS domain in the ViewAddress tab.

Allow usage of ENS domains on ViewWallet

---

common/components/BalanceSidebar/TokenBalances/AddCustomTokenForm/DecimalField.tsx
common/components/BalanceSidebar/TokenBalances/AddCustomTokenForm/SymbolField.tsx

This removes the read-only attribute from the symbol and decimal inputs in the token form. This allows the user to change these values after they have been fetched. This can be used when the user wants to add a token with a symbol that already exists (with a different address).
* Removed read-only attribute from symbol and decimal input for the custom tokens form.

Remove read-only attribute from symbol and decimal input

---

common/components/WalletDecrypt/components/ViewOnly.tsx

In ViewOnly, the `Enter an address...` input wasn't allowing non-ENS domains -- now it does!

Fix input field in ViewOnly

---

common/libs/nodes/configs.ts

Update Infura endpoints to V3 API
Updated infura node endpoints
1. Infura ETH network
2. Infura Ropsten network
3. Infura Rinkeby network

update infura enpoints to v3 api

---

common/components/Footer/NewFooter/components/Linkset.tsx

Adds newest products to footer.
* Added Desktop App and Mobile App to footer.

Added additional products to footer

---

README.md
static/.well-known/security.txt

Closes (no issue)
* Added `security.txt` which is a proposed standard (https://github.com/securitytxt/security-txt#internet-draft). It is to help make things easier for security researchers with disclosure.
* Added a small description on our branching model and naming conventions to help other contributors get started.
* Modification to `README.md`
* New file `./well-known/security.txt` in `static/`
* Navigate to `http://localhost:3000/.well-known/security.txt`

Added security.txt and branching model convention

---

shared/enclave/server/wallets/msg-config.ts
shared/enclave/server/wallets/trezor.ts

Closes #2439
Fixes Trezor Firmware bug that leads to `Safety Check Failed`
* Change method for initializing Trezor session with config.
1. Access account with trezor device on electron developer build `yarn run dev:electron`
2. Try to send transaction with Trezor account. Sign and submit transaction.

Fix for Trezor Firmware 1.8.0 bug.

---

common/features/config/networks/static/reducer.ts
common/libs/nodes/configs.ts

Some minor updates to the UBQ configurations. 
node url: pyrus2.ubiqscan.io is behind a proxy returning parity like responses, as a result balances are not shown correctly in mycrypto. rpc1.ubiqscan.io is without such proxy and fixes this.
explorer url: remove /en (deprecated), avoids a redirect.

UBQ: update node url, update explorer url

---

common/features/transaction/network/sagas.spec.ts
common/features/transaction/network/sagas.ts

Closes: #2426 
Closes: #2336
Fixes issue with nonce calculation when using the same public/private keypair across multiple networks. Fixed issue with nonce calculation when offline.
* Added a ChainID check to nonce lookup.
* `Throw`s instead of `return`s in try/catch to re-allow nonce cancellation when offline.
1. Send a transaction on mainnet using MetaMask.
2. Switch to Ropsten or Rinkeby and login using MetaMask (this will use the same keypair). 
3. Open the Advanced transaction settings section. This will display your nonce. Your nonce will be calculated to be the same as whatever the nonce for the new network is. It won't use the same nonce as the same account on the previous network.
4. Disconnect your computer from the internet. Click the Refresh button in the nonce field and it …

Fix chain nonce bug

---

common/libs/wallet/deterministic/ledger.ts
common/typescript/ledger/hw-app-eth.d.ts
package.json
shared/enclave/server/wallets/ledger.ts
yarn.lock

Ledger removed the hardcoded ERC-20 token info from the Ethereum app to reduce the size. This update implements the `provideERC20TokenInformation` function to replace this. More info on this change [here](https://github.com/LedgerHQ/ledgerjs/blob/master/docs/migrate_eth_app.md).
* Updated `@ledgerhq/hw-app-eth` to `4.48.0`
* Added TypeScript types for the new functions
* Implemented the `provideERC20TokenInformation` function
1. Update the Ethereum app to at least v1.2.2. This update is currently available in Ledger Live only when launching with `FORCE_PROVIDER=4`, but should be available without pretty soon.
2. Generate a token transaction in MyCrypto.
3. Check if the token symbol, amount and destination address are shown on the Ledger device.

Provide ERC-20 token information to Ledger wallets

---

common/v2/features/AddAccount/AddAccount.tsx
common/v2/features/Wallets/web3/web3.ts

* Changed back button in add-existing-account flow to reroute to beginning of flow by resetting local flow state.
* Fixed a quick issue not allowing pageload
1. Navigate to https://localhost/add-account
2. Go through flow for mnemonic option until you get to select address view.
3. Hit the back button. Should reroute you to https://localhost/add-account again at the wallet select view

Reroute back button to beginning of add-account flow

---

common/v2/features/AddAccount/AddAccount.tsx
common/v2/features/Wallets/web3/web3.ts
common/v2/libs/networks/index.ts
common/v2/libs/networks/networks.ts
common/v2/libs/networks/types.ts
common/v2/services/AssetOption/types.ts
common/v2/services/LocalCache/LocalCache.ts
common/v2/services/LocalCache/constants.ts

Edits the defaults for account object in add-account flow.
TODO: 
- - [x] Asset (should be set to base asset of each network)
- - [x] Label (get feedback on this, currently set to "New Account") *Leaving this alone for now - make a task for this in PM tool*
- - [x] LocalSettings (figure out some default value for this and set it)
- - [x] TransactionHistory (leave as empty string until filled in by user..?) *Leaving this alone*

Add-account flow default changes

---

common/v2/features/AddAccount/AddAccount.tsx
common/v2/features/DevTools/DevTools.tsx
common/v2/providers/AccountProvider/AccountProvider.tsx
common/v2/services/Account/types.ts
common/v2/services/LocalCache/constants.ts

Finishes up handling of data in Add Existing Account flow.
* Removed 'Confirm Address' View.
* Added derivation path to Account objects (added in type and initialization files).
* Redirect automatically to Dashboard (endpoint: `/dashboard`).

Remove 'Confirm Address' View

---

common/v2/features/AddAccount/AddAccount.tsx

Enables web3 support in `add-existing-account` flow.
Automatically uses the redirect on login.

enable web3 on add-existing-account flow

---

common/containers/Tabs/ENS/components/NameResolve/components/NameAuction.tsx
common/containers/Tabs/ENS/components/NameResolve/components/NameForbidden.tsx
common/containers/Tabs/ENS/components/NameResolve/components/NameNotYetAvailable.tsx
common/containers/Tabs/ENS/components/NameResolve/components/NameOpen.tsx
common/translations/lang/en.json

Reported by @jspence425 
Please review as soon as possible, ENS manager updates on May 4th and it would be great to release this hotfix today before users will start relying on it more.
https://mycryptobuilds.com/hotfix/incorrect-url-for-non-auctioned-ens-domains/#/ens
Visiting a non-auctioned ENS domain goes to a valid ENS manager URL ending in `.eth`.
Visiting a non-auctioned ENS domain goes to an invalid URL not ending with `.eth` which has JS errors that lead to a blank page.

Fix incorrect URL for non-auctioned ENS domains

---

common/v2/features/AddAccount/AddAccount.tsx
common/v2/features/Wallets/types.ts
common/v2/libs/networks/networks.ts
common/v2/libs/networks/types.ts
common/v2/services/LocalCache/LocalCache.ts
common/v2/services/LocalCache/constants.ts
common/v2/services/NetworkOptions/types.ts

https://mycryptobuilds.com/network-filter-unsupported-wallets
Only shows supported networks when the user selects a wallet type
* Added dPath shit to local cache initialization.
* Added filtering for networks where wallet type is supported. *This depends on the presence of a DPath option in the Network's Config List*.
1. Navigate to http://localhost/add-account. Access a ledger device.
2. Try to select the Webchain network. Note that it does not exist in the list.

Add WalletType filtering for networks tab

---

common/v2/features/AddAccount/AddAccount.tsx

Enables parity signer for the add-existing-account flow
* Change handling for parity signer wallet types.
1. Navigate to https://mycryptobuilds.com/enable-parity-signer
2. Select "Parity Signer" option.
3. Try to add parity-signer account

Enable parity signer for Add Account Flow

---

common/v2/features/AddAccount/components/DeterministicWallets.scss
common/v2/features/AddAccount/components/DeterministicWallets.tsx

This fixes the following issue from #2550:
> @blurpesec Radio buttons appear oval-ish in desktop views for me. Is this intentional?
> ![image](https://user-images.githubusercontent.com/29407814/57453488-8662d280-7234-11e9-9838-ed34d4dde080.png)

Fix radio button stretching

---

common/v2/services/LocalCache/LocalCache.ts
common/v2/services/LocalCache/constants.ts
common/v2/services/NetworkOptions/types.ts

Fixes a bug where tokens aren't correctly added to `networkOptions.asset` array.

Fixed tokens initialization in networkOptions

---

common/v2/features/Layout/Header/Header.tsx

A small style fix to ensure that hover menus aren't hidden behind notifications
......
Before
After

Menu hover fix

---

common/libs/wallet/deterministic/ledger.ts

Fixes an incompatibility issue regarding Windows and WebUSB. This can be reverted once this issue is fixed. The desktop app is not affected by this.
* Added a fall back to U2F for Windows
Try to unlock with a Ledger device on Windows

Temporarily fall back to U2F on Windows with Ledger devices

---

.prettierignore
package.json

This fixes the annoying constant reformatting of package.json by only letting Yarn format it, making our pull requests easier to read and merge when they include modifications to package.json

Disable Prettier formatting for package.json

---

common/translations/lang/en.json
common/v2/features/AddAccount/components/SaveAndRedirect.tsx
common/v2/features/Dashboard/NotificationsPanel/components/WalletNotAddedNotification.tsx
common/v2/features/Dashboard/NotificationsPanel/components/index.ts
common/v2/features/DevTools/DevTools.tsx
common/v2/libs/assetOptions.ts
common/v2/libs/assets/assets.ts
common/v2/libs/assets/index.ts
common/v2/libs/index.ts
common/v2/providers/NotificationsProvider/constants.ts
common/v2/services/Account/types.ts
common/v2/services/Asset/Asset.ts
common/v2/services/LocalCache/LocalCache.ts
common/v2/services/LocalCache/constants.ts

Initializes/Creates test accounts during initialization of local cache for use in development of other features.
Also handles account-not-added notification due to invalid network and duplicate address.
Adds new default asset on account addition.

Added Test Accounts during Initialization of LC

---

common/config/dpaths.ts
common/features/config/__snapshots__/sagas.spec.ts.snap
common/features/config/networks/static/reducer.ts
common/libs/nodes/configs.ts
shared/types/network.d.ts

EtherInc is a fork of Ethereum to power the future of blockchain based organizations.
* Homepage: https://einc.io/
* Node: https://api.einc.io/jsonrpc/mainnet
* Explorer: https://explorer.einc.io/
* BIP44 / Chainid 101 ( [satoshilabs/slips#438](https://github.com/satoshilabs/slips/pull/438) )
This PR adds EtherInc node support

Add EtherInc (ETI) Support

---

common/components/ParityQrSigner.scss

🎉 🎉 🎉
This adds a white border to make sure the QR code can be scanned correctly.
Self explanatory. 
1. Connect with Parity Signer
2. Make a transactions
3. Click on "Sign"

White border for Parity Signer QR codes

---

common/config/dpaths.ts
common/features/config/__snapshots__/sagas.spec.ts.snap
common/features/config/networks/static/reducer.ts
common/libs/nodes/configs.ts
shared/types/network.d.ts

Auxilium (AUX) is a cryptocurrency foundation of a philantropic company Auxilium Global. Its current main network started in summer of 2018, after performing swap from Sprouts blockchain and running a modified fork of Ethereum Go implementation.
- Blockchain explorer: https://explore.auxilium.global
- R-RPC node: https://rpc.auxilium.global
- Node: https://github.com/auxiliumglobal/go-ethereum
- ChainID: 28945486
- SLIP-44 number: 344 
More information about Auxilium Global can be found here: https://auxilium.global
Gracias!

Add Auxilium crypto support

---

common/v2/features/Settings/Import/components/ImportBox.tsx

Fix issue where an error was displaying by default on the import page before an import was attempted
Stops error from showing before import

Fix error rendering when importing invalid file type that is not a json file

---

webpack_config/makeConfig.js

We're going to alter the production build to use the dev-builds css loaders temporarily. 
This is to allow design team to review current state of `gau` without forcing us to figure out a solution to this bug yet since it's pretty low-priority until right before MVP release.
We're going to create a task that blocks GAU MVP release in order to fix this before MVP goes live.
This new task is here: https://app.clubhouse.io/mycrypto/story/2535/revert-https-github-com-mycryptohq-mycrypto-pull-2702-and-fix-dev-and-production-build-style-mismatch-bug
This pr closes this task: https://app.clubhouse.io/mycrypto/story/2531/create-way-for-avani-to-be-able-to-review-design-implementation

Force production build to use dev environment css loaders temporarily

---

webpack_config/makeConfig.js

https://app.clubhouse.io/mycrypto/story/2559/can-t-open-https-mycryptobuilds-com-gau-in-safari
test fix to see if will fix safari csp issues regarding workers since safari doesn't recognize the workers-src parameter
also related to #2708

csp fix for gau

---

common/v2/components/AssetIcon.tsx
webpack_config/makeConfig.js

~Todo: get feedback from @miagx about whether or not we can have the endpoint modified for `.svg`s instead of `.png`s~

Use self-hosted CDN for asset icons

---

common/v2/features/SendAssets/components/ConfirmTransaction.scss
common/v2/features/SendAssets/components/ConfirmTransaction.tsx
common/v2/features/SendAssets/stateFactory.tsx
common/v2/features/SendAssets/types.ts
common/v2/services/Store/AddressBook/AddressBookProvider.tsx

Changes:
- Use baseAsset to split out asset to send and baseAsset for the confirm panel.
- Removed implicit asset tickers.
Note: This PR isn't intended to clean up Confirm Panel styles, just to make sure logic is all there. :-)

Added additional information to Confirm Transaction Panel

---

package.json

Fix issue that prevents committing code due to `tscheck` only running for staged files.

Run tscheck on all files

---

common/v2/features/AddAccount/components/SaveAndRedirect.tsx
common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdown.tsx
common/v2/features/SendAssets/components/SendAssetsForm.tsx
common/v2/features/SendAssets/components/fields/AccountDropdown.tsx
common/v2/features/SendAssets/components/fields/AssetDropdown.tsx
common/v2/services/EthService/network/helpers.ts
common/v2/services/Store/Asset/helpers.ts
common/v2/services/Store/LocalCache/seedCache.ts

There were some problems with get-account-balance usability that I wanted to fix. These are those fixes. This should get us up to near-parity with current `gau` functionality.
Changes:
1) Fixed a bug with duplicate entries when adding existing accounts.
2) Fixed an issue with base asset population when adding existing accounts.
3) Fixed Asset Dropdown duplication bug in Send-Assets flow (there still exists a mismatch bug between test accounts and add-existing accounts, but its not blocking anything -> To select an Ethereum account, make sure to click the "Ethereum" asset, NOT the "Ether" asset in dropdown).
4) Fixed Account Dropdown bug in Send-Assets flow.
5) Fixed bug with network usage for ethers.js provider initialization.
6) Fixed a bug with send-max button.

Fixes for get-account-balance usability

---

common/v2/components/AccountList.tsx
common/v2/config/cacheData.ts
common/v2/services/Store/LocalCache/seedCache.ts
common/v2/services/Store/StoreProvider.tsx

🎉 🎉 🎉
Displayed fiat value in AccountList used on the Dashboard and Settings page
- Added `totalFiat` method to `StoreProvider`
- Displayed fiat value in AccountList using `totalFiat`
View either the Dashboard or Settings page 😄

Display fiat value in AccountList

---

common/v2/components/AccountList.tsx
common/v2/components/Currency.tsx
common/v2/config/cacheData.ts

🎉 🎉 🎉
Added support for prefixing currency symbols.
I.e. USD should be prefixed to the value as "$10" instead of "10$".
* Added prefix prop to Currency component
* Added prefix field to Fiat interface
* Used prefix prop in AccountList
View dashboard and see that $ is used correctly as prefix instead of postfix.

Added support for prefixing currency symbols

---

common/v2/services/Store/StoreProvider.tsx

Fix StoreProvider Bugs

---

common/v2/services/EthService/network/ethersJsProvider.ts

🎉 🎉 🎉
Added support for storing multiple EthersJS singletons fixing issues where testnet balances would be calculated on the wrong network.
* Added object for storing multiple EthersJS singletons
View the dashboard and see that Ropsten, Rinkeby etc. accounts have valid balances.

Added support for storing multiple EthersJS singletons

---

webpack_config/makeConfig.js

🎉 🎉 🎉
`npm_package_gitHead` is not defined when using `yarn`, resulting in undefined file hashes on the production build. This PR replaces it with the Webpack build hash.
* Replaced `npm_package_gitHead` with Webpack's hash.
1. `yarn build`
2. Check if filenames in `dist/prod` include file hashes.

Fix undefined file hash

---

common/v2/services/Store/BalanceService.tsx

Return previous account on balance lookup error instead of undefined.

Fix bug with storeprovider timeout by just returning unaltered account

---

common/v2/components/AccountList.tsx
common/v2/features/Dashboard/components/WalletBreakdown/AccountDropdown.tsx
common/v2/services/Store/StoreProvider.tsx

Gets rid of the "Showing 15 out of 14 accounts" bug with account dropdown on dashboard. Also truncates addresses and adds labels.
- Filter dashboardAccounts from settings when there is no account the uuid is assigned to.
- Truncates addresses in account dropdown.
- Adds labels to account dropdown.

Added filter for removed accounts in dashboard accounts list

---

common/v2/components/Dropdown.tsx
common/v2/components/NetworkSelectDropdown.tsx
common/v2/components/WalletUnlock/Web3Provider.tsx
common/v2/features/AddAccount/components/NetworkSelectPanel.tsx
common/v2/features/AddAccount/stories.tsx
common/v2/services/WalletService/web3/web3.ts

🎉 🎉 🎉
Fixed a few issues in relation to `NetworkSelectDropdown` and `NetworkSelectPanel`.
See Clubhouse card or changes below!
- Used `Dropdown` component for `NetworkSelectDropdown`, allows for searching etc.
- Disabled next button when an invalid network is selected
- Automatic network selection when using MetaMask
1. Go to add account
2. Add any account other than metamask
3. See that you can search and choose networks
1. Go to add account
2. Add any account other than metamask
3. See that you can't continue with an invalid network
1. Go to add account
2. Add metamask account
3. See that the correct network is automatically chosen and the account is added

Fixed network selection issues

---

common/v2/components/AssetIcon.tsx
common/v2/features/Dashboard/components/WalletBreakdown/BalancesDetailView.tsx
common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdownView.tsx

🎉 🎉 🎉
Added asset icons to both WalletBreakdown UI modes
* Added `AssetIcon` to `WalletBreakdownView` and `BalancesDetailView`
* Added `className` to `AssetIcon` for styling
- View dashboard and see that icons have been added to WalletBreakdown. 
- Also click "view details" to see icons on the detailed breakdown.

Added asset icons to WalletBreakdown

---

common/v2/components/WalletUnlock/ViewOnly.tsx

Previously, the app couldn't pass through the add-account flow and would through an 'm.init is not a constructor error` instead. This is now fixed.

Fix a bug with view-only accounts in add-account flow

---

common/v2/components/AccountSummary.tsx
common/v2/features/SendAssets/components/fields/AccountDropdown.tsx

- Filters view only accounts from Send Assets account dropdown.
- Remove copyable button from accounts in Send Assets account dropdown.

Remove copyable from send assets account dropdown and filter viewonly accounts

---

common/v2/features/SendAssets/components/SignTransactionWallets/Web3.tsx

Previously, a request to switch network would show network id instead of network name. This has been altered.

Fix bug with networkid not being name

---

common/v2/services/RatesProvider.tsx

Rate polling worker should be updated when a user scans for new assets.
To test:
1) Add an account.
2) Scan for tokens. Rates should be updated immediately.

Update rate polling worker on asset updates

---

common/translations/lang/en.json
common/v2/components/AddressField.tsx
common/v2/components/WalletUnlock/DeterministicWallets.tsx
common/v2/components/WalletUnlock/ViewOnly.tsx
common/v2/components/index.ts
common/v2/services/Store/AddressBook/helpers.ts
common/v2/services/Store/AddressBook/index.ts
common/v2/services/Store/BalanceService.tsx
common/v2/services/WalletService/deterministic/deterministic.ts
common/v2/services/WalletService/deterministic/index.ts

The goal of this PR is to extract out the redux and shepherd stuff being used in the Add-Account flow.
This is needed so that we can for prep for migrating `gau` to `master` and strip out legacy sections of the codebase.

Strip Redux/Shepherd out of HD wallet types in Add Account

---

common/v2/components/Currency.tsx

Description
Fixed currency formatting issue where `1.50` would read as `1.5`

Fixed currency formatting

---

common/v2/services/ApiService/Analytics/Analytics.spec.ts
jest_config/jest.config.json
package.json
yarn.lock

[[ch3434]](https://app.clubhouse.io/mycrypto/story/3434/webpack-improve-dev-server)
From time to time `Analytics.spec.ts` would timeout.
To avoid it we use `nock` to mock the api call and return a response.

Mock http call for analytics spec

---

common/v2/components/AccountList.tsx
common/v2/components/CollapsibleTable.tsx
common/v2/components/RowDeleteOverlay.tsx
common/v2/components/Table.tsx
common/v2/components/index.ts
common/v2/features/Settings/Settings.tsx
common/v2/features/Settings/components/AddressBook.tsx

* Added a table row overlay for account deletion confirmation step
~Will prob need to be cleaned up a bit later~
[ch2593]

Add account deletion confirmation to table on desktop

---

common/config/tokens/eth.json

Note: not on prod, but in 1.7.4 release candidate.
One of those lovely contracts that mess up our interface by returning insane values :eyes: 
From the [contract](https://etherscan.io/address/0x5a276Aeb77bCfDAc8Ac6f31BBC7416AE1A85eEF2#code):
```
function balanceOf(address _owner) public view returns (uint256 balance) {
return MAX_UINT256;
}
```

Remove LOVE token

---

common/Root.tsx
common/v2/features/DevTools/DevTools.tsx

https://app.clubhouse.io/mycrypto/story/3557/devmode-modal

DevMode modal [ch3557]

---

common/v2/components/AccountList.tsx
common/v2/components/TransactionFlow/ConfirmTransaction.tsx
common/v2/components/TransactionFlow/TransactionReceipt.tsx
common/v2/components/TransactionFlow/displays/TransactionFeeDisplay.tsx
common/v2/features/Dashboard/components/TokenPanel/TokenPanel.tsx
common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdown.tsx
common/v2/features/SendAssets/components/SendAssetsForm.tsx
common/v2/services/ApiService/AssetMap/AssetMap.ts
common/v2/services/ApiService/AssetMap/index.ts
common/v2/services/ApiService/TokenInfo/TokenInfo.ts
common/v2/services/ApiService/index.ts
common/v2/services/RatesProvider.tsx
common/v2/services/Store/BalanceService.tsx
common/v2/services/Store/Cache/seedCache.ts
common/v2/services/Store/StoreProvider.tsx
common/v2/types/asset.tsx
common/v2/types/rates.ts
common/v2/utils/generateUUID.tsx
common/v2/utils/index.ts
package.json
yarn.lock

[ch3535] [ch3536]
Migrate from cryptocompare to coingecko. Use asset mapping from mycryptohq/assets
Fixes handling token detail fetches for large amounts of assets.
Fixes a bug that results in token detail fetches occurring 8x times for every one time it needs to be run.
~If you want to test before this csp /cors issue is fixed, find and replace `https://price.mycryptoapi.com` with `https://raw.githubusercontent.com/MyCryptoHQ/assets/master/assets/assets.json`~

Migrate to coingecko from cryptocompare

---

babel.config.js

Added 'commonjs' to the babel.config.js to fix the false positive warnings

Fix 'export not found' warnings

---

electron-app/preload/index.ts

Triggering preload after Electron has loaded its internal initialization script, removes the 'Unable to load preload' error
[ch4277]

Load preload.js after Electron intialization

---

electron-app/main/window.ts

Disable nodeIntegration and enable contextIsolation for security reasons
https://electronjs.org/docs/tutorial/security#isolation-for-untrusted-content

Disable nodeIntegration and enable contextIsolation

---

common/v2/features/InteractWithContracts/components/GeneratedInteractionForm.tsx
common/v2/features/InteractWithContracts/helpers.ts

The deprecated `payable` and `constant` fields were removed from the ABI JSON output of Solidity with 0.6.0. The functionality is replaced with the `stateMutability` field. In this PR we added support for the `stateMutability `field when interacting with contracts
[ch4282]

Use stateMutability payable param if exists

---

package.json
yarn.lock

MyCrypto is now using:
MyCryptoHQ/uuid-by-string
|_MyCryptoHQ/js-md5
|_MyCryptoHQ/js-sha1
Removing the eval() causing a blank screen on electron

Replace UUID library to fix Electron blank screen

---

webpack_config/electron.production.js

Previous target value `electron-renderer` instructs webpack to use NodeTargetPlugin which should be only used if budle is running in Node.js environment.
Since we have `nodeIntegration` disabled, the bundle target should be set to `web`.

Change webpack target for Electron production build

---

common/v2/components/SignTransactionWallets/Mnemonic.tsx
common/v2/services/WalletService/deterministic/mnemonic.ts

- add missing properties to be returned from MnemonicWallet
- read dPath from sender account instead from state

Return missing properties from MnemonicWallet

---

package.json
yarn.lock

Bump lodash from 4.17.13 to 4.17.15

---

common/v2/database/data/nodes.ts

Move ETC RPC endpoint to the more advanced Ethercluster
Ethercluster is a Hyperledger Labs project built by the ETC Cooperative for scalable node architecture. It's more robust than the outdated https://ethereumclassic.network endpoint.
This fixes issue with users getting wrong balances since they're tied to an old node.

feat: Update ETC endpoint to Ethercluster

---

common/v2/features/Dashboard/components/TokenPanel/TokenList.tsx
common/v2/services/Store/Asset/__tests__/helpers.spec.ts
common/v2/services/Store/Asset/helpers.ts

[ch4173](https://app.clubhouse.io/mycrypto/story/4173/tusd-balance-is-wrong)
Now that we have uuid for tokens we should use them when we sum the users asset balances. 
ref: https://mycryptohq.slack.com/archives/G8G1S4TG9/p1579654425069200
- use `uuid` when summing asset balances
- add tests
- use `uuid` as `key` when displaying token list

Use uuid as uniq prop when summing asset balances

---

common/v2/config/dpaths.ts
common/v2/database/data/networks.ts
common/v2/database/data/nodes.ts
common/v2/types/networkId.ts
shared/types/network.d.ts

Support **EtherCore Mainnet**, Proof of Work Ethereum compatible network.
Homepage: https://ethercore.org
Block Explorer: https://explorer.ethercore.org
RPC Endpoint: https://rpc.ethercore.org
ChainId / SLIP-44: **466** https://github.com/satoshilabs/slips/pull/847
Official Email: info@ethercore.org

Add EtherCore support

---

common/v2/features/SwapAssets/stateFactory.tsx
common/v2/translations/lang/en.json

🎉 🎉 🎉
Added some input sanity validation to reduce the will-be-error responses from dexag and added logic to show a more logical error message.
* If the user clears one of the inputs, clear all swap inputs and don't send a request to dexag that will result in a 400 bad request
* If the user inputs a send/receive input of `0`, show a better error message and don't send a request to dexag that will result in a 400 bad request
* If the user inputs a send/receive input of `-n`, show a better error message and don't send a request to dexag that will result in a 400 bad request
We are now doing sanity checks to make sure we _should_ send a request to DEXAG without it intentionally resulting in a 400 bad request.
* Sanity checks on input with the swap input event handlers

Swap input sanity checks

---

common/v2/components/GeneralStepper/GeneralStepper.tsx
common/v2/components/GeneralStepper/__tests__/GeneralStepper.test.tsx
common/v2/components/GeneralStepper/index.ts
common/v2/components/GeneralStepper/types.ts
common/v2/components/index.ts
common/v2/features/SendAssets/SendAssets.tsx
common/v2/features/SendAssets/__tests__/SendAssets.test.tsx
common/v2/features/SendAssets/stateFactory.tsx

This pr introduces a Generalized Stepper that is implemented into the Send-Assets flow. It also adds a number of tests to make sure that it works correctly :open_mouth:. This will be used in DeFiZap implementation. Eventually other flows should have it incorporated. in order to reduce QA time, it's only been introduced into one flow so far (Send Assets).
1) Add an account (metamask or another normal (non-Frame) wallet type) on https://mycryptobuilds.com/pr/2996/
2) Attempt to send a transaction using this account in the normal Send Assets flow (https://mycryptobuilds.com/pr/2996/#/send).
3) Does it work? Does it stall on one of the steps from send flow?

Generalized Stepper Implementation

---

common/v2/components/TransactionFlow/displays/TransactionDetailsDisplay.tsx
common/v2/features/SendAssets/SendAssets.tsx
common/v2/features/SendAssets/helpers.ts
common/v2/features/SendAssets/stateFactory.tsx

Ran into an issue of there being no signed tx field in the ConfirmTransaction panel for hardware wallets.
1) Navigate to https://mycryptobuilds.com/pr/3030/ and add a hardware wallet address.
2) Attempt to send a transaction.
3) After signing the transaction, on the confirm transaction step, click the "more details" section and see if a signed transaction field appears. does it?

Enabled signed tx in confirm panel

---

static/.well-known/security.txt

🎉 🎉 🎉
Add line to `security.txt` to claim domain ownership on OpenBugBounty
* Single line change

Add OBB copy to claim domain

---

static/.well-known/security.txt

🎉 🎉 🎉
Add line to `security.txt` to claim domain ownership on OpenBugBounty
* Single line change

Add OBB copy to claim beta domain

---

common/v2/components/SignTransactionWallets/index.ts
common/v2/features/DeployContracts/DeployContractsFlow.tsx
common/v2/features/DeployContracts/helpers.ts
common/v2/features/InteractWithContracts/InteractWithContractsFlow.tsx
common/v2/features/InteractWithContracts/helpers.ts
common/v2/features/SendAssets/components/SignTransaction.tsx
common/v2/features/SwapAssets/SwapAssetsFlow.tsx
common/v2/features/SwapAssets/components/SetAllowance.tsx
common/v2/features/SwapAssets/helpers.ts

Each sign step would map the walletId to the SignComponent.
This PR makes a single declaration in `SignTransactionWallets`

Dedupe declaration of wallet signing components

---

common/v2/components/AddressField.tsx
common/v2/components/DomainStatus.tsx
common/v2/features/SendAssets/components/SendAssetsForm.tsx
common/v2/services/EthService/ens/__tests__/validators.spec.ts
common/v2/services/EthService/ens/validators.ts

[CH4517]
🎉 🎉 🎉
* Fixed bug that caused the user to be able to sign a transaction to a non-intended address if the ENS name was invalid (description in comment on ch4517)
* Adjusted logic to allow for more ENS TLDs so we can send to `*.argent.xyz` addresses
* Adjusted logic to check if a value is valid ENS name
* Remove `0x` startswith condition because you can have a name like `0xharry.eth`
* Remove strlen condition because short names released and we should be relying on onchain data. Too tight of a restriction for read-only interaction.
* Added new TLD to the TLD dictionary
* Modified sanity checks

Better ENS Validation

---

common/v2/features/SwapAssets/components/fields/SwapFromToDiagram.tsx

On the confirm swap panel the console would display an error from `validateDOMNesting() ... div cannot be a descendant of p` .
This PR changes the HTML markup to remove the unnecessary nesting.
Display is identical

Remove unecessary p container

---

.storybook/config.js
.storybook/main.js
.storybook/preview-body.html
common/v2/components/AccountDropdown.tsx
common/v2/components/Banner.stories.tsx
common/v2/components/SignTransactionWallets/__tests__/WalletConnect.test.tsx
common/v2/components/TransactionFlow/ConfirmTransaction.stories.tsx
common/v2/components/TransactionFlow/ConfirmTransaction.tsx
common/v2/components/TransactionFlow/displays/TransactionDetailsDisplay.tsx
common/v2/components/__tests__/AssetDropdown.test.tsx
common/v2/components/__tests__/ContactLookupField.test.tsx
common/v2/features/BroadcastTransaction/stateFactory.tsx
common/v2/features/SendAssets/components/SendAssetsForm.tsx
common/v2/features/SendAssets/stateFactory.tsx
common/v2/services/Store/StoreProvider.tsx
common/v2/services/Store/helpers.tsx
common/v2/services/Store/index.tsx
common/v2/services/Store/utils.ts
common/v2/types/account.tsx
common/v2/types/transactionFlow.ts
common/v2/utils/transaction.ts
common/vendor/safe-t-connect.js
jest_config/__fixtures__/index.ts
jest_config/__fixtures__/txConfig.json
package.json
tsconfig.json
webpack_config/common.js
webpack_config/config.js

1. Configure Storybook (SB) to use project css and assets.
2. Center display of story
3. Set default port to ':3001'
4. Update ConfirmTransaction component to enable use in Storybook
5. Updated StoreAccount to get existing account 'label'. (This commit was included because it removes unnecessary dependencies on `AddressBook` and creates more standard typing. It remains optional)
1. Pull PR and run `yarn && yarn storybook`.
2. Open browser at `localhost:3001`
3. Click on 'ConfirmTransaction'
4. Use the mycryptobuilds.com link and create a transaction (it should have no regressions).

ConfirmTransaction stories demo

---

common/v2/components/TransactionFlow/ConfirmTransaction.stories.tsx
common/v2/components/TransactionFlow/ConfirmTransaction.tsx
common/v2/components/TransactionFlow/TxReceipt.stories.tsx
common/v2/components/TransactionFlow/TxReceipt.tsx
common/v2/components/TransactionFlow/displays/TransactionDetailsDisplay.tsx
common/v2/components/TransactionFlow/helpers.ts
common/v2/components/TransactionFlow/types.ts
common/v2/services/Store/AddressBook/AddressBookProvider.tsx
common/v2/services/Store/utils.ts
common/v2/utils/transaction.ts

Fix for a bug when sending from an account that does not exist in our store crash Confirm step.
Link to thread: https://mycryptohq.slack.com/archives/G8G1S4TG9/p1583283623101100

Fallback to default account if none found in store

---

common/v2/features/ErrorHandling/ErrorProvider.tsx

The error boundary routes to `/home` in case of uncaught error.
We have a toggle in devTools to remove the behaviour, but we don't (and most probably shouldn't) cache the devs preference.
To avoid the extra clicks, we set default behaviour to 'suppress' when we are IS_DEV.

Remove error boundary when in dev env

---

common/components/ElectronBuildVerified/Banner.scss
common/components/ElectronBuildVerified/index.tsx
common/containers/TabSection/ElectronTemplate.tsx

[CH5455]
🎉 🎉 🎉
* Adds a banner to the Electron view to prompt users to verify the builds
* Fetches the version number from `config/data.tsx` (which is from the `packageJson.version`) and compares that string with the one in LocalStorage from when they last accepted
* Added new component `ElectronBuildVerified`

(Legacy) Added Banner for user to acknowledge verifying builds

---

common/v2/components/Account.tsx
common/v2/components/AccountList.tsx
common/v2/components/ContactLookupDropdown.tsx
common/v2/components/Dropdown.tsx
common/v2/components/RowDeleteOverlay.tsx
common/v2/features/Dashboard/Dashboard.tsx
common/v2/features/Settings/Settings.tsx

Fixes for: 
- Settings: Delete account clipping [ch5536]
- Global: searchable dropdown component dowshifts text [ch5538]
- Mobile Send: Trying to paste address into recipient field can erase the address [ch5529]

Fixes for dropdown component and delete account clipping

---

common/v2/services/ApiService/Dex/Dex.ts

Exclude 0x pool from Swap per https://mycryptohq.slack.com/archives/G8G1S4TG9/p1582830405054300
[This is submitted now while looking into our Dex implementation]
- Create a Swap
- Check network tab and see that radar-relay is discluded.

Exlcude 0x aka radar-relay from Dex.ag lookups

---

.github/PULL_REQUEST_TEMPLATE.md

Update Github readme to state that any strings [ch5589]

Add translatable strings requirement to PR template

---

package.json

We were rebuilding electron dependencies on every yarn add/remove.
This runs the `electron-builder install-app-deps` only when we actually need it.

Stop building electron-deps on postInstall

---

common/components/ui/Warning.tsx
common/config/navigation.ts
common/v2/features/BuyAndExchange/BuyAndExchange.tsx
common/v2/features/BuyAndExchange/ShapeShift/ShapeShiftDisabled.tsx
common/v2/features/BuyAndExchange/ShapeShift/index.ts
common/v2/features/BuyAndExchange/routes.ts

[CH5205]
🎉 🎉 🎉
* Removal of Shapeshift to the web and desktop app for legacy.
* Removed navigation item
* Displayed a warning page if they manually route to the shapeshift integration

Disable ShapeShift integration and show a warning to the user

---

common/v2/features/SendAssets/components/SendAssetsForm.tsx
common/v2/services/UnstoppableService/index.ts
package.json
yarn.lock

Fixes: #3160 
We added a change to set default asset as ETH, but doesn't set default network too (which is conducted on asset selection). We should check to make sure this doesn't break `gasPrice` lookup as well.

Fix default asset ens bug in send flow

---

common/Root.tsx
common/v2/utils/scrollToTop.tsx

**Links when clicked now reset page scroll to top**
- Removed `overflow` css rule on Router container (_This is what resolved the bug_)
- Updated scrollToTop method for the newest recommended one on [React Training](https://reacttraining.com/react-router/web/guides/scroll-restoration)
- Made the DevTool `fixed` so we can still use it
Just scroll and change page via a button or navigation.
Verify that the new integration of DevTool is okay for you since we couldn’t keep it as it was before due to the necessity of adding the `overflow` rule to the container to keep the "shape" of the app.
[Story details](https://app.clubhouse.io/mycrypto/story/5782)

Reset scroll on page change

---

common/v2/features/Layout/Header/Header.tsx
common/v2/features/Layout/Header/constants.ts
common/v2/routing/index.ts

Following AllHands include settings icon in header

Add settings icon to nav link

---

common/v2/features/Layout/Header/constants.ts

Include link to `/add-account` in header for easy access.

Include link to add account in header

---

common/v2/database/data/networks.ts

Uses a faster explorer hosted by aqua.signal2noi.se pool

AQUA: update explorer URL

---

common/v2/services/EthService/network/helpers.ts

Fixed an obscure bug where disabling the MetaMask extension would cause massive amounts of requests to our API, re-renders of the site etc.
When polling for balances we only update the balance state in case there is changes. Due to the bug with node configuration, the request would always fail, and therefore there would always be a difference between the current balance and the new balance. This would trigger an infinite loop of requests to ethscan.

Fixed slowdown when disabling MetaMask

---

common/v2/features/Dashboard/components/TokenPanel/TokenList.tsx

Sort the token list in the token scanner panel before display
Add some accounts to dashboard, scan for tokens and make sure the token names are alphabetized.

Sort token scanner list before display

---

common/AppRoutes.tsx
common/v2/features/Settings/Settings.tsx

Make settings page title style correspond to 'Your Dashboard'
reference: https://www.figma.com/file/BY0SWc75teEUZzws8JdgLMpy/MyCrypto-GAU-Master?node-id=1522%3A84934

Harmonize settings title

---

common/v2/components/AccountList.tsx
common/v2/components/DashboardPanel.tsx

Following all hands design conversation:
Remove link text from table header.

Remove link text from Dashboard AccountList

---

common/v2/components/NetworkSelectDropdown.tsx
common/v2/components/WalletUnlock/LedgerNano.tsx
common/v2/components/WalletUnlock/Mnemonic.tsx
common/v2/components/WalletUnlock/ParitySigner.tsx
common/v2/components/WalletUnlock/SafeT.tsx
common/v2/components/WalletUnlock/Trezor.tsx
common/v2/components/WalletUnlock/ViewOnly.tsx
common/v2/database/v1.0.0/generateDefaultValues.spec.ts
common/v2/database/v1.0.0/generateDefaultValues.ts
common/v2/features/BroadcastTransaction/stateFactory.tsx
common/v2/features/CreateWallet/Keystore/Keystore.tsx
common/v2/features/CreateWallet/Mnemonic/Mnemonic.tsx
common/v2/features/CreateWallet/components/SelectNetworkPanel.tsx
common/v2/features/Dashboard/components/TokenPanel/AddToken.tsx
common/v2/features/DevTools/DevTools.tsx
common/v2/features/Settings/Settings.tsx
common/v2/features/Settings/components/AddOrEditNetworkNode.tsx
common/v2/features/Settings/components/AddToAddressBook.tsx
common/v2/services/Store/Network/NetworkProvider.tsx
common/v2/services/Store/Network/utils.ts

Swap `getNetworkByName` with `getNetworkById`, show network name in network dropdown instead of network id.
[ch5769]

Fix network dropdown usage

---

common/v2/features/NotificationsPanel/components/OnboardingPleaseUnderstandNotification.tsx

Quick fix for Icons ration on "Onboarding please understand" notification.

Fix "Onboarding please understand" notification icons ratio

---

common/v2/config/index.ts
common/v2/features/AddAccount/AddAccountFlow.tsx
common/v2/services/Store/Account/AccountProvider.tsx
common/v2/services/Store/StoreProvider.tsx
common/v2/types/index.ts
package.json
yarn.lock

[ch5875]
After adding an account, scan tokens only on the account being added. Change `scanTokens()` to use `model.updateAll` in provider instead of `model.update` to reduce overall "glitchiness".
1) Add accounts back to back with network tab open. After each add, you should only see a couple of new network requests instead of hundreds ;)
2) With 10+ accounts on your dashboard, click the `Scan Tokens` button with network tab open. This should result in 100-200 new network calls as opposed to the previous ~500-700 that were being conducted.

Scan tokens ux improvements

---

common/index.html
common/v2/features/BuyAndExchange/ZeroEx/ZeroEx.tsx
common/v2/features/BuyAndExchange/ZeroEx/ZeroExDisabled.tsx
webpack_config/makeConfig.js

[CH5754]
🎉 🎉 🎉
* Point users to our Beta product for swap (this affects the web build, electron build already has this nav bar item removed)
* Remove ZeroEx and point to our beta product. 
* Remove also 0x from CSP and loading foreign JS into the app
1. Build web `yarn start`
2. Navigate to swap nav item
3. Click on 0x widget

Legacy: Remove ZeroEx

---

common/v2/components/AmountInput.tsx
common/v2/components/GasSelector.tsx
common/v2/components/InputField.tsx
common/v2/features/Home/components/TestimonialsPanel.tsx
common/v2/features/ReceiveAssets/ReceiveAssets.tsx
common/v2/utils/index.ts
common/v2/utils/sanitizeDecimalSeparator.ts

Using `inputMode="decimal"` forces numeric keyboard with an only country-specific decimal separator on iOS devices. For countries with comma as a decimal separator, this makes it impossible to enter a valid amount since only decimal dot is allowed. This PR fixes this behavior by changing the decimal comma to decimal dot on input change.
[ch5719]

Sanitize decimal separator

---

common/v2/services/ApiService/Analytics/constants.ts
common/v2/services/Store/Account/AccountProvider.tsx
common/v2/types/transactionFlow.ts

This allows us to record _only_ the type of tx (Standard, DefiZap, Swap, Contract Interaction, Contract Deploy, Membership Purchase, or Unknown if missing on the flow) being saved to account object so that we can know what features people are using MyCrypto for.

Added txType to analytics when account is added to LS

---

common/v2/config/links.ts
common/v2/features/Layout/Footer/components/Linkset.tsx

[CH5884]
* Removed EtherCards and added UnstoppableDomains and Quiknode ref links
* Added links for affiliate programs
* Remove ether.cards affiliate link

Footer affiliate links

---

common/v2/components/AssetIcon.tsx

Changes the width of AssetIcon to be the same as the height, to make the images square.
Old:
New:

Resize AssetIcon

---

src/services/Store/BalanceService.tsx

When I wanted to add funds to a Zap the app crashed because on account update we filtered out base asset if its balance was zero. (I had erc20 tokens but no ETH)
Fixed that by not filtering base asset which is essential on some flows.

Remove base asset filtering on accounts update

---

common/api/emails.ts

This adds a tag when a user signs up using the form in the footer.

Add tag on subscription

---

src/services/Store/utils.ts

Stops assuming that baseAsset is always present in an account. If it's not present, return balance of 0.

Stop assuming base asset is present

---

.github/workflows/ci.yml
package.json
yarn.lock

Following static test videos use npm-run-all to run linting and tsc in parallel.
28s for `yarn lint:css && yarn lint:ts && yarn tscheck` vs 18.14s for `npm-run-all lint:css lint:ts tscheck`

Run validation scripts in parallel

---

src/components/NewAppReleaseModal.tsx
src/config/constants.ts
src/config/data.tsx
src/config/helpArticles.ts
src/features/BuyAssets/BuyAssetsForm.tsx
src/features/Dashboard/components/ActionTile.tsx
src/features/Dashboard/components/WalletBreakdown/NoAssets.tsx
src/features/Dashboard/types.ts
src/features/DownloadApp/DownloadApp.tsx
src/features/DownloadApp/types.ts
src/features/Home/components/DownloadAppPanel.tsx
src/features/Home/components/PeaceOfMindPanel.tsx
src/features/Layout/Header/Header.tsx
src/services/ApiService/Github/types.ts
src/utils/__tests__/openLink.spec.ts
src/utils/index.ts
src/utils/isUrl.ts
src/utils/openLink.ts

[ch6211]
- create and tests `openLink` utility to make sure `window.open` is always called with `noreferrer`.
- replace all `window.open` calls to use the utility
- update `isUrl` to also be a Typeguard.

Ensure window.open is always called with noreferrer

---

.github/workflows/ci.yml
.github/workflows/mycryptobuilds.yml

Uploads the standalone `yarn build:downloadable` to artifacts so that people can download them. The previous standalone build was a zipped up mac electron build for some reason. This one uses `yarn build:downloadable`

Update CI to zip & save standalone

---

src/config/constants.ts
src/services/RatesProvider.tsx
src/services/Store/BalanceService.tsx

Changes handling for acc balance lookups so that it better handles errors :3.
Basically, it'll catch failed batch calls from ethscan and just feed back and empty object so that it doesn't fail out of the entire token scan from 1 failed lookup.
Also introduced the batch-size variable to limit size of lookups. This should decrease timeouts & errors but the tradeoff is it increases # of lookups.
Going to see what I can do to tweak load on our infra a little bit

Slightly change handling for acc balance lookups

---

node-scripts/translations/translations-extract.ts
src/components/WalletUnlock/DeterministicAccountList.tsx
src/components/WalletUnlock/Ledger.tsx
src/services/WalletService/deterministic/DeterministicWalletService.tsx
src/services/WalletService/deterministic/__snapshots__/helpers.test.ts.snap
src/services/WalletService/deterministic/helpers.test.ts
src/services/WalletService/deterministic/helpers.ts
src/services/WalletService/deterministic/reducer.ts
src/services/WalletService/deterministic/types.ts
src/services/WalletService/deterministic/useDeterministicWallet.ts
src/translations/lang/en.json

[ch5950]
Allows a user to generate fresh addresses using their ledger device (logic can be used across all HD wallet account types).
_Note: For now, it's limited up to an amount of `DEFAULT_GAP_TO_SCAN` which is currently set to 5. There are 2 reasons for this:_
_1) It allows us to not have to check new dpaths to generate the address and fetch it's balance (since the address/balance will already be in the useDeterministicWallet state)._
_2) It allows us to somewhat cap the number of empty addresses users add to their dashboard (which should help to cap infrastructure overhead)._

DPath Scanner: Generate Fresh Address

---

.github/stale.yml

This PR sets up probot-stale, to automatically close issues and PRs that haven't received any activity. It's configured with mostly the default settings, these can be changed if needed. There's a full list of settings here: https://github.com/probot/stale#usage

Setup stale bot

---

.github/workflows/ci.yml

To see if it works without since it seems to be unstable and causing issues

Disable dependency caching on Windows CI build

---

jest_config/jest.config.json
jest_config/test-utils.ts

Following [course video](https://mycrypto.atlassian.net/wiki/spaces/TS/pages/553910303/Configure+Jest+for+Testing+JavaScript+Applications#Support-a-Test-Utilities-File-with-Jest-moduleDirectories-10%3A57) use `jest.config.json` file to inject `extend-expect`

Use declarative injection of jest-dom/extend-expect

---

jest_config/jest.config.json

In an attempt to reduce memory usage:
- Use modulePathIgnorePatterns to remove jest warning:
jest-haste-map: Haste module naming collision: MyCrypto
The following files share their name; please adjust your hasteImpl:
* <rootDir>/package.json
* <rootDir>/dist/electron-js/package.json
- Use regex pattern for testPath and coveragePath ignore
1. Run `yarn build:electron:osx`
2. `/dist` folder will contain `__mocks__` and `src` dirs.
3. Run `yarn test` and you will see the jest warning displayed.
misc: If you `rm -rf dist` while the test jest will cry.
4. Repeat on branch and the warning should be gone.

Make jest ignore dist directory

---

.drawbridgerc
package.json

1. We changed the output dir to `dist/web`.
Replace the previous references to `dist/prod`.
2. Prefer `yarn` over `npm` to run commands.

Update dist pathname to dist/web

---

.github/workflows/mycryptobuilds.yml

GHA runs are failing on mater: https://github.com/MyCryptoHQ/MyCrypto/runs/928976417?check_suite_focus=true
S3 staging urls have changed.
Update the github actions to set the correct value for E2E_BASE_URL
eg. `<staging_url>/master/#`

Update E2E_BASE_URL to reflect s3 changes

---

src/features/DevTools/DevTools.tsx

Devtool main div was taking all height of the screen even when closed resulting in no abilities to use left quarter of the screen.
Now devtool only take `100vh` when opened

Fix devtools height when closed on mobile

---

common/libs/nodes/tokenBalanceProxy.ts
package.json
yarn.lock

This implements [`eth-scan`](https://github.com/MyCryptoHQ/eth-scan) in legacy. This (hopefully) fixes some issues with the token scanner not being able to fetch tokens. It uses a customized version of `eth-scan`, which adds support for Shepherd.
* Replaced the token fetch logic with `eth-scan`.
1. Unlock your account
2. Click the button to scan for tokens
3. Check if the token balances are loaded as usual

Implement eth-scan for legacy token scanner

---

jest_config/__mocks__/react-inlinesvg.tsx

Run `yarn test` and see that there are no more errors related to `react-inlinesvg`

Mock react-inlinesvg for jest

---

src/components/ContractLookupField.stories.tsx
src/components/GeneralLookupField.stories.tsx
src/components/WalletUnlock/ViewOnly.tsx
src/features/BuyAssets/BuyAssetsForm.tsx
src/features/DeFiZap/components/ZapForm.tsx
src/features/InteractWithContracts/components/Interact.tsx
src/features/PurchaseMembership/components/MembershipPurchaseForm.tsx
src/features/RequestAssets/RequestAssets.tsx

`Formik render={}` is deprecated.
Replace with child callback function e.g
```
<Formik>{(props) => (<>{//...etc}</>)}</Formik>
```

Replace formik render with child callback function

---

src/features/SignAndVerifyMessage/stories.tsx
src/services/WalletService/deterministic/trezor.ts
src/types/vendor/trezor-connect.d.ts

This PR adds support for singing transactions with Trezor devices. This is the same code as #3469, adapted to work with beta.
1. Go to Sign page on MyCrypto
2. Sign a message using the Trezor option
3. Copy the signed message and make sure it succesfully verifies

Add support for signing messages with Trezor

---

src/features/DeFiZap/components/ZapForm.tsx
src/features/DevTools/DevTools.tsx
src/features/InteractWithContracts/components/fields/AddressField.tsx
src/features/PurchaseMembership/components/MembershipPurchaseForm.tsx
src/features/RequestAssets/RequestAssets.tsx
src/features/Settings/components/AddToAddressBook.tsx

`render` is also deprecated for `Field`.
Replace with child callback.

Remove formik render from fields

---

common/components/WalletDecrypt/disables.ts
common/libs/wallet/deterministic/trezor.ts
common/typescript/trezor-connect.d.ts

This PR adds support for singing transactions with Trezor devices.
1. Go to Sign page on MyCrypto
2. Sign a message using the Trezor option
3. Copy the signed message and make sure it succesfully verifies

Add support for signing messages with Trezor (Legacy)

---

src/features/SignAndVerifyMessage/VerifyMessage.tsx
src/features/SignAndVerifyMessage/types.ts

This adds support for using query params `message`, `address` and `signature` to verify messages.

Add query params for verify message page

---

src/components/TransactionFlow/TxReceipt.tsx

This fixes the timestamp shown on the transaction status page. Currently, the time is multiplied by `1000` which results in a date far into the future ([example](https://mycryptobuilds.com/c0809e40e763a9dad7af0b695f23604cde8a4241/#/tx-status/?hash=0xc38e5a4e49d87b4e99a370efdb4c026f2cf5a8edcb09150e2d5771172220bc9a)). `date-fns` works with normal (second-based) Unix timestamps instead of the default millisecond-based timestamps that JavaScript uses, so the time shouldn't be multiplied.
Fixed example: https://mycryptobuilds.com/pr/3533/#/tx-status/?hash=0xc38e5a4e49d87b4e99a370efdb4c026f2cf5a8edcb09150e2d5771172220bc9a

Fix timestamp for transactions on status page

---

src/services/EthService/network/__tests__/helpers.spec.ts
src/services/EthService/network/helpers.ts

ethers.js allows you to add networks using network id for some networks, but not for networks that are unsupported. Noticed this issue first while looking into #3532.

Fixes an issue with networks unindexable by name

---

src/utils/openLink.spec.ts
src/utils/openLink.ts

🎉 🎉 🎉
Fix `openLink` not properly applying `noreferrer` to external links.
https://html.spec.whatwg.org/multipage/window-object.html#apis-for-creating-and-navigating-browsing-contexts-by-name
Check that an external link doesn't have `window.opener` and `document.referrer` when opened.

Fix external links

---

src/components/GeneralLookupField.tsx

Fixes an issue with the contract interaction page where you couldn't enter an ABI if you input the contract address and pressed Enter to submit.

Trigger onChange when submitting in lookup field using Enter key

---

src/database/data/networks.ts

Fixes the issue where non-ethereum evm networks don't have support for HD wallet types.

Add DW scanner configs for non-ethereum EVM networks

---

src/components/CollapsibleTable.tsx

When user has an account with transactions and views the dashboard in mobile mode, there is the following error:
```
Warning: React does not recognize the `isFlipped` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isflipped` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
Use SC transient props to remove the error:
https://styled-components.com/docs/api#transient-props

SC should not pass props to DOM element

---

src/components/TransactionFlow/TxReceipt.stories.tsx
src/features/PurchaseMembership/components/MembershipEducation.tsx
src/features/PurchaseMembership/components/MembershipPurchaseForm.tsx
src/features/PurchaseMembership/components/MembershipSelector.test.tsx
src/features/PurchaseMembership/components/MembershipSelector.tsx
src/features/PurchaseMembership/config.ts

[ch7346]
Makes some changes for membership configs. Before this is merged, we need for ch7341 to be done.

Membership options changes for release

---

common/utils/versioning/index.ts

This prevents versions `>=2.0.0` from showing up as new available version in the desktop app.

Check if version is <2.0.0 for desktop app

---

src/components/Switch.stories.tsx
src/components/Switch.tsx
src/features/Settings/components/GeneralSettings.tsx

Remove prop error which would display in console when heading to
/settings route.
Steps to test:
1. go to [https://app.mycrypto.com/settings](https://app.mycrypto.com/settings)
2. open the console and see error related to `greyable` prop
3. go to the staging link 
4. see that the error is removed

Use transient prop for greyable SC attribute

---

src/components/AccountSelector.tsx
src/components/AccountSummary.tsx
src/components/AssetSelector.stories.tsx
src/components/AssetSelector.test.tsx
src/components/AssetSelector.tsx
src/components/GeneralLookupDropdown.tsx
src/components/NetworkNodeDropdown.tsx
src/components/NetworkSelector.tsx
src/components/Selector.tsx
src/components/WalletUnlock/DeterministicWallet.tsx
src/components/WalletUnlock/DeterministicWallets.tsx
src/features/InteractWithContracts/components/FunctionDropdownItem.tsx
src/features/InteractWithContracts/components/GeneratedInteractionForm.tsx
src/features/InteractWithContracts/components/fields/BooleanSelector.tsx
src/features/PurchaseMembership/components/MembershipSelector.tsx
src/features/RequestAssets/RequestAssets.tsx
src/features/SendAssets/components/SendAssetsForm.tsx
src/utils/filterAssets.spec.ts
src/utils/filterAssets.ts
src/utils/index.ts

Changed asset dropdown a bit to be more performant.
- Removed Typography from asset selector
- Aligned items in the selector a little better (fixes an issue with the blinking cursor in searchable Selector lacking padding-left).
- Removed displaying of asset icons when using large list of assets (Hardware Scanner & Request Assets).

Improve Asset Dropdown

---

webpack_config/common.js

https://stackoverflow.com/questions/61268885/why-does-app-crush-with-recharts-components

Fix Recharts

---

yarn.lock

Had missed that we still had the old version of Elliptic installed. Fixed that

Bump Elliptic

---

src/services/Store/BalanceService.test.ts
src/services/Store/BalanceService.tsx

Swap over to use getRawBalance instead of getBalance for base assets on networks.

Fix issue with base asset balances on jsonrpc provider-networks

---

src/components/AmountInput.tsx
src/components/AssetIcon.tsx
src/components/Currency.stories.tsx
src/components/Currency.tsx
src/components/Icon/Icon.tsx
src/components/Icon/index.ts
src/components/index.ts

1. Stop `AssetIcon` ticker from wrapping.
Problem:
Fix:
2. Fix alignment of `AssetIcon` in `Currency`
Problem:
Fix:

Include generic asset icon

---

.github/workflows/mycryptobuilds.yml

Commits to add commit hash broke `/ok-to-test`

Fix ok-to-test MyCryptoBuilds

---

src/features/SendAssets/components/SendAssetsForm.tsx
src/features/SendAssets/components/fields/GasPriceSlider.tsx

Refactor GasPriceSlider and fix an issue where it wouldn't update state when a prop had changed.
To reproduce: Switch assets to different networks and see that the default value of the slider changes.

Refactor GasPriceSlider and fix issues with not updating state

---

__tests__/addaccount-page.po.js
__tests__/txstatus-page.po.js

Use `paste` option for form filling to decrease test time. 
Before
After

Optimise dev e2e

---

package.json
src/components/SignTransactionWallets/__tests__/WalletConnect.test.tsx
src/components/WalletUnlock/WalletConnect.tsx
src/config/wallets.ts
src/features/SignAndVerifyMessage/SignMessage.tsx
src/features/SignAndVerifyMessage/stories.tsx
src/services/WalletService/walletService.ts
src/services/WalletService/walletconnect/WalletConnectService.ts
src/services/WalletService/walletconnect/types.ts
src/services/WalletService/walletconnect/useWalletConnect.ts
src/services/WalletService/walletconnect/walletConnectWallet.ts
src/services/WalletService/walletconnect/withWalletConnect.tsx
src/types/walletService.ts
yarn.lock

This fixes an issue where you are unable to sign messages when using WalletConnect. Before, the connection would be automatically killed because the WalletConnect component would be unmounted. This PR does a few things:
* Adds a `autoKill` prop to `useWalletConnect` (enabled by default, disabled for `SignMessage`).
* Changes the type of `WALLETS_CONFIG.WalletConnect` to `MISC`. This may break non-signing related things.

Fix message signing with WalletConnect

---

src/services/Analytics/analytics.middleware.ts
src/services/Analytics/constants.ts

Additional product events. 
- include networkId for add account event
- add setDemoMode to tracked events

Track network for addAccounts

---

src/features/SignAndVerifyMessage/VerifyMessage.tsx
src/utils/normalize.spec.ts
src/utils/normalize.ts

Fixes an issue with macOS sometimes changing quotes, which makes the signed message invalid.

Normalize quotes when parsing signed message

---

src/services/Store/store/account.slice.test.ts
src/services/Store/store/account.slice.ts
src/services/Store/store/index.ts

[ch8805]
Removes pending transaction when nonce is used. This is useful for removing txs that were overwritten by external sources (a different app like Metamask).

Remove pending txs when nonce is used

---

src/services/Analytics/Analytics.ts

- Replaces `any` type with proper one
- Enables customDimensions for `Add Account` and `Add Asset`, since these are now configured in Matomo

Fix: send analytics dimensions properly

---

src/features/PurchaseMembership/components/MembershipSelector.tsx

Match padding on other `54px` selectors

Fix membership selector height

---

src/features/SendAssets/components/SendAssetsForm.tsx

Fixes an issue where data would be stick around if you previously tried to send an ERC20
Steps to test:
1. Go to send flow
2. Create an ERC20 tx
3. Go to confirm screen
4. Go back
5. Switch to ETH transfer and fill out form
6. Go to confirm screen
7. See that the data field is now `0x`

Fix send assets data bug
