MyCryptoHQ/MyCrypto

.travis.yml, common/api/utils.js
We don't need travis to email us every time.
=> Adjust travis notifications

common/routing/index.jsx
Just linted the router file, double quotes -> single quotes
=> Linting routing

common/containers/Tabs/SendTransaction/components/AddressField.jsx, common/containers/Tabs/SendTransaction/index.jsx
add some localizations and remove angular.
=> Send: cleanup

.flowconfig, package-lock.json, package.json
This attempts to fix the flow errors about style modules in components, as outlined here: https://gist.github.com/lambdahands/d19e0da96285b749f0ef
=> Flow style include fix

.eslintrc.json
@skubakdj just got bit by this in #116, so I think it's a worthwhile addition.
=> Add no-restricted-globals rule

common/components/Header/components/GasPriceDropdown.jsx
Fixes #81 by only responding to gas price changes every 50 milliseconds
=> Throttling changes to gas price (#81)

common/containers/Tabs/GenerateWallet/components/DownloadWallet.jsx, common/libs/keystore.js, common/libs/wallet/privkey.js
=> Use async in download wallet

common/components/AlphaAgreement/index.jsx, common/components/AlphaAgreement/index.scss, common/components/Header/index.scss, common/components/index.js, common/containers/App/index.jsx
* Requires a user to agree to use v4 before allowing them in
* Sends them back to v3 if they disagree
* Saves their agreement in localstorage to prevent future bugging
* Bumps up the size of the banner a bit
Let me know if you want to have someone work on the copy.
---
=> Alpha required agreement

common/config/data.js
Solves https://github.com/MyEtherWallet/MyEtherWallet/issues/153
=> Provide Method of Updating Users about V4 Alpha

common/config/data.js, common/containers/Tabs/SendTransaction/index.jsx
This PR fixes the "no bignumber" error that occurs when changing the amount value to an empty string.
To fix this, we only estimate gas when the amount value can be parsed to a number.
This PR also contains a small amount of refactoring, mostly around destructuring assignments.
=> Fix "no bignumber" Error

common/actions/notifications.js, common/reducers/index.js, common/reducers/swap/index.js, common/sagas/config.js, common/sagas/contracts.js, common/sagas/deterministicWallets.js, common/sagas/ens.js, common/sagas/notifications.js, common/sagas/swap/orders.js, common/sagas/wallet.js
Partially addresses https://github.com/MyEtherWallet/MyEtherWallet/issues/163
* Wrapped our Yield, Return, and Next types into a central export to reuse.
* Went through all sagas and typed them.
* Traced some flow error that occurred as a result of typing all sagas.
=> Saga Flow Audit

common/api/bity.js, common/components/BalanceSidebar/BalanceSidebar.jsx, common/components/ExtendedNotifications/TransactionSucceeded.js, common/config/bity.js, common/config/data.js, common/containers/Tabs/Swap/components/CurrencySwap.jsx, common/containers/Tabs/Swap/components/SwapProgress.jsx
Completely Addresses https://github.com/MyEtherWallet/MyEtherWallet/issues/165
=> Refactor Bity

common/components/Footer/PreFooter.jsx, common/components/Footer/PreFooter.scss, common/components/Footer/index.jsx, common/components/Footer/index.scss
Solves https://github.com/MyEtherWallet/MyEtherWallet/issues/200
- create PreFooter components and styles
- add PreFooter to main Footer Component and adjust Footer styles
=> Add Pre-footer

common/config/data.js
=> Alpha 0.0.2

.babelrc, common/components/Root/index.jsx, common/index.jsx, common/routing/index.js, common/routing/index.jsx
This reverts commit b59298ec0e3f4a70c1b5aa4e128778d803793572.
The HMR fix commit currently breaks production build.
=> Revert "Hot module reload fixes (#181)"

common/store.ts
Closes https://github.com/MyEtherWallet/MyEtherWallet/issues/81
- persist gas price config to local storage
=> Persist Gas Price

README.md
Quid pro quo. You can see what it looks like in the readme here: https://github.com/MyEtherWallet/MyEtherWallet/tree/bs-readme#thanks--support. This is also probably a good spot to add anyone else.
=> Add browserstack to the readme

common/components/ui/QRCode.tsx, common/containers/Tabs/GenerateWallet/components/DownloadWallet.tsx, common/containers/Tabs/SendTransaction/components/ConfirmationModal.tsx, common/containers/Tabs/SendTransaction/index.tsx, common/containers/Tabs/Swap/components/CurrencySwap.tsx, common/containers/Tabs/Swap/components/CurrentRates.tsx, common/containers/Tabs/Swap/components/SwapInfoHeader.tsx, common/containers/Tabs/Swap/components/SwapInfoHeaderTitle.tsx, common/containers/Tabs/Swap/index.tsx, common/sagas/contracts.ts
- fix generate wallet bug
- allow 0s in swap input fields
- misc unused import removal
- remove console logs
=> Fix Typescript Refactor

common/components/Header/index.tsx, common/components/ui/Dropdown.tsx, common/config/data.ts, common/config/languages.json, common/reducers/config.ts, common/utils/helpers.ts
- simplify language dropdown 
- move language mapping to separate file 
- fix rpc regression (bring node options back in)
=> Refactor Languages / Fix RPC Node Regression

common/containers/Tabs/SendTransaction/index.tsx
Accidentally added `console.log()`'s from https://github.com/MyEtherWallet/MyEtherWallet/commit/6f7e3c27e2f984f28021e0c4fd03b1c948a9c7a0, this will remove them.
=> Remove unnecessary console logs

.travis.yml, common/components/ui/Dropdown.tsx, common/components/ui/SimpleDropdown.tsx, common/containers/Tabs/SendTransaction/components/UnitDropdown.tsx
fixes https://github.com/MyEtherWallet/MyEtherWallet/issues/258
- add typescript compiler check to travis
- fix existing typescript compiler errors
=> Travis TypeScript Compiler Checking

README.md
Update readme to enforce more maintainable code
=> Update Code Guidelines

package.json
=> fix(package): update react to version 16.1.1

package.json
=> chore(package): update redux-test-utils to version 0.2.1

common/sagas/config.ts
=> Unset Web3 Node on Wallet Reset

common/sagas/swap/rates.ts
Fixes https://github.com/MyEtherWallet/MyEtherWallet/issues/413
Current polling cycle of 5s is too frequent.
=> Set Bity Rates Polling Cycle to 30 Seconds

README.md
Closes #394. Hope this is clear enough!
=> Add information about typing connected components to README

common/components/WalletDecrypt/index.tsx
Closes https://github.com/MyEtherWallet/MyEtherWallet/issues/444
=> Re-Order Decrypt Options to Match V3

package.json
=> chore(package): update copy-webpack-plugin to version 4.2.3

package.json
=> chore(package): update check-node-version to version 3.1.1

common/containers/Tabs/SignAndVerifyMessage/components/SignMessage/index.tsx
=> Arrow functionify to prevent error in Sign Message

.prettierrc, package.json
This PR adds a config file that prettier will use, keeping everyone's config the same
=> Fix Prettier Configuration

common/components/BalanceSidebar/Promos.tsx, common/components/Footer/index.tsx, common/components/Header/components/GasPriceDropdown.tsx, common/components/Header/components/Navigation.tsx, common/components/WalletDecrypt/index.tsx, common/config/data.ts, common/containers/Tabs/ENS/components/GeneralInfoPanel/index.tsx, common/containers/Tabs/GenerateWallet/components/DownloadWallet.tsx, common/containers/Tabs/GenerateWallet/components/EnterPassword.tsx, common/containers/Tabs/GenerateWallet/components/PaperWallet.tsx, common/containers/Tabs/Help/index.tsx, common/containers/Tabs/SendTransaction/components/NonceField.tsx
Closes https://github.com/MyEtherWallet/MyEtherWallet/issues/458
* Add `const knowledgeBaseURL` to `common/config/data.ts`
* Replace all hardcoded urls
* Update old knowledge base paths
=> Update Knowledge-Base Links

README.md
Updates readme to include notes about the address derivation checker and integration testing
=> ReadMe Updates (Integration Testing/Address Derivation) 

package.json
=> chore(package): update nodemon to version 1.12.7

package.json
Redux-Form is no longer a dependency
=> Remove Redux-Form Types Dependency

package.json
=> chore(package): update nodemon to version 1.13.2

common/components/WalletDecrypt/components/LedgerNano.tsx
Closes #691. Not much more to it than this:
=> Ledger warning

package.json
=> chore(package): update @types/react to version 16.0.34

package.json
Closes https://github.com/MyEtherWallet/MyEtherWallet/issues/496 (more information in https://github.com/MyEtherWallet/MyEtherWallet/issues/347)
There are likely additional files that will need to be frozen. We can add to this list over time, but it will serve as a baseline to get the ball rolling.
Also, it is important to note that changes to the files listed in `"freezer"` will still be permissible, but will require administrator override. Having CI fail on any changes to these files allows us to heavily scrutinize 
(perhaps to the point of requiring an external audit) changes before allowing a merge.
=> Configure Freezer

common/components/GasSlider/components/AdvancedGas.tsx, common/components/GasSlider/components/SimpleGas.tsx
Addresses number 2 in https://github.com/MyEtherWallet/MyEtherWallet/issues/571#issuecomment-355836066. I'll address the nonce issue in a later PR. Also forces the numbers to be, well, numbers.
=> Slider prop error fix

common/api/shapeshift.ts, common/config/tokens/eth.json, spec/reducers/swap.spec.ts
There were some missing whitelist tokens in the eth.json file. I added them back and also added a test to ensure all future whitelist tokens exist in the json.
=> Add Default Tokens

spec/package.json.spec.ts
Closes https://github.com/MyEtherWallet/MyEtherWallet/issues/794
=> Ensure package versions are exact

common/components/ui/UnlockHeader.tsx, common/config/data.ts, common/sagas/config.ts, spec/sagas/config.spec.ts
(Forgot to re-base branch in https://github.com/MyEtherWallet/MyEtherWallet/pull/815)
Closes https://github.com/MyEtherWallet/MyEtherWallet/issues/642
I believe wallet and transaction state is the only state that needs to get reset when changing networks. I couldn't think of any any other state that would be need to be reset during a network change, but please comment if you think there is.
Branched off of https://github.com/MyEtherWallet/MyEtherWallet/pull/813, will re-base branch after merge.
=> Change network without window refresh

common/components/WalletDecrypt/components/Trezor.tsx, common/libs/wallet/deterministic/trezor.ts, common/vendor/trezor-connect.js
This PR updates our Trezor vendor file to version 4, [which was done back in November for v3](https://github.com/kvhnuke/etherwallet/commit/af5ecdcdd947dc38cb0c55802476772127e696ca#diff-102af3612c74fe120bd2878b53c58379). I'm not sure of all the details, but I do know that this makes Trezor work in offline environments (Downloadable HTML build, and the upcoming Electron build) by fixing some bugs that came from assuming certain things about the environment it was running.
Unfortunately, this undoes @james-prado's [alterations to `trezor-connect.js`](https://github.com/MyEtherWallet/MyEtherWallet/commit/0fa0004e3bace26ae7e45f9123b25d44bd92fc69#diff-697f5a96937411134f084d8f5bd932d5) from earlier, and forces us back to using `(TrezorConnect as any)`. However, I think altering anything that …
=> Update trezor-connect.js to v4

common/containers/Tabs/Contracts/components/Interact/components/InteractForm/index.tsx, common/sass/mixins.scss, common/sass/styles.scss, common/sass/styles/overrides.scss, common/sass/styles/overrides/forms.scss, common/sass/styles/overrides/react-select.scss, common/sass/variables/forms.scss
- Add a new override file `react-select.scss`
- Style new `<Select />` components like all the other components
- Add `is-invalid` class to `<Select />` where validation is necessary
- `is-invalid` is handled in `react-select.scss` overrides
=> Add react-select style overrides

package.json
=> chore(package): update image-webpack-loader to version 4.0.0

common/components/AmountFieldFactory/AmountInputFactory.tsx, common/components/GenerateTransaction/GenerateTransaction.tsx, common/sagas/swap/liteSend.ts, common/selectors/transaction/current.ts, common/selectors/wallet.ts, webpack_config/makeConfig.js
=> Fix misc send issues

common/components/BalanceSidebar/EquivalentValues.tsx
Closes https://github.com/MyEtherWallet/MyEtherWallet/issues/938
=> Handle unsupported units in EquivalentValues

common/components/Translate.tsx
Closes https://github.com/MyCryptoHQ/MyCrypto/issues/1003
- Add `'inlineCode'` to `allowedTypes` array
=> Update <Markdown/> allowedTypes

common/reducers/config/nodes/staticNodes.ts, spec/reducers/config/nodes/staticNodes.spec.ts
Closes #1052 
Update the old MyEtherWallet Infura endpoints to the new MyCrypto ones
* Replaced mew by mycrypto in staticNodes.ts and staticNodes.spec.ts
=> Update infura endpoints (#1052)

common/index.html
Closes #1076 
Fixes the grammar error, specifies _desktop_ computer, not just "laptop or computer".
=> Fix bad browser copy

common/config/data.tsx
Closes #1064
Sets common/config/data.ts's `VERSION` var to the package.json's `version`. Still adds `(BETA)` to the end.
=> Source VERSION from package.json

common/components/BalanceSidebar/AccountInfo.tsx, common/components/CurrentCustomMessage.tsx, common/containers/Tabs/SendTransaction/components/RequestPayment.tsx, common/containers/Tabs/SendTransaction/components/WalletInfo.tsx, common/containers/Tabs/SignAndVerifyMessage/components/SignMessage/SignButton.tsx, common/libs/wallet/IWallet.ts, common/libs/wallet/deterministic/deterministic.ts, common/libs/wallet/non-deterministic/web3.ts, common/utils/localStorage.ts
Closes https://github.com/MyCryptoHQ/MyCrypto/issues/1153
To test:
1. test generate keystore works (from https://github.com/MyCryptoHQ/MyCrypto/pull/1154/files#diff-da809197b595406e304acd50516913eaR62)
2. test web3 unlock works (https://github.com/MyCryptoHQ/MyCrypto/pull/1154/files#diff-6e02304097be0810552c805f4537b71bR18)
3. Test signing works for all formats (https://github.com/MyCryptoHQ/MyCrypto/pull/1154/files#diff-14d64f27973fa652c812d4bf57981601R28)
4. Test payment requests work (https://github.com/MyCryptoHQ/MyCrypto/pull/1154/files#diff-3b47f7a518452473a0a206bddecfd7b9R144)
5. Test creating a signed message on all wallet formats (https://github.com/MyCryptoHQ/MyCrypto/pull/1154/files#diff-4922ccfe05f56e9512da9a9c6571d78dR52
=> Adjust Wallet Interface

package.json
=> chore(package): update html-webpack-plugin to version 3.0.3

package.json
=> fix(package): update hard-source-webpack-plugin to version 0.6.4

common/components/ui/Modal.tsx
Closes #1097, pretty straightforward.
=> Fix Disclaimer Open on ESC

common/components/AddressField.tsx, common/components/ConfirmationModal/components/Body/components/Addresses.tsx, common/containers/Tabs/SendTransaction/components/RequestPayment.tsx
Closes https://github.com/MyCryptoHQ/MyCrypto/issues/1313
Also includes checksumming on the confirmation modal
=> Add checksumming to payment request & confirmation modal

package.json
=> chore(package): update @types/react to version 16.3.4

.travis.yml, jest_config/jest.config.json, jest_config/jest.int.config.json, package.json
Closes #865
Increases max workers by one for tests to increase testing speed
Requires @dternyak to signup on https://coveralls.io/ and add this repository to be reported
=> Add coverage reporting with coveralls

common/config/tokens/eth.json, package.json, scripts/types/CommitStatus.ts, scripts/types/GitCommit.ts, scripts/types/TokensJson.ts, scripts/update-tokens-utils.ts, scripts/update-tokens.ts, tsconfig.json
- Converts the list script to typescript for type safety
- Adds validation functions to ensure that the resulting token list exactly matches our `Token` type
- Handles Symbol collisions by either appending the name of the token (if the name is not duplicated either) or the index of the current token in the list of tokens with the same symbol
- Warns user of script on token symbol collisions
1. `npm run update:tokens`
=> Eth-lists-script Typescript

README.md, common/components/BetaAgreement/index.tsx, common/config/data.tsx, common/config/links.ts, common/translations/lang/en.json, package.json
This PR contains 
- messaging updates to reflect the Release Candidate status of this codebase
- bumps the version to 1.0.0 (RC)
- adds steely affiliate links to match support.mycrypto.com
=> Prep Launch of Release Candidate

package.json, yarn.lock
Updates the package resolution for `@types/react` so they all resolve to the same package
=> Fix react yarn type resolution

common/containers/OnboardModal/index.tsx, common/libs/wallet/deterministic/ledger.ts, common/reducers/transaction/meta/meta.ts, spec/reducers/transaction/meta/meta.spec.ts
=> More RC Bugfixes

common/components/WalletDecrypt/WalletDecrypt.scss, common/components/WalletDecrypt/WalletDecrypt.tsx, common/components/WalletDecrypt/components/Trezor.tsx
Closes #1312
Updates the TREZOR help link, but also bumps some spacing that bugged me while I was working on this.
* Updated TREZOR help link to knowledge base article
* Bump up "Change Wallet" padding on mobile to not be so crammed
=> Trezor Help Link & Decrypt UI

common/sagas/wallet/wallet.ts
The branch by @wbobeirne didn't work until i swapped out two sagas, would love to get a review on that.
=> Fix retry scan if you have no tokens

common/libs/web-workers/workers/generateKeystore.worker.ts
=> Remove checksumming of keystore address

common/translations/lang/en.json
Closes https://github.com/MyCryptoHQ/MyCrypto/issues/1747
=> Add private key deprecation information

jest_config/jest.config.json
Closes https://github.com/MyCryptoHQ/MyCrypto/issues/1749
=> Exclude components from coverage reports

package.json
=> chore(package): update electron-builder to version 20.13.4

common/libs/nodes/configs.ts
mewapi.epool.io >> mew.epool.io
If you're contributing translations, please follow the contributor guidelines
at https://github.com/MyCryptoHQ/MyCrypto/wiki/Contributor-Guidelines#providing-translations
---
If you're contributing code, please link to the issue it resolves and follow the
contributor guidelines at https://github.com/MyCryptoHQ/MyCrypto/wiki/Contributor-Guidelines#contributing-code and fill out the following template:
Closes #(issue number goes here)
(Description goes here)
* High level
* Changes that
* You Made
1. Steps
2. To
3. Test
(Only if applicable)
=> Update epool node

common/libs/nodes/configs.ts
Closes https://github.com/MyCryptoHQ/MyCrypto/issues/1696
=> Update ETC Epool Node URL

README.md
Updates readme to help prevent issues like #1920.
=> Add system requirements to README.md

README.md
Fixes changes requested for #1933
=> Change shell commands to reflect yarn usage

common/containers/Tabs/ENS/components/NameResolve/components/NameOwned.tsx, common/sagas/ens/modeMap.ts, common/translations/lang/en.json
Closes #1888. Screenshot included. 
Also, it seems the value `Highest Bidder` field is actually the highest bid, so I changed things accordingly.
=> [Fix] Make ENS Value Consistent

electron-app/main/window.ts
=> MC-01-004: Prevent Navigation on Main Electron Window

common/components/ElectronNav/ElectronNav.tsx
Closes https://github.com/MyCryptoHQ/MyCrypto/issues/2015
=> Remove Alpha Banner on Electron

common/config/tokens/eth.json
Source: https://medium.com/@AugurProject/augur-launches-794fa7f88c6a
---
REP TokenMigration
* REP Token address
=> REP Token Address Change

shared/enclave/server/views/passphrase.html, shared/enclave/server/views/passphrase.ts, shared/enclave/server/views/pin.html, shared/enclave/server/views/pin.ts, shared/enclave/server/views/showPrompt.ts, shared/enclave/server/wallets/trezor.ts
Closes #2047
TREZOR wallets with a passphrase were having an event skipped, preventing them from being unlocked.
* A prompt now occurs after PIN to enter the passphrase.
* Entering the passphrase correctly unlocks the wallet.
1. Download the electron build.
2. Attempt to log into a TREZOR equipped with a passphrase.
3. Enter the passphrase and press "Unlock".
4. The wallet should unlock.
=> Enable login for TREZOR with passphrase

common/components/WalletDecrypt/WalletDecrypt.scss
Just a tiny bit more breathing room
before on left. after on right.
=> Add Margin to Wallet Decrypt 

common/config/addressMessages.ts
At request of Ledger HQ,
Added a notice to address:  0xC33B16198DD9FB3bB342d8119694f94aDfcdca23
MSG added: 
`This addresses has been associated with an ongoing issue with the Ledger Chrome App. Monitor their twitter account for updates at: https://twitter.com/LedgerHQ`
=> Added Message for Ledger bug address

common/features/config/networks/static/reducer.ts, common/libs/nodes/configs.ts, shared/types/network.d.ts
GoChain is a scalable, Ethereum based smart contract blockchain that is fast, secure and green.
- Homepage: https://gochain.io/
- Node: https://rpc.gochain.io/
- Explorer: https://explorer.gochain.io/
- BIP44 / Chainid 6060 ( satoshilabs/slips#284 )
- Added support for Gochain tesnet
=> Added GoChain testnet support

common/libs/nodes/configs.ts
Preventative measure for increased traffic from the Coinbase addition. Will follow-up with more nodes.
If you're contributing translations, please follow the contributor guidelines
at https://github.com/MyCryptoHQ/MyCrypto/wiki/Contributor-Guidelines#providing-translations
---
If you're contributing code, please link to the issue it resolves and follow the
contributor guidelines at https://github.com/MyCryptoHQ/MyCrypto/wiki/Contributor-Guidelines#contributing-code and fill out the following template:
Closes #(issue number goes here)
(Description goes here)
* Removed Commonwealth nodes; they're down and traffic is expected to increase
* Added Gastracker node
1. Select Gastracker from the dropdown top right
2. Note it connects successfully
(Only if applicable)
=> Add gastracker; remove Commonwealth as their nodes are currently down

common/containers/Tabs/ScheduleTransaction/components/Fields/TimeBounty/TimeBountyField.tsx, common/features/schedule/sagas.ts, common/translations/lang/en.json
Adds TimeBounty warning when not enough funds.
=> [BUGFIX] Add TimeBounty warning.

common/config/tokens/eth.json
Synced tokens from https://github.com/ethereum-lists/tokens
=> Updated ethTokens.json

package.json
=> New release

common/containers/Tabs/Swap/components/SupportFooter.tsx
In the support textarea, the exchange rate origin/destination are switched around.
=> Fix incorrect exchange rate

common/containers/Tabs/SignAndVerifyMessage/components/VerifyMessage/index.tsx
Solution for https://mycrypto.atlassian.net/browse/CORE-66.
=> [BUGSQUASH] Fix typo in Verify popup

common/Root.tsx, common/containers/Tabs/SignAndVerifyMessage/components/SignMessage/index.tsx
Solution for https://mycrypto.atlassian.net/browse/CORE-63.
=> [BUGSQUASH] Prompt before leaving Sign/Verify

common/containers/Tabs/SendTransaction/components/RequestPayment.tsx
Solution to https://mycrypto.atlassian.net/browse/CORE-88
=> [BUGSQUASH] Remove the Gas Limit panel from Request Payment

common/components/WalletDecrypt/WalletDecrypt.tsx
Solution for https://mycrypto.atlassian.net/browse/CORE-43.
=> [BUGSQUASH] Don't set state after timeout if WalletDecrypt no longer exists

common/components/ui/UnlockHeader.scss
Solution to https://mycrypto.atlassian.net/browse/CORE-142.
=> [BUGSQUASH] Adjust Change Wallet button's z-index

common/components/WalletDecrypt/components/WalletButton.scss, common/components/WalletDecrypt/components/WalletButton.tsx
Solution to https://mycrypto.atlassian.net/browse/CORE-122.
=> [BUGSQUASH] Fix weird outline on wallet selection

common/components/ui/Dropdown.tsx
Solution to https://mycrypto.atlassian.net/browse/CORE-136.
=> [BUGSQUASH] Show initial value as ETH in SendTransaction

common/containers/Tabs/Swap/components/CurrencySwap.tsx
Solution to https://mycrypto.atlassian.net/browse/CORE-24.
=> [BUGSQUASH] Make swap pair changing empty vs. 0

common/components/WalletDecrypt/components/WalletButton.tsx
Solution to <insert issue here>.
=> [BUGSQUASH] Disallow clicking link on disabled WalletButton.

common/components/BalanceSidebar/TokenBalances/index.tsx, common/features/customTokens/actions.ts, common/features/customTokens/types.ts, common/features/wallet/sagas.ts, common/translations/lang/en.json, common/utils/tokens.ts
Solves https://mycrypto.atlassian.net/browse/CORE-120.
=> [BUGSQUASH] Prevent duplicate token additions

common/config/dpaths.ts, common/features/config/networks/static/reducer.ts, common/libs/nodes/configs.ts, shared/types/network.d.ts
This PR caused an issue with SendTransaction. To be fixed.
=> Revert "Add support for iOlite Network"

common/containers/Sidebar/Sidebar.scss, common/index.html, common/v2/features/BuyAndExchange/ShapeShift/components/Support.scss, webpack_config/makeConfig.js
* Fix styling issue related to scoped helper class in Sidebar
=> Release 1.5.0.3

common/config/tokens/eth.json
Annoucement: https://medium.com/melonport-blog/mln-token-migration-event-96b1c8003876
Needs update for Friday, Feb 1, 2019
- Deprecate Old MLN 
- Added New MLN
=> MLN token address update + others

common/components/ui/Input.tsx, common/utils/versioning/index.ts
The code had some `console.log`s that would spam the console on the desktop version and possibly the web version too.
* Remove the `console.log`s.
=> Remove unnecessary `console.log`

package.json
Remove security vulnerability.
=> Tick Lodash version

common/api/emails.ts
Change from EmailOctopus to MailChimp.
=> Update email API

package.json
=> Release 1.5.8 (Test Release)

common/libs/wallet/deterministic/trezor.ts, common/typescript/trezor-connect.d.ts, common/vendor/trezor-connect.js
Close #2389
Updates TrezorConnect
* Updated local storage of trezor-connect.js 
* Altered TrezorConnect lib to handle new promise-based reqs.
1. Access Wallet using Trezor device and attempt to send transaction
2. The user experience with sending via Trezor device shouldn't change.
=> Update Trezor Connect

package.json
=> hotfix to gasprice and Trezor/CSP

common/config/dpaths.ts, common/features/config/networks/static/reducer.ts, common/libs/nodes/configs.ts
Add support TomoChain Mainnet.
Refer to https://github.com/kvhnuke/etherwallet/pull/2093, https://github.com/kvhnuke/etherwallet/pull/2170
=> Add support TomoChain Mainnet

common/api/rates.ts
Updates to API Gateway CryptoCompare proxy to fix `mycryptobuilds` CORS error and some overall clean up.
-Created a new API Gateway method.
-Updated proxy endpoint in rates.ts to reflect API changes.
1. Test CC prices on `mycryptobuilds`.
2. Check console for any CORS errors.
=> API Gateway proxy updates

.travis.yml, jest_config/setupJest.js, package.json, webpack_config/webpack.electron-dev.js, yarn.lock
due to https://github.com/LedgerHQ/ledgerjs/blob/master/docs/migrate_eth_app.md
=> update ledger packages

common/v2/services/LocalCache/LocalCache.ts, common/v2/services/NodeOptions/NodeOptions.ts, common/v2/services/NodeOptions/types.ts
* Added createWithID method.
TODO:
=> Add createWithID Method

common/v2/features/AddAccount/AddAccount.tsx
=> Re-Add and Enable view-only account type

common/translations/lang/en.json, common/v2/features/Dashboard/components/AccountList.tsx
Before fix: 
If user deleted all accounts while on dashboard they wouldn't be redirected. 
After fix:
Redirects user to no-accounts if they delete all their accounts while on dashboard.
=> redirect user from dashboard if no account exists

common/v2/features/AddAccount/AddAccount.tsx, common/v2/features/AddAccount/AddAccountStyles.scss
https://mycrypto.atlassian.net/browse/CW-17
=> Select Network

common/v2/features/AddAccount/AddAccountFlow.tsx, common/v2/features/AddAccount/AddAccountForm.reducer.tsx, common/v2/features/AddAccount/components/SaveAndRedirect.tsx, common/v2/features/AddAccount/stories.tsx, common/v2/features/AddAccount/types.tsx
=> add-existing-account refactor -> onUnlock handling

common/v2/features/SendAssets/SendAssets.tsx, common/v2/features/SendAssets/components/ConfirmTransaction.tsx, common/v2/features/SendAssets/components/SignTransaction.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/Keystore.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/Ledger.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/Metamask.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/Mnemonic.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/Parity.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/PrivateKey.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/SafeTmini.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/Trezor.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/index.ts, common/v2/features/SendAssets/components/TransactionComplete.tsx, common/v2/features/SendAssets/components/TransactionFormData.tsx, common/v2/features/SendAssets/components/index.ts, common/v2/features/SendAssets/constants.js, common/v2/features/SendAssets/constants.ts
- Refactored current components in flow into higher order functions which take in props and return main component
- why this was done: TS Errors 
- Implemented initial rendering of sign transaction with wallets components
=> initial setup of sign transaction with wallets flow

common/v2/features/SendAssets/SendAssets.tsx, common/v2/features/SendAssets/components/ConfirmTransaction.tsx, common/v2/features/SendAssets/components/SignTransaction.tsx, common/v2/features/SendAssets/components/TransactionFormData.scss, common/v2/features/SendAssets/components/TransactionFormData.tsx, common/v2/features/SendAssets/components/TransactionReceipt.tsx, common/v2/features/SendAssets/components/fields/AmountField.tsx, common/v2/features/SendAssets/components/fields/AssetField.tsx, common/v2/features/SendAssets/components/fields/RecipientAddressField.tsx, common/v2/features/SendAssets/components/fields/SenderAddressField.tsx, shared/types/util.d.ts
https://app.clubhouse.io/mycrypto/story/1248/hook-up-transaction-data-form-to-confirm-transaction-panel
=> Sign transaction with wallets Flow

README.md
Please merge into develop, not release
=> Fix inconsistent Node version in readme

common/v2/features/AddAccount/components/SaveAndRedirect.tsx, common/v2/features/Dashboard/components/AccountList.tsx, common/v2/features/Dashboard/components/WalletBreakdown.tsx, common/v2/features/DevTools/DevTools.tsx, common/v2/features/Wallets/web3/web3.ts, common/v2/libs/accounts/accounts.ts, common/v2/libs/accounts/index.ts, common/v2/libs/assets/assets.ts, common/v2/libs/assets/index.ts, common/v2/libs/index.ts, common/v2/libs/networks/networks.ts, common/v2/providers/AccountProvider/AccountProvider.tsx, common/v2/services/Account/Account.ts, common/v2/services/Account/types.ts, common/v2/services/LocalCache/constants.ts, common/v2/services/NodeOptions/types.ts
Just a baseline implementation of balance fetching for dashboard. Has bugs. Only supports base assets (no erc-20s).
=> Account balance fetch

common/v2/features/SendAssets/components/SignTransaction.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/Ledger.scss, common/v2/features/SendAssets/components/SignTransactionWallets/Ledger.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/MetaMask.scss, common/v2/features/SendAssets/components/SignTransactionWallets/Metamask.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/SafeTmini.scss, common/v2/features/SendAssets/components/SignTransactionWallets/SafeTmini.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/Trezor.scss, common/v2/features/SendAssets/components/SignTransactionWallets/Trezor.tsx, package.json, yarn.lock
Web views only
https://app.clubhouse.io/mycrypto/story/553/step-2-sign-transaction-safe-t-mini-styles
=> Sign transaction with SafeTmini styles

common/v2/features/SendAssets/components/SignTransaction.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/MetaMask.scss, common/v2/features/SendAssets/components/SignTransactionWallets/Metamask.tsx, package.json, yarn.lock
=> Sign with MetaMask using ethers.js

package.json
- Update to Readme
- WebUSB support for Ledger devices (waiting on a fix for windows)
- Crypto10 Hedged Contract and ABI
- Yarn audit for the entire code base!
- Udate to RSK.json
=> release 1.6.7

README.md
🎉 🎉 🎉
Adds the guide to verify the releases to this doc's readme.
=> Added release verification guide to README

common/v2/features/SendAssets/components/TransactionFormData.scss, common/v2/features/SendAssets/components/TransactionFormData.tsx, common/v2/features/SendAssets/components/fields/DataField.tsx, common/v2/features/SendAssets/components/fields/GasLimitField.tsx, common/v2/features/SendAssets/components/fields/GasPriceField.tsx, common/v2/features/SendAssets/components/fields/NonceField.tsx, common/v2/features/SendAssets/components/index.ts, common/v2/features/SendAssets/components/validators/index.ts, common/v2/features/SendAssets/components/validators/validators.ts
Implements field-level validation for advanced transaction fields. Refactored advanced fields to conform with the format that @vilsbole used in sender-address
=> Advanced Transaction Field tweaks / refactor

.travis.yml
TravisCI build notifications to `#bot_github` slack channel.
Added Slack notification to travis yaml file with encrypted credentials.
=> travisCI Slack integration

common/translations/lang/en.json, common/v2/features/SendAssets/components/TransactionFormData.tsx, common/v2/features/SendAssets/components/displays/TransactionValuesDisplay.tsx, common/v2/features/SendAssets/components/displays/index.ts, common/v2/features/SendAssets/components/fields/AccountDropdown.tsx
Filtering for sender address
Filters sender address dropdown based on the network of the asset selected. If no asset is selected, default to empty dropdown.
~*Get UX feedback before publishing*~
=> Sender Address Filtering

common/v2/features/Dashboard/Dashboard.tsx, common/v2/features/Dashboard/Settings/Settings.tsx, common/v2/features/Dashboard/components/AccountDropdown.tsx, common/v2/features/Dashboard/components/AccountList.tsx
Fix Settings Account List and Dashboard Dropdown rendering
* Update settings to show all accounts instead of current accounts
* Update dashboard to render whenever a wallet is selected from the dropdown
=> Fixes to accounts table and dashboard dropdown rendering

common/v2/features/Layout/Footer/Footer.scss, common/v2/features/Layout/Footer/components/LogoBox.scss, common/v2/features/Layout/Footer/components/LogoBox.tsx
* Removes the moon mode toggle from the footer
=> Remove Moon Mode Toggle

common/v2/config/networks/globalProvider.ts, common/v2/config/networks/index.ts, common/v2/config/networks/providerHandler.ts, common/v2/features/AddAccount/components/SaveAndRedirect.tsx, common/v2/features/Dashboard/components/WalletBreakdown.tsx, common/v2/features/DevTools/DevTools.tsx, common/v2/features/SendAssets/components/TransactionFormData.tsx, common/v2/features/Wallets/web3/web3.ts, common/v2/libs/accounts/accounts.ts, common/v2/libs/nodes/rpc/requests.ts, common/v2/libs/transaction/process.ts, common/v2/libs/units.ts, common/v2/services/Account/types.ts, common/v2/services/LocalCache/LocalCache.ts, common/v2/services/LocalCache/constants.ts
Added a class wrapping the ethers.js interactions to provide standardized handler methods.
Added GasLimitEstimation as a method for testing one of the methods.
=> ethers.js class provider

common/v2/features/SendAssets/components/SendAssetsForm.tsx
Fix Formik onsubmit button for send-assets form
=> Fix formik submission for send-assets

common/api/shapeshift.ts
- Update ClientID for ShapeShift integration
- String change
1. Steps
2. to
3. test
=> update shapeshift client id

common/translations/lang/en.json, common/v2/components/ENSStatus.tsx, common/v2/components/index.ts, common/v2/features/SendAssets/components/SendAssetsForm.tsx, common/v2/features/SendAssets/components/fields/EthAddressField.tsx, common/v2/features/SendAssets/components/fields/GasLimitField.tsx, common/v2/features/SendAssets/components/validators/validators.ts, common/v2/libs/formatters.ts, common/v2/libs/validators.ts
_Rebase to gau once `mh/ens-resolution` is merged._
Note: For on-chain name resolution we can't use a library for validation because there isn't one that exists for all of the chains that we use. Decided to implement a custom regex function depending on valid tlds depending on chain.
Fixed validation / validation translatons. These are something that would be useful to test.
=> Validation changes & other cleanup stuff

common/v2/features/ReceiveAssets/ReceiveAssets.tsx
Implements `react-select` for the receive flow assets dropdown with closer styles to other inputs
=> Fix ComboBox Autocompletion

common/v2/services/Github/constants.ts
=> Change the github link to proxy link

common/v2/features/SendAssets/components/SendAssetsForm.tsx
Fixes an outstanding issue with showing base-assets in send-assets dropdown.
*Note: There appears to be something in the Analytics service tests that are broken. I haven't touched these at all in this PR.*
=> Re-Added base assets on send flow assets-dropdown

common/v2/config/routePaths.ts, common/v2/services/Store/Settings/SettingsProvider.tsx
Fixed an error where an error message wouldn't display when a user tried to upload an incorrect filetype (like an image) as a settings file.
[ch2487]
=> Fix settings import file type detection error

package.json
Current Release Updates
- RSK Testnet addresses (contract and token) change
=> release 1.7.1

common/translations/lang/en.json, common/translations/lang/fr.json, common/translations/lang/ja.json, common/translations/lang/ko.json, common/v2/config/data.tsx, common/v2/config/links.ts, common/v2/features/Dashboard/NotificationsPanel/components/OnboardingResponsibleNotification.tsx, common/v2/features/Layout/Footer/components/Linkset.tsx
Various footer changes
- Footer: Changed EtherScamDB to CryptoScamDB 
- Footer: Added FindETH
1. Check footer
2. Click on links in footer
=> Various footer changes

common/v2/services/Store/Account/helpers.ts, common/v2/services/Store/BalanceService.tsx, common/v2/utils/convert.tsx
Fixes a bug in fiat value conversions due to overflow/underflow when converting numbers to bigNumber.
Fixes bug due to assuming object type that resulted in RSOD.
=> Conversion bug fix (overflow/underflow errors)

common/v2/config/networks.ts, common/v2/config/tokens/kovan.json, common/v2/config/tokens/rinkeby.json, common/v2/config/tokens/ropsten.json, common/v2/services/Store/LocalCache/seedCache.ts
🎉 🎉 🎉
Fixed a few issues with new test assets as discussed with @blurpesec on Slack.
* Fixed contract address comparison
* Renamed some testnet assets/tokens
View the dashboard, and see that issues with weird assets are gone! 😄
=> Fixed a few issues with new test assets

common/v2/features/SendAssets/components/validators/validators.spec.ts
Added unit tests for send form validation functions
=> Unit tests for send form validation functions

common/v2/components/AccountList.tsx, common/v2/components/NetworkSelectDropdown.tsx, common/v2/features/Dashboard/components/WalletBreakdown/AccountDropdown.tsx, common/v2/features/DevTools/DevTools.tsx, common/v2/features/DevTools/ToolsAccountList.tsx, common/v2/features/Settings/components/AddToAddressBook.tsx, common/v2/services/Store/AddressBook/helpers.ts
There was a bug with adding a new label to an address in the settings page. This PR fixes that.
- Added Network Field
- Altered the function finding address labels to use context instead of reading directly from LC.
=> Fix Bug with Address Label Addition

webpack_config/makeConfig.js
https://github.com/MyCryptoHQ/MyCrypto/pull/2749 for `develop`
=> Fix undefined file hash (develop)

common/v2/features/SendAssets/components/ConfirmTransaction.tsx
Adds indication that the transaction has begun to be broadcasted. Need to get some feedback about copy for this.
=> Added logic for indicating tx is being broadcasted

common/v2/features/SendAssets/SendAssets.tsx, common/v2/features/SendAssets/components/SendAssetsForm.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/Hardware.tsx, common/v2/features/SendAssets/components/TransactionReceipt.tsx, common/v2/features/SendAssets/components/displays/TransactionDetailsDisplay.tsx, common/v2/features/SendAssets/types.ts, common/v2/types/walletId.ts
Fixes the sendmax button when user is trying to send tokens.
* Added handling for erc20 tokens in the sendmax button logic.
* Added logic for Send New Transaction button in receipt panel
=> Fix sendmax button

common/v2/features/SendAssets/components/SignTransaction.scss, common/v2/features/SendAssets/components/SignTransaction.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/Hardware.scss, common/v2/features/SendAssets/components/SignTransactionWallets/Hardware.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/Keystore.scss, common/v2/features/SendAssets/components/SignTransactionWallets/Keystore.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/MetaMask.scss, common/v2/features/SendAssets/components/SignTransactionWallets/Metamask.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/Mnemonic.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/PrivateKey.tsx
- correct panel width for hardware wallets
- stop address overflow for MM
=> ev/fix mobile designs for SignTransactions

common/v2/features/Dashboard/components/WalletBreakdown/BreakdownChart.tsx, common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdown.tsx, common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdownView.tsx
Made wallet breakdown chart a little more user friendly. 
* Combined all portions of chart less than 3%.
* Don't display labels on portions of chart less than 3%.
=> Wallet Breakdown Chart Changes

common/v2/config/ethScan.ts
[ch3083](https://app.clubhouse.io/mycrypto/story/3083/add-new-eth-scan-compatible-networks)
update ethscan compatible networks list
=> add kovan and goerli to ethscan networks

common/v2/features/Dashboard/components/TokenPanel/TokenList.tsx, common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdown.tsx, common/v2/features/SendAssets/SendAssets.tsx, common/v2/features/SendAssets/components/ConfirmTransaction.tsx, common/v2/features/SendAssets/components/SendAssetsForm.tsx, common/v2/features/SendAssets/components/TransactionReceipt.tsx, common/v2/services/Store/StoreProvider.tsx, common/v2/utils/convert.spec.ts, common/v2/utils/convert.ts, common/v2/utils/index.ts
Add rates calculation for confirm and tx receipt panels.
=> Add fiat calculation for confirm panel and tx receipt panel

common/v2/components/AccountList.tsx, common/v2/components/WalletUnlock/Mnemonic.tsx, common/v2/features/Dashboard/Dashboard.tsx, common/v2/features/ReceiveAssets/ReceiveAssets.tsx, common/v2/features/Settings/Settings.tsx, common/v2/features/Settings/components/AddressBook.tsx, common/v2/features/Settings/components/GeneralSettings.tsx, package.json, yarn.lock
=> Update UI in Core

common/AppRouter.tsx, common/sass/styles/scaffolding.scss, common/v2/utils/index.ts, common/v2/utils/scrollToTop.tsx
[ch3150](https://app.clubhouse.io/mycrypto/story/3150/scroll-to-top-on-route-change)
important:
'scrollTo' will fail if the main div has an overflow y or x (?!)
so we remove it from the #app container
=> return to top of layout on route change

common/v2/features/Home/components/TestimonialsPanel.tsx
=> Added new testimonials to home page

common/v2/components/TransactionFlow/TransactionReceipt.tsx
Fixed a bug with txReceipt panel on Metamask
=> Fix txReceipt for Metamask

common/v2/features/Dashboard/constants.ts, common/v2/features/Layout/Header/constants.ts
Deactivate incomplete links:
- Contract interaction
- Swap
=> Remove incompleted links for beta

common/v2/components/TransactionFlow/ConfirmTransaction.tsx, common/v2/components/TransactionFlow/TransactionReceipt.tsx
This switches order of To and From accounts in Send Assets flow. This is the expected order.
=> switched order of to and from addresses in Send Assets flow

common/v2/features/SendAssets/components/SendAssetsForm.tsx, common/v2/features/SendAssets/components/fields/GasPriceSlider.tsx, common/v2/services/Store/LocalCache/seedCache.ts, common/v2/types/network.ts
- Fixed missing gas text when sending testnet assets
- Added isTestnet field to Network interface
=> Fixed missing gas text when sending testnet assets

common/v2/components/AccountList.tsx, common/v2/routing/PrivateRoute.tsx, common/v2/routing/routes.tsx, common/v2/types/routes.ts
Added route redirection for pages with required accounts
As an alternative to #2810 and #2808
=> Added route redirection for pages with required accounts

common/v2/services/WalletService/web3/web3.ts
Removed shepherd from web3 walletservice
=> Removed shepherd from web3 walletservice

common/translations/lang/en.json, common/v2/config/data.tsx, common/v2/features/Layout/Header/Header.tsx, common/v2/features/NotificationsPanel/components/WalletAddedNotification.tsx, common/v2/features/NotificationsPanel/components/WalletCreatedNotification.tsx, common/v2/features/NotificationsPanel/components/WalletNotAddedNotification.tsx, common/v2/features/SendAssets/components/SendAssetsForm.tsx, common/v2/features/SendAssets/components/SignTransactionWallets/Hardware.tsx
=> Fixed a bunch of broken links

common/translations/lang/en.json, common/v2/features/ScreenLock/ScreenLockLocking.tsx
The inactivity timer view will show the correct minutes of inactivity instead of static "5 minutes"
=> Fixed inactivity timer

common/v2/features/AddAccount/components/SaveAndRedirect.tsx
Fixed an issue where an address label wouldn't be shown correctly on dashboard after being added
=> Fixed address book issues

common/v2/config/data.tsx, common/v2/features/NotificationsPanel/components/OnboardingResponsibleNotification.tsx
Updated 'learn more' link on onboarding notification
=> Updated 'learn more' link on onboarding notification

common/v2/components/WalletUnlock/Web3ProviderInstall.tsx
Fixed missing variable on Web3 install translation
=> Fixed missing variable on Web3 install translation

common/v2/components/Currency.tsx, common/v2/components/Typography.tsx, common/v2/config/index.ts, common/v2/features/Dashboard/components/WalletBreakdown/BalancesDetailView.tsx, common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdown.tsx, common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdownView.tsx, common/v2/features/Dashboard/components/WalletBreakdown/types.ts
- Updated currency formatting to include commas in larger numbers
- Used currency formatting in WalletBreakdown
- Used fiat setting for WalletBreakdown
=> Updated currency formatting

common/translations/lang/en.json, common/v2/features/Dashboard/constants.ts
Changed copy for dashboard buttons
=> Edit dashboard action buttons copy

common/v2/features/Settings/components/AddressBook.tsx
Added network to address book settings
=> Added network to address book settings

common/libs/nodes/configs.ts
Quick update to egem network for url.
=> Update EGEM Network

package.json, yarn.lock
🎉 🎉 🎉
* High level
* changes that
* you made
1. Steps
2. to
3. test
=> Update @mycrypto/ui from 0.18.3 to 0.20.2

common/v2/features/AddAccount/components/SaveAndRedirect.tsx, common/v2/services/Store/AddressBook/helpers.ts
=> Updated Address Book naming

common/v2/components/AmountInput.tsx, common/v2/components/index.ts, common/v2/features/SendAssets/components/SendAssetsForm.tsx, common/v2/features/SendAssets/components/fields/EthAddressField.tsx, common/v2/theme/fonts.ts, common/v2/theme/index.ts, package.json, yarn.lock
A few improvements to the Send Assets flow input components.
- Added `AmountInput` component
- Added `monospace` font and used in address and amount input
=> Send Assets input improvements

common/config/tokens/ella.json, common/config/tokens/esn.json, common/config/tokens/etc.json, common/config/tokens/eth.json, common/config/tokens/gor.json, common/config/tokens/kov.json, common/config/tokens/rin.json, common/config/tokens/rop.json, common/config/tokens/ubq.json, package.json, yarn.lock
- Re-added names to token list
- Fixed UUID generation
=> Fixed issues with token parser

common/v2/components/AssetDropdown.tsx, common/v2/components/index.ts, common/v2/features/ReceiveAssets/ReceiveAssets.tsx, common/v2/features/SendAssets/components/SendAssetsForm.tsx, common/v2/features/SendAssets/components/fields/AssetDropdown.tsx, common/v2/features/SendAssets/components/fields/index.ts
- Fixed search for `AssetDropdown`
- Implemented `AssetDropdown` for receive assets
- Small fixes to Receive Assets
Has some performance issues currently on receive assets flow
=> Receive and SendAssets improvements and fixes

package.json, webpack_config/development.js, yarn.lock
[ch3434](https://app.clubhouse.io/mycrypto/story/3434/webpack-improve-dev-server)
Remove plugin to stop dev server from running out of memory.
=> Remove HardSourceWebpackPlugin

webpack_config/electron-main.development.js
🎉 🎉 🎉
......
* High level
* changes that
* you made
1. Steps
2. to
3. test
=> Fix webpack not finding tsx files

common/v2/services/Store/Cache/Cache.ts
Fixes a bug with createWithID introduced during cache swap
=> Fixes a bug with createWithID introduced during cache swap

common/translations/lang/en.json, common/v2/config/constants.ts, common/v2/features/Dashboard/Dashboard.tsx, common/v2/features/NotificationsPanel/NotificationsPanel.tsx, common/v2/features/NotificationsPanel/components/UnlockVIPDetected.tsx, common/v2/features/NotificationsPanel/components/index.ts, common/v2/features/NotificationsPanel/constants.ts, common/v2/services/Store/BalanceService.tsx, common/v2/services/Store/StoreProvider.tsx
I wanted to test erc721 interaction and decided to try to do Unlock Protocol detection, and ended up doing the entire integration for determining if the user has one of our Unlock tokens. In order to test it, i added a notification thanking the user for donating.
ToDo: 
With unlock token:
Without unlock token:
=> Add Unlock Protocol detection and notification

.github/workflows/ci.yml, package.json, webpack_config/buildElectron.js, yarn.lock
https://app.clubhouse.io/mycrypto/story/3821/improve-ci
=> Improve CI [ch3821]

common/v2/components/ContentPanel.tsx, common/v2/features/ReceiveAssets/ReceiveAssets.tsx
Partially addresses [CH3900] - Adjust global panel to show full address
https://app.clubhouse.io/mycrypto/story/3900/adjust-global-panels-to-view-full-address
=> Make the contentpanel wider and see how it goes

common/config/tokens/rsk.json, common/v2/config/tokens/rsk.json
🎉 🎉 🎉
Adds two custom tokens
* Only configuration
=> Add INV & DOC token to RSK network

common/v2/features/Layout/Header/Header.tsx
=> Make header draggable for Electron

common/v2/components/AddressField.tsx, common/v2/components/ENSStatus.tsx, common/v2/components/WalletUnlock/ViewOnly.tsx, common/v2/features/SendAssets/components/SendAssetsForm.tsx, common/v2/features/SendAssets/components/fields/EthAddressField.tsx
0x0000000000000000000000000000000000000000 was already considered an invalid address.
Just made sure we checked it when doing ENS lookups
=> Added check to make sure ENS resolved address is valid

common/v2/services/ApiService/Analytics/Analytics.ts
Just added a condition to disable Analytics while on Dev environment cause it returns a lot of 404 errors
=> Disable Analytics in Dev Environment

common/v2/components/AddressField.tsx, common/v2/components/WalletUnlock/ViewOnly.scss
- Added identicons to `AddressField` component
- Fixed width issue with `ViewOnly`
=> Added addressfield identicon

common/v2/components/InputField.tsx, common/v2/config/data.tsx, common/v2/features/SwapAssets/stateFactory.tsx, common/v2/features/SwapAssets/types.ts, common/v2/translations/lang/en.json, common/v2/utils/emailFormatter.ts, common/v2/utils/index.ts
- Added error message for swap api failure
- Added general support for generating support emails
=> Added error message for swap api failure

common/v2/components/AddressField.tsx, common/v2/components/WalletUnlock/SafeT.scss, common/v2/components/WalletUnlock/ViewOnly.scss, common/v2/components/WalletUnlock/ViewOnly.tsx
- Fixed `ViewOnly` styling issues
- Fixed button overlap on `SafeT`
=> Fixed small styling issues

common/v2/features/AddAccount/components/SaveAndRedirect.tsx
- Added automatic scan for tokens after adding a new account
=> Added automatic scan for tokens after adding a new account

common/v2/services/ApiService/Analytics/Analytics.ts, common/v2/services/ApiService/Analytics/constants.ts
[[4294]](https://app.clubhouse.io/mycrypto/story/4294/enable-analytics-for-dev-mode)
=> re-enable analytics for development environment

common/v2/features/InteractWithContracts/components/GeneratedInteractionForm.tsx, common/v2/features/InteractWithContracts/components/Interact.tsx, common/v2/features/InteractWithContracts/getParsedQueryString.spec.ts, common/v2/features/InteractWithContracts/utils.ts, common/v2/translations/lang/en.json
[ch3421]
Below listed params should be used:
- network,
- address,
- function,
- input (for each input in format `param name:param value`)
Test url: [https://mycryptobuilds.com/pr/2920/#/interact-with-contracts?network=Ropsten&address=0xbb4AAaF8cAA1A575B43E7673e5b155C1c5A8BC13&function=etherBalances&input=addresses:[%220xCb1E63be3e892126eED1345831720759435c9066%22,%220x82D69476357A03415E92B5780C89e5E9e972Ce75%22]&input=secondParam:secondValue&input=thirdP:thirdV](https://mycryptobuilds.com/pr/2920/#/interact-with-contracts?network=Ropsten&address=0xbb4AAaF8cAA1A575B43E7673e5b155C1c5A8BC13&function=etherBalances&input=addresses:[%220xCb1E63be3e892126eED1345831720759435c9066%22,%220x82D69476357A03415E92B5780C89e5E9e972Ce75%22]&input=secondParam:secondValue&input=thirdP:thirdV)
=> Prefill interact with contracts data from URL

common/v2/database/data/networks.ts
needs to be tested to ensure both transaction and address links work
=> change block explorer for ETC

common/v2/features/AddAccount/stories.tsx
Fix an issue where some wallets were missing in `dev:electron`
=> Fix hideFromWalletList conditions

package.json, yarn.lock
[ch4040]
Enable updated tooltip component by bumping @mycrypto/ui lib.
=> Bump @mycrypto/ui lib to latest version

common/features/config/networks/static/reducer.ts
https://github.com/MyCryptoHQ/MyCrypto/pull/2958 but for legacy
=> Update block explorer for ETC in legacy

common/features/config/networks/static/reducer.ts, common/libs/nodes/configs.ts
Reverts MyCryptoHQ/MyCrypto#2770
=> Revert "Update Ellaism Links"

common/features/config/networks/static/reducer.ts, common/libs/nodes/configs.ts
https://github.com/MyCryptoHQ/MyCrypto/pull/2770
=> Update Ellaism links

electron-app/main/index.ts, electron-app/main/window.ts, electron-app/preload/index.ts, webpack_config/buildElectron.js, webpack_config/electron-main.development.js
=> Move registerProtocol method from preload, remove empty preload

common/v2/features/SwapAssets/helpers.ts
=> Added proxy contract to transaction data correctly

common/v2/components/AddressField.tsx, common/v2/components/ExtendedContentPanel.tsx, common/v2/features/InteractWithContracts/components/Interact.tsx, common/v2/features/InteractWithContracts/stateFactory.tsx, common/v2/services/EthService/ens/__tests__/validators.spec.ts, common/v2/services/EthService/ens/validators.ts, common/v2/services/Store/Contract/ContractProvider.tsx
- Used AddressField component for Contracts
- Fixed some validation issues
=> Used AddressField component for Contracts

common/v2/features/SendAssets/components/SendAssetsForm.tsx
[ch3514](https://app.clubhouse.io/mycrypto/story/3513/sendassets-preserve-form-state-on-back)
Preserve form state when moving from 'Confirm' to 'SendForm'
=> Prefil SendAssetsForm with txConfig when it exists

common/v2/components/AccountDropdown.tsx, common/v2/components/AddressField.tsx, common/v2/components/AmountInput.tsx, common/v2/components/AssetDropdown.tsx, common/v2/components/AssetSummary.tsx, common/v2/components/Checkbox.tsx, common/v2/components/Dropdown.tsx, common/v2/components/InputField.tsx, common/v2/components/TransactionFlow/displays/TransactionDetailsDisplay.scss, common/v2/components/TransactionFlow/displays/TransactionDetailsDisplay.tsx, common/v2/features/SendAssets/SendAssets.tsx, common/v2/features/SendAssets/components/SendAssetsForm.scss, common/v2/features/SendAssets/components/SendAssetsForm.tsx, common/v2/features/SendAssets/components/fields/DataField.tsx, common/v2/features/SendAssets/components/fields/GasLimitField.tsx, common/v2/features/SendAssets/components/fields/GasPriceField.tsx, common/v2/features/SendAssets/components/fields/NonceField.tsx, common/v2/translations/lang/en.json, common/v2/types/transactionFlow.ts, common/v2/utils/validators.ts
=> Send form styling updates

common/v2/database/data/tokens/eth.json, common/v2/database/v1.0.0/generateDefaultValues.spec.ts, package.json
Updated the token output location for `yarn update:tokens` to match beta's config location.
=> Updated tokens and script output location for beta

common/libs/nodes/configs.ts
https://github.com/MyCryptoHQ/MyCrypto/pull/2982 but for `legacy` branch
=> Legacy: Update ETC endpoint

common/v2/database/data/networks.ts, common/v2/database/v1.0.0/generateDefaultValues.spec.ts
Fixed issues caused by https://github.com/MyCryptoHQ/MyCrypto/pull/2991
=> Fixed test and linting issues

common/v2/components/AccountList.tsx, common/v2/database/data/networks.ts, common/v2/theme/constants.ts
Added the wallet type to AccountList in Dashboard
=> added wallet type to account list

package.json, yarn.lock
Updated ethers.js to fix ENS bug
=> Updated ethersjs to fix ens bug

common/v2/features/Dashboard/components/RecentTransactionList.tsx
=> Reversed sort order for tx history table in dashboard

common/v2/features/ScreenLock/ScreenLockProvider.tsx, common/v2/services/Store/DataManager/DatabaseService.ts
Attempted to fix unlock bugs 
Go to https://mycryptobuilds.com/pr/3027 . Does it send you to the unlock screen? Good.
=> Unlock bug(s) fix

common/v2/features/ScreenLock/ScreenLockProvider.tsx, common/v2/services/Store/DataManager/DatabaseService.ts
Reverts MyCryptoHQ/MyCrypto#3027
=> Revert "Unlock bug(s) fix"

common/v2/features/Dashboard/components/ActionTile.tsx, common/v2/features/Dashboard/constants.ts, common/v2/features/Dashboard/types.ts, common/v2/translations/lang/en.json
**Description :**
Used basic `Math.Random()` function to randomise selection between Ledger and Trezor on "Get Hardware Wallet" tile.
**Steps to test :**
1. Load dashboard
2. Reload dashboard
3. Reload dashboard
4. If you've not seen any difference on the tile, reload until you see one. Apparently you're not lucky. :(
Story details: https://app.clubhouse.io/mycrypto/story/4899
=> Dashboard: Rotate get Ledger/Trezor CTA on load

electron-app/main/index.ts
[CH5099]
🎉 🎉 🎉
* Modify Electron settings
=> update electron settings

common/v2/translations/lang/ar.json, common/v2/translations/lang/de.json, common/v2/translations/lang/el.json, common/v2/translations/lang/es.json, common/v2/translations/lang/fi.json, common/v2/translations/lang/fr.json, common/v2/translations/lang/ht.json, common/v2/translations/lang/hu.json, common/v2/translations/lang/id.json, common/v2/translations/lang/it.json, common/v2/translations/lang/ja.json, common/v2/translations/lang/ko.json, common/v2/translations/lang/nl.json, common/v2/translations/lang/no.json, common/v2/translations/lang/pl.json, common/v2/translations/lang/pt.json, common/v2/translations/lang/ru.json, common/v2/translations/lang/sk.json, common/v2/translations/lang/sl.json, common/v2/translations/lang/sv.json, common/v2/translations/lang/tr.json, common/v2/translations/lang/vi.json, common/v2/translations/lang/zhcn.json, common/v2/translations/lang/zhtw.json
Just wanted to clean some dead code.
=> Remove reference to Cipher in i18n files

common/v2/database/seed/accounts.ts, common/v2/features/CreateWallet/Keystore/Keystore.tsx, common/v2/features/CreateWallet/Mnemonic/Mnemonic.tsx, common/v2/features/DevTools/DevTools.tsx, common/v2/features/SendAssets/stateFactory.tsx, common/v2/services/Store/BalanceService.tsx, common/v2/services/Store/StoreProvider.tsx, common/v2/types/account.tsx
To have better types for address.
=> Use TAddress for Account address

common/v2/components/AccountList.tsx
The goal of this pr is to introduce sorting to the AccountList table. I removed the sorting for AccountList from the AbstractTable, and use a switcher for the sorting functions.
=> Added sorting in the AccountList table

common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdownView.tsx, common/v2/features/Dashboard/components/WalletBreakdown/helpers.test.ts, common/v2/features/Dashboard/components/WalletBreakdown/helpers.ts, common/v2/features/Dashboard/components/WalletBreakdown/index.ts
Changed pie chart settings to make it function slightly better.
Add some accounts and play with it to see if there's anything you expect to work better
=> Make pie chart better

common/v2/components/NetworkSelectDropdown.tsx, common/v2/features/Settings/Export/Downloader.tsx, common/v2/features/Settings/Export/Export.tsx, common/v2/features/Settings/Import/components/ImportBox.tsx, common/v2/features/Settings/components/AddToAddressBook.tsx, common/v2/translations/lang/en.json
- Added form validation to `AddToAddressBook` component on Settings page
- Changed styling of import box validation
- Fixed styling inconsistencies with `AddToAddressBook`
=> Settings Form Validation

common/v2/features/DevTools/DevTools.tsx, common/v2/features/ErrorHandling/ErrorProvider.tsx, common/v2/services/EthService/__tests__/validators.spec.ts, common/v2/services/EthService/validators.ts
- Fixes issue with crashing when using DevTools following recent change
- Fixes issue where inputting symbols in send asset flow would crash
- Fixes issue where you would be redirected even when suppressing errors
=> Small bug fixes

common/v2/features/SendAssets/components/SendAssetsForm.tsx
Fixed crash with form validation for transaction fees
=> Hotfix for send flow crash

common/v2/database/data/tokens/eth.json, common/v2/database/v1.0.0/generateDefaultValues.spec.ts
This updates tokens from ethereum-lists.
=> Updated Tokens (includes defi protocol tokens)

common/v2/features/Dashboard/components/TokenPanel/TokenList.tsx
- View Dashboard and see that Token value is hidden in the TokenList (left hand side)
=> Added support for hiding tokenlist values

common/v2/components/ContactLookupField.tsx, common/v2/database/data/contracts.spec.ts, common/v2/database/data/tokens.spec.ts, common/v2/features/SendAssets/components/SendAssetsForm.tsx, common/v2/services/EthService/__tests__/validators.spec.ts, common/v2/services/EthService/validators.ts, common/v2/translations/lang/en.json, common/v2/types/errorObject.ts, common/v2/types/index.ts
Made better address validation? I hope
=> Made better address validation

common/v2/components/AssetDropdown.tsx, common/v2/components/ContactLookupField.tsx, common/v2/components/Dropdown.tsx, common/v2/components/NetworkSelectDropdown.tsx, common/v2/features/InteractWithContracts/components/GeneratedInteractionForm.tsx, common/v2/features/InteractWithContracts/components/Interact.tsx
Fixed weird styling offset caused by `react-select`
- Applied to `Dropdown` component
- Needs testing to make sure it doesn't break any dropdowns
=> Small styling fix to Dropdown component

package.json, yarn.lock
Updated UI library to include new Accordian component
=> Updated UI library

common/v2/components/Account.tsx, common/v2/components/AccountList.tsx, common/v2/components/NetworkSelectDropdown.tsx, common/v2/components/Tooltip.tsx, common/v2/components/TransactionFlow/displays/TransactionIntermediaryDisplay.tsx, common/v2/components/index.ts, common/v2/features/AddAccount/components/NetworkSelectPanel.tsx, common/v2/features/Dashboard/components/TokenPanel/TokenList.tsx, common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdown.tsx, common/v2/features/SendAssets/components/SendAssetsForm.tsx, common/v2/features/Settings/components/AddressBook.tsx, common/v2/features/Settings/components/DangerZone.tsx, common/v2/features/Settings/components/GeneralSettings.tsx, common/v2/features/SwapAssets/components/SwapAssets.tsx, common/v2/translations/lang/en.json
Added a bunch of tooltips
Affected flows/pages: 
- Add account flow
- Send assets flow
- Swap flow
- Settings page
=> Added tooltips

common/v2/services/Store/helpers.tsx
Fixes store-account label bug by not assuming it exists!
=> Fix store-account label bug

common/v2/features/Dashboard/components/WalletBreakdown/BreakdownChart.tsx, common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdownView.tsx, package.json, yarn.lock
=> Fix charts bug

common/v2/database/data/tokens/eth.json, common/v2/database/v1.0.0/generateDefaultValues.spec.ts
Pulled tokens down to include updated uniswap pool tokens.
=> Updated Tokens

.github/workflows/ci.yml, common/v2/services/Store/BalanceService.tsx, package.json, yarn.lock
- Updated eth-scan
- Fixed issues in BalanceService following update
- Made sure to return `BigNumber.js`
- Added new method for fetching balances
- Fixed issues with CI caching
=> Updated eth-scan

common/v2/config/constants.ts, common/v2/features/DeFiZap/components/ZapCard.tsx, common/v2/services/ApiService/DeFiReserveMap/DeFiReserveMap.ts, common/v2/services/ApiService/DeFiReserveMap/index.ts, common/v2/services/ApiService/index.ts, common/v2/services/RatesProvider.tsx, common/v2/services/Store/StoreProvider.tsx, common/v2/types/asset.tsx, package.json
Added in the DeFi protocol balances
=> Zap Protocol Balances

common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdownView.tsx
=> Fix coingecko logo alignment

common/v2/features/Dashboard/components/MembershipPanel.tsx, common/v2/services/EthService/contracts/index.ts, common/v2/services/EthService/contracts/unlockAbi.ts, common/v2/services/EthService/contracts/unlockToken.ts, common/v2/services/EthService/network/index.ts, common/v2/services/EthService/network/unlockProtocolProvider.ts, common/v2/services/EthService/nodes/rpc/requests.ts, common/v2/services/Store/StoreProvider.tsx, common/v2/types/index.ts, common/v2/types/unlockProtocolToken.ts
Added detection of Unlock Token Expiration date. Added in unlock abi as well so we can call the functions from it :-D ?
=> Added Unlock Token Expiration

common/v2/services/Store/BalanceService.tsx
Hotfix for membership detection issue
=> Membership hotfix

common/v2/features/NoAccounts/NoAccounts.tsx, common/v2/features/NoAccounts/index.ts, common/v2/features/Settings/Import/Import.tsx, common/v2/translations/lang/en.json
=> Fix import settings button

common/v2/components/ContactLookupField.tsx, common/v2/features/ReceiveAssets/ReceiveAssets.tsx, common/v2/features/SendAssets/components/SendAssetsForm.tsx, common/v2/features/SendAssets/components/fields/AmountField.tsx, common/v2/features/SendAssets/components/fields/AssetField.tsx, common/v2/features/SendAssets/components/fields/GasPriceSlider.tsx, common/v2/features/Settings/components/AddToAddressBook.tsx, package.json, yarn.lock
Updated Formik and fixed type errors
=> Updated Formik

common/v2/components/ContactLookupField.tsx, common/v2/components/WalletUnlock/ViewOnly.tsx, common/v2/features/SendAssets/components/SendAssetsForm.tsx, common/v2/services/EthService/utils/units.ts, common/v2/services/EthService/validators.ts, common/v2/utils/convert.ts, common/v2/utils/transaction.ts, common/v2/utils/validators.ts
=> Fix sending from to same address and sending max 

common/v2/components/TransactionFlow/ConfirmTransaction.tsx
=> Add loader indicator for Confirm and send

common/v2/components/AmountInput.tsx, common/v2/components/TransactionFlow/ConfirmTransaction.tsx, common/v2/components/TransactionFlow/TxReceipt.stories.tsx, common/v2/components/TransactionFlow/TxReceipt.tsx, common/v2/features/PurchaseMembership/PurchaseMembershipStepper.tsx, common/v2/features/PurchaseMembership/components/ConfirmMembershipPurchase.tsx, common/v2/features/PurchaseMembership/components/MembershipDropdown.tsx, common/v2/features/PurchaseMembership/components/MembershipPurchaseForm.tsx, common/v2/features/PurchaseMembership/components/MembershipReceiptBanner.tsx, common/v2/features/PurchaseMembership/components/MembershipSelectedBanner.tsx, common/v2/features/PurchaseMembership/components/index.ts, common/v2/features/PurchaseMembership/config.ts, common/v2/translations/lang/en.json, common/v2/utils/constants.ts
- Updated lifetime membership to use ETH contract
- Added general membership styling to confirmation and receipt panel
- Updated membership purchase form to include correct fields etc.
=> Membership Purchase Flow UI

common/v2/features/SendAssets/components/SendAssetsForm.tsx
=> Send assets, in case user has eth asset, pick it as default

common/v2/config/links.ts
Replace download desktop app link [ch5555]
=> Replace download desktop app link

common/v2/components/SignTransactionWallets/WalletConnect.tsx, common/v2/components/WalletList/WalletButton.stories.tsx, common/v2/components/WalletList/WalletButton.tsx, common/v2/components/WalletList/WalletList.tsx, common/v2/components/WalletList/index.ts, common/v2/components/WalletUnlock/WalletConnect.tsx, common/v2/components/index.ts, common/v2/features/AddAccount/AddAccountFlow.tsx, common/v2/features/AddAccount/stories.tsx, common/v2/features/SignAndVerifyMessage/SignMessage.tsx, common/v2/features/SignAndVerifyMessage/stories.tsx, common/v2/services/WalletService/walletService.ts, common/v2/services/WalletService/walletconnect/WalletConnectService.ts, common/v2/services/WalletService/walletconnect/index.ts, common/v2/services/WalletService/walletconnect/reducer.ts, common/v2/services/WalletService/walletconnect/types.ts, common/v2/services/WalletService/walletconnect/useWalletConnect.ts, common/v2/services/WalletService/walletconnect/walletConnectWallet.ts, common/v2/services/WalletService/walletconnect/withWalletConnect.tsx, common/v2/translations/lang/en.json, common/v2/types/story.ts
=> Sign message with WalletConnect

common/components/Footer/NewFooter/components/Linkset.tsx, common/config/links.ts, common/translations/lang/en.json, common/translations/lang/fr.json, common/translations/lang/ja.json, common/translations/lang/ko.json
🎉 🎉 🎉
* Changes the links from ESDB to CSDB
* Translation file changes
* Changes to configuration file
=> (LEGACY) ESDB link change to CSDB

README.md
Update GitHub readme to include feature flags [ch5686]
=> Add link to feature flag docs to README.md

common/v2/features/Dashboard/components/RecentTransactionList.tsx
Fix the asset rate lookup in tx history table
=> Fixed Asset Rate in Tx History Table

common/v2/components/SignTransactionWallets/Keystore.scss, common/v2/components/SignTransactionWallets/Keystore.tsx, common/v2/components/SignTransactionWallets/Mnemonic.tsx, common/v2/translations/lang/en.json
=> Sign Message: Implement loading state for button

common/components/Survey/Survey.scss, common/components/Survey/index.tsx, common/containers/TabSection/ElectronTemplate.scss, common/containers/TabSection/ElectronTemplate.tsx
=> [Legacy] Add survey message to desktop app

common/index.html, webpack_config/config.js
Implement meta tags for Twitter card [ch5735]
=> Implement meta tags for Twitter card

package.json, yarn.lock
This fixes an issue with case-sensitivity in domains.
=> Update @unstoppabledomains/resolution to 1.3.6

common/AppRoutes.tsx, common/Root.tsx, common/v2/features/Layout/Layout.tsx
https://mycryptohq.slack.com/archives/G8G1S4TG9/p1586207204129100
- force layout to 100% height
- include padding for stepper views
- fix fullW for home page.
=> Full height for layout

common/v2/services/EthService/__tests__/validators.spec.ts, common/v2/services/EthService/validators.ts
Fixed send crash when entering comma seperated value
=> Fixed Send Crash

common/v2/features/SendAssets/components/SendAssetsForm.tsx
- Fixed an issue with initial value of selected asset
=> Fixed an issue with initial value of selected asset on send flow

common/v2/features/ProtectTransaction/ProtectTxProvider.tsx, common/v2/features/ProtectTransaction/components/WithProtectTx.tsx, common/v2/features/SendAssets/components/SendAssetsForm.tsx
- Added Protected TX for members
=> Added Protected TX for members

common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdown.tsx, common/v2/services/Store/StoreProvider.tsx
[ch5834]
Fixed a bug with label update propagation to dashboard account dropdown.
=> Fixed label bug with dropdown in dashboard

common/v2/components/Table.tsx, common/v2/features/Dashboard/components/WalletBreakdown/WalletBreakdownView.tsx, common/v2/translations/lang/en.json
Add padding to Tables so the content is align with the Table Heading and top right button
Balance breakdown under chart now take full width and align with CoinGecko logo
Address [CH5829](https://app.clubhouse.io/mycrypto/story/5829) and [CH5831](https://app.clubhouse.io/mycrypto/story/5831)
=> Dashboard design fixes

common/v2/features/SendAssets/components/SendAssetsForm.tsx, common/v2/features/SendAssets/components/fields/GasPriceSlider.tsx
- Reduced renders and gas estimation calls
- Fixed gas estimates not being fetched initially
- Fixed a small styling issue
=> Fixed gas issues with Send Assets

common/v2/components/SignTransactionWallets/PrivateKey.tsx, common/v2/components/WalletList/WalletList.tsx, common/v2/features/AddAccount/stories.tsx, common/v2/features/CreateWallet/Mnemonic/Mnemonic.tsx, common/v2/types/story.ts, electron-app/main/menu.ts, electron-app/main/window.ts, shared/enclave/server/index.ts, shared/enclave/utils.ts
- Fixed issue with creating mnemonic wallet
- Fixed private key signing
- Re-enabled title for dragging on Mac
- Fixed missing clipboard support on Mac
=> Electron fixes

common/v2/features/SendAssets/components/SendAssetsForm.tsx
- Used default network for default base asset
=> Fixed another Send Assets default value bug

common/v2/components/AccountDropdown.tsx, common/v2/types/index.ts
Sorts alphabetically by label in account dropdown component
=> Added sorting by label to account dropdown

common/v2/features/Settings/components/AddToAddressBook.tsx
Fixed a bug resulting in white screen when add-address button is clicked in address book panel of settings page.
1) Navigate to mycryptobuilds.com/pr/3210/#/settings and scroll down till you're at the bottom of the Address Book Panel. Click (add address). Did it white screen? good!
=> Fixed bug in Add Contact (settings panel)

common/v2/services/Store/Account/AccountProvider.tsx
Fixed a bug with token scanning due to removed lodash functionality following #3142
=> Fixed bug with token scanning due to removed lodash functionality

common/v2/components/ContentPanel.tsx, common/v2/components/GeneralStepper/__tests__/GeneralStepper.test.tsx, common/v2/features/AddAccount/AddAccountFlow.tsx, common/v2/features/PurchaseMembership/components/MembershipPurchaseForm.tsx, common/v2/features/PurchaseMembership/components/MembershipReceiptBanner.tsx, common/v2/services/Store/StoreProvider.tsx, common/v2/translations/lang/en.json, package.json, yarn.lock
- Fixed styling for `ContentPanel` based on design meeting
- Automatic fetching of membership state after purchase
- Improved membership fetching and handling overall
- Fixed small styling and copy issues for membership
=> Membership QA fixes

common/v2/services/Store/StoreProvider.tsx
Changed so we only scan the account in question instead of all accounts.
=> Reduced token scanning after DefiZap TX goes through

common/v2/components/EditableText.tsx, common/v2/components/Typography.tsx
Closes [5905]
Update, multiline labels.
I started developing some custom JS solution, but I figured I won't get really far. So I used the solution on this blog:
https://css-tricks.com/almanac/properties/l/line-clamp/
Tested on Chrome/Firefox/Brawe mobile/Safari all of which works fine.
=> Update account rows labels with multiline

common/v2/features/AddAccount/AddAccountFlow.tsx
Added an analytics event for type of wallet added & new number of accounts, so we can track how many accounts are actually added.
=> Added new account event

common/config/dpaths.ts, common/features/config/networks/static/reducer.ts, common/libs/nodes/configs.ts, shared/types/network.d.ts
Add Energy Web networks
Add Energy Web networks (EnergyWeb Volta test and EnergyWeb production chain networks)
=> Add energy web networks

common/v2/components/WalletUnlock/Keystore.tsx, common/v2/services/WalletService/keystore/keystore.ts, common/v2/translations/lang/en.json
=> Fixed white screen in case of errors with keystore

.github/workflows/mycryptobuilds.yml
=> Github Actions - mycryptobuilds migration

.github/workflows/mycryptobuilds.yml, .gitignore, package.json
Adds the `yarn build:storybook` build script for github actions ci.
=> added build-storybook

common/v2/services/Store/BalanceService.tsx, common/v2/services/Store/StoreProvider.tsx, common/v2/types/bigNumber.ts, common/v2/types/index.ts
[ch6039]
Filters out zeroed balances in account asset balance updates, to remove assets that users used to have but don't anymore.
=> Remove zero balances 

common/v2/features/ErrorHandling/ErrorProvider.tsx
Handled possible undefined error path
=> Fixed error handling issue

common/v2/features/Ens/EnsLogo.tsx
Makes ENS Logo spacing smaller
=> Resize spacing for ENS logo

common/v2/features/Ens/MyDomains.tsx, common/v2/translations/lang/ar.json, common/v2/translations/lang/de.json, common/v2/translations/lang/el.json, common/v2/translations/lang/en.json, common/v2/translations/lang/es.json, common/v2/translations/lang/fi.json, common/v2/translations/lang/fr.json, common/v2/translations/lang/ht.json, common/v2/translations/lang/hu.json, common/v2/translations/lang/id.json, common/v2/translations/lang/it.json, common/v2/translations/lang/ja.json, common/v2/translations/lang/ko.json, common/v2/translations/lang/nl.json, common/v2/translations/lang/no.json, common/v2/translations/lang/pl.json, common/v2/translations/lang/pt.json, common/v2/translations/lang/ru.json, common/v2/translations/lang/sk.json, common/v2/translations/lang/sl.json, common/v2/translations/lang/sv.json, common/v2/translations/lang/tr.json, common/v2/translations/lang/vi.json, common/v2/translations/lang/zhcn.json, common/v2/translations/lang/zhtw.json
Adds ens referral query to link out.
=> Added refferal code to ens link out

src/features/Layout/Footer/components/Subscribe.tsx, src/translations/lang/en.json
Added privacy policy to subscribe form in the footer.
=> Add privacy policy to footer

src/services/ApiService/emails.ts
=> Add tag on subscription (GAU)

src/features/Dashboard/components/WalletBreakdown/WalletBreakdown.tsx, src/features/NoAccounts/NoAccounts.tsx, src/services/Store/StoreProvider.tsx
Adds new user vs existing user metric & starting number of accounts (number of accounts user has when they visit the site the first time).
=> Adds new vs existing user metric

src/config/constants.ts, src/services/Store/Asset/AssetProvider.tsx
Re-added support for excluding tokens, now from the asset API.
Fixes #3201
=> Added support for excluding tokens received from assets API

src/components/ContactLookupField.tsx
=> Prevent stuttering in ContactLookup field

src/services/EthService/network/helpers.ts
Adds infura node type to getProvider to initialize ethers.js with the api key :3?
=> Add infura node type to getProvider

src/components/GeneralStepper/GeneralStepper.stories.tsx, src/components/GeneralStepper/__tests__/GeneralStepper.test.tsx, src/components/icons/CloseIcon.tsx, src/features/ProtectTransaction/components/ProtectTxMissingInfo.tsx, src/features/ProtectTransaction/components/ProtectTxProtection.tsx, src/features/ProtectTransaction/components/WithProtectTx.tsx, src/features/SendAssets/SendAssets.tsx, src/features/SendAssets/__tests__/SendAssets.test.tsx, src/utils/withProtectTxProvider.tsx
[[ch6124]](https://app.clubhouse.io/mycrypto/story/6124/protected-transactions-qa-review-changes)
ProtectedTx
- Harmonize font-weight in sidebar
- Center main and sidebar
- Activate `has-side-panel` class
Further changes may only be addressed after merging #3289 Nansen PR
=> Protected tx UI fixes

src/features/SendAssets/SendAssets.tsx
Attempts to fix bug in send-assets form
=> Fixes bug in send-assets flow

shared/types/network.d.ts, src/config/dpaths.ts, src/database/data/networks.ts, src/database/data/nodes.ts, src/database/generateDefaultValues.spec.ts, src/types/networkId.ts
Based on https://github.com/MyCryptoHQ/MyCrypto/pull/3172 but for `master`.
=> Add EWC networks

.github/workflows/mycryptobuilds.yml
Add condition in github actions to set the correct E2E_BASE_URL for master
=> Set E2E_BASE_URL for master

src/config/constants.ts, src/features/SwapAssets/components/ConfirmSwap.tsx, src/features/SwapAssets/components/SwapAssets.tsx, src/utils/convert.spec.ts
Closes [ch5944]
The contract still needs to be updated, to take 2% fee in account.
=> Adjustments to swap fee copy

src/config/constants.ts, src/services/EthService/network/helpers.ts
Added Etherscan & Infura API keys. Use Etherscan api key in ethers.js initialization.
=> Add Infura and Etherscan API Keys

src/components/Account.tsx, src/components/EthAddress.tsx
Change address components to use checksum addresses.
=> Use checksum addresses for copyable address components

package.json
=> Add JSON formating to lint-staged

common/containers/OnboardingModal/slides/ThirdSlide.tsx, common/features/domainResolution/ens/selectors.ts, common/features/domainResolution/unstoppable/selectors.ts
This removes some console logs which spam the console and make it hard to debug user issues. This PR also updates one of the onboarding slides to include CryptoScamDB instead of EtherScamDB.
=> Legacy console log cleanup

src/features/AddAccount/AddAccountFlow.tsx, src/features/NotificationsPanel/constants.ts
[ch6221]
Added trigger for the save settings notification and edited the interval it appears on
=> Added trigger for save settings notification

__tests__/featureflag-utils.js, __tests__/send.test.js, src/AppProviders.tsx, src/AppRoutes.tsx, src/Root.tsx, src/components/AccountList.tsx, src/components/SignTransactionWallets/Web3.tsx, src/config/index.ts, src/features/Dashboard/Dashboard.tsx, src/features/DevTools/DevTools.tsx, src/features/Layout/Header/Header.tsx, src/features/Layout/Header/constants.ts, src/features/ProtectTransaction/ProtectTxProvider.tsx, src/features/SendAssets/__tests__/SendAssets.test.tsx, src/features/Settings/Settings.tsx, src/routing/index.ts, src/routing/routes.tsx, src/services/EthService/network/helpers.ts, src/services/FeatureFlagProvider.tsx, src/services/index.ts, src/types/global.d.ts, src/utils/web3.ts
- Add Provider for feature flags
- Add feature flags dynamically switchable in DevTools
- Add testing utils to change feature flags
- Add PTX test that tests feature behind feature flag
=> Dynamic Feature Flags

src/components/Account.tsx, src/components/AccountList.tsx, src/components/EditableAccountLabel.tsx, src/components/EditableText.tsx, src/components/TransactionFlow/ConfirmTransaction.stories.tsx, src/components/TransactionFlow/ConfirmTransaction.tsx, src/components/TransactionFlow/TxReceipt.stories.tsx, src/components/TransactionFlow/TxReceipt.tsx, src/components/TransactionFlow/displays/FromToAccount.tsx, src/components/__tests__/EditableAccountLabel.test.tsx, src/components/index.ts, src/features/Dashboard/components/RecentTransactionList.tsx, src/features/SwapAssets/components/ConfirmSwap.tsx, src/services/Store/AddressBook/helpers.ts
[ch6098]
Add edit label functionality into more places.
=> Expand edit label functionality

common/components/WalletDecrypt/components/DeterministicWalletsModal.tsx
This removes the token dropdown from the address modal, since it can cause the application to freeze.
=> Remove token dropdown from address modal

src/components/Amount.tsx, src/components/ContentPanel.tsx, src/components/GeneralStepper/GeneralStepper.tsx, src/components/GeneralStepper/__tests__/GeneralStepper.test.tsx, src/components/PoweredByText.tsx, src/components/TransactionFlow/ConfirmTransaction.tsx, src/components/TransactionFlow/TxReceipt.tsx, src/features/Dashboard/components/RecentTransactionList.tsx, src/features/ProtectTransaction/components/ProtectTxBase.tsx, src/features/ProtectTransaction/components/ProtectTxProtection.tsx, src/features/ProtectTransaction/components/ProtectTxReport.tsx, src/features/ProtectTransaction/components/WithProtectTx.tsx, src/features/ProtectTransaction/utils.ts, src/features/SendAssets/SendAssets.tsx, src/features/SendAssets/components/SendAssetsForm.tsx, src/features/SendAssets/components/index.ts
- Reworked PTX design implementation
- Fixed a bunch of CSS/styling issues
=> PTX design rework + fixes

__tests__/layout.test.js, src/features/Layout/Layout.tsx, src/types/global.d.ts
=> Allow scroll for mobile

.github/workflows/mycryptobuilds.yml
Changing this to an S3 redirect to master branch.
=> Revert MyCryptobuilds CI change

__tests__/website.test.js, webpack_config/common.js, webpack_config/production.js
[ch6504](https://app.clubhouse.io/mycrypto/story/6504/add-favicon-to-devserver)
=> Add favicon to dev server and test

src/index.html, webpack_config/config.js
Updated the `meta` tags to change our title and description for the site. This has already been done on landing for whenever we're ready to deploy that as well. We probably won't notice any SEO improvements until landing is hosted on mycrypto.com
- Updated index.html title
- Updated index.html description to use the config file that the rest of the meta tags use.
=> Updated meta tags

src/components/TransactionFlow/TxReceipt.tsx, src/features/ProtectTransaction/components/ProtectTxAbort.tsx
=> Fix PTX abort notification styling

webpack_config/production.js
Issue with detecting routes on production builds not using HashRouter. fml
=> Fix production build

src/components/WalletUnlock/Web3Provider.tsx, src/services/WalletService/web3/web3.ts
Web3 wasn't allowing for fallback to legacy add web3 account permissions. Fixed that.
=> Fixed web3 bug

src/features/ProtectTransaction/components/ProtectTxProtection.tsx, src/translations/lang/en.json
=> Update link for PTX KB article

jest_config/jest.config.json
Improve coverage reporting:
- exclude unwanted files in coverage report
- add threshold
=> Improve coverage config 

src/components/TransactionFlow/ConfirmTransaction.tsx, src/components/TransactionFlow/TxReceipt.tsx, src/components/TransactionFlow/__tests__/ConfirmTransaction.test.tsx, src/components/TransactionFlow/__tests__/TxReceipt.test.tsx, src/features/ProtectTransaction/ProtectTxProvider.tsx, src/features/ProtectTransaction/components/ProtectTxButton.tsx, src/features/ProtectTransaction/components/WithProtectTx.tsx, src/features/SendAssets/components/SignTransaction.tsx
Fixed initial biggest issues with PTX on mobile
=> PTX Mobile fixes

src/features/Dashboard/components/RecentTransactionList.tsx
Luker noticed a bug with the tx status link in recent txs panel. This pr fixes that. We also may mock up a quick icon or something for this in the design channel.
=> Tx Status (smol changes)

src/features/TxStatus/TxStatus.reducer.test.tsx, src/features/TxStatus/TxStatus.reducer.tsx, src/features/TxStatus/TxStatus.tsx, src/services/EthService/network/providerHandler.ts
- Caught uncaught errors
- Add form validation
- Fixed bugs
=> TX Status Fixes

__tests__/layout.test.js, src/AppRoutes.tsx, src/config/isActiveFeature.ts, src/features/Layout/Layout.tsx, src/features/MigrateLS/MigrateLS.test.tsx, src/features/MigrateLS/MigrateLS.tsx
By default, display message directing to support if ever migration is missing. 
https://mycryptohq.slack.com/archives/G8G1S4TG9/p1598383606041500
=> Display default prompt for migrate ls

jest_config/__fixtures__/defiRates.ts, jest_config/__fixtures__/index.ts, src/AppProviders.tsx, src/components/AccountList.tsx, src/components/TransactionFlow/ConfirmTransaction.tsx, src/components/TransactionFlow/TxReceipt.stories.tsx, src/components/TransactionFlow/TxReceipt.tsx, src/components/TransactionFlow/__tests__/TxReceipt.test.tsx, src/features/Dashboard/components/RecentTransactionList.tsx, src/features/Dashboard/components/TokenPanel/TokenPanel.tsx, src/features/Dashboard/components/WalletBreakdown/WalletBreakdown.tsx, src/features/DeFiZap/components/ZapCard.tsx, src/features/ProtectTransaction/components/ProtectTxProtection.tsx, src/features/PurchaseMembership/components/MembershipPurchaseReceipt.tsx, src/features/SendAssets/__tests__/SendAssets.test.tsx, src/features/SendAssets/components/SendAssetsForm.tsx, src/features/Settings/Settings.tsx, src/features/SwapAssets/components/SwapTransactionReceipt.tsx, src/features/TokenMigration/components/TokenMigrationReceipt.tsx, src/features/TxStatus/TxStatus.test.tsx, src/features/TxStatus/TxStatus.tsx, src/services/Rates/RatesProvider.tsx, src/services/Rates/index.tsx, src/services/Rates/useRates.spec.tsx, src/services/Rates/useRates.tsx, src/services/Store/Asset/useAssets.tsx, src/services/index.ts, src/services/useRates.tsx
=> Add useRates

package.json, yarn.lock
=> Remove @types/crypto-js

common/api/gas.ts
🎉 🎉 🎉
* Increased max gas sanity check because there is no sanity anymore with gas prices
* Upped constant value
1. Steps
2. to
3. test
=> Increase max gas limit

src/features/Settings/components/AddressBook.tsx
Add label sort to the address book table in the settings.
=> Added label sort to address book table

src/Root.tsx, src/sass/variables/grid.scss, webpack_config/development.js, webpack_config/production.js
=> Remove sass is-electron

src/features/Layout/Layout.tsx
Add Header container z-index to fix priority of display in mobile
=> Add z-index to header container

jest_config/__fixtures__/index.ts, jest_config/__fixtures__/sendFormFields.ts, src/features/PurchaseMembership/PurchaseMembershipStepper.tsx, src/features/PurchaseMembership/helpers.ts, src/features/SendAssets/__snapshots__/helpers.spec.ts.snap, src/features/SendAssets/components/SendAssetsForm.tsx, src/features/SendAssets/helpers.spec.ts, src/features/SendAssets/helpers.ts, src/translations/lang/en.json
Add tests for the send form fields processing functions.
=> Add send form field processing tests

jest_config/__fixtures__/index.ts, jest_config/__fixtures__/notifications.ts, src/AppProviders.tsx, src/features/AddAccount/AddAccountFlow.tsx, src/features/AddAccount/__tests__/AddAccountFlow.test.tsx, src/features/CreateWallet/components/withAccountAndNotificationsContext.tsx, src/features/DevTools/ToolsNotifications.tsx, src/features/NotificationsPanel/NotificationsPanel.tsx, src/features/NotificationsPanel/index.ts, src/features/NotificationsPanel/useNotifications.spec.tsx, src/features/NotificationsPanel/useNotifications.tsx, src/features/index.ts, src/types/notification.ts
=> Refactor NotificationsProvider and test

src/components/GeneralStepper/GeneralStepper.tsx, src/components/GeneralStepper/__tests__/GeneralStepper.test.tsx, src/components/TransactionFlow/TxReceipt.tsx, src/components/TransactionFlow/helpers.spec.ts, src/components/TransactionFlow/helpers.ts, src/features/ProtectTransaction/components/WithProtectTx.tsx, src/features/SendAssets/SendAssets.reducer.tsx, src/features/SendAssets/SendAssets.tsx, src/features/SendAssets/__tests__/SendAssets.reducer.test.tsx, src/types/transactionFlow.ts
Attempted to fix two tx resubmit bugs - the bug with gas price being too low for replacement to be allowed and the bug with txReceipt panel inside send flow.
=> Replace tx bug fixes

src/services/EthService/contracts/erc20.ts, src/services/EthService/network/providerHandler.ts, src/types/erc20.ts, src/utils/asyncFilter.spec.ts, src/utils/asyncFilter.ts, src/utils/useTxMulti/actions.ts, src/utils/useTxMulti/reducer.ts, src/utils/useTxMulti/useTxMulti.spec.tsx, src/vendor/ramda.ts
Skips multi tx's which are unnecessary approvals for ERC20's.
=> Check Allowance before doing approvals

src/components/PoweredByText.tsx, src/components/WalletUnlock/DeterministicAccountList.tsx, src/translations/lang/en.json
=> Add powered by FindETH text

src/components/SignTransactionWallets/Web3.scss, src/components/SignTransactionWallets/Web3.tsx, src/components/SignTransactionWallets/__mocks__/web3.ts, src/components/SignTransactionWallets/__tests__/SignTransactionWeb3.test.tsx
=> Refactor Web3 Signer + Bug fixes

src/components/GeneralStepper/QueryBanner.tsx, src/components/PoweredByText.tsx, src/components/Tooltip.tsx
Tooltip color was broken in #3450 - fixed with this PR by adding two types of tooltip colors.
=> Fix tooltip coloring

src/features/Ens/MyDomains.tsx, src/features/Ens/__tests__/EnsDashboard.test.tsx, src/features/Ens/types.ts, src/services/ApiService/Ens/EnsService.ts
Fix ENS page issues after merging #3520
=> Fix ENS page crash after date-fns changes

src/config/dpaths.ts
Re-enable scanning of Ledger Live DPaths
=> Enable scanning of Ledger Live DPaths

src/features/ScreenLock/ScreenLockLocking.tsx
Fix screen lock time calculation error introduced in #3520
=> Fix screen lock time calculation

src/components/Tooltip.tsx, src/components/TransactionFlow/MultiTxReceipt.tsx
Addressed a display bug for gas price/limit in multi-tx receipt.
=> Fixed display bug on multi-tx receipt

src/components/Tooltip.tsx, src/components/TransactionFlow/TxReceipt.stories.tsx, src/components/TransactionFlow/TxReceipt.tsx
Fixes bug caused by merge of #3554
=> Fix button with tooltip display issue on TxReceipt

src/translations/lang/en.json
Changed the word "off" to "of"
=> Fix mispelling on Uniswap Claim card

jest_config/__fixtures__/account.ts, jest_config/__fixtures__/txConfig.ts, src/components/TokenMigration/TokenMigrationStepper.tsx, src/components/TokenMigration/__tests__/TokenMigrationConfirm.test.tsx, src/components/TokenMigration/components/TokenMigrationConfirm.tsx, src/components/TokenMigration/components/TokenMigrationMultiTx.tsx, src/utils/transaction.ts
- Fix not having a token migration screen for 1 tx, which caused it took look like the user was doing an approval but was actually doing the migration. This bug only occurs if the approval isn't necesarry.
- Fix loading state on all steps
=> Fix Token Migration bugs

package.json, src/components/TokenMigration/TokenMigrationStepper.tsx, src/components/TokenMigration/__tests__/TokenMigrationConfirm.test.tsx, src/components/TokenMigration/__tests__/TokenMigrationMultiTx.test.tsx, src/components/TokenMigration/__tests__/TokenMigrationReceipt.test.tsx, src/components/TokenMigration/components/TokenMigrationConfirm.tsx, src/components/TokenMigration/components/TokenMigrationMultiTx.tsx, src/components/TokenMigration/components/TokenMigrationReceipt.tsx, src/components/TransactionFlow/helpers.spec.ts, src/components/TransactionFlow/helpers.ts, src/components/TransactionFlow/index.ts, src/features/PurchaseMembership/PurchaseMembershipStepper.tsx, src/features/PurchaseMembership/components/ConfirmMembershipPurchase.tsx, src/features/PurchaseMembership/components/ConfirmMembershipPurchaseMultiTx.tsx, src/features/PurchaseMembership/components/MembershipPurchaseReceipt.tsx, src/features/SwapAssets/components/ConfirmSwapMultiTx.stories.tsx, src/features/SwapAssets/components/ConfirmSwapMultiTx.tsx, src/types/index.ts, src/types/transactionFlow.ts
[ch7058]
Abstracts steps of multi tx flows by standardizing similar types shared between steps.
=> Abstract steps of multi tx flows

src/config/constants.ts, src/features/Dashboard/components/TokenPanel/AddToken.tsx, src/services/ApiService/CustomAsset/CustomAsset.ts, src/services/ApiService/CustomAsset/index.ts, src/services/ApiService/index.ts, src/translations/lang/en.json
[ch7222]
Added custom asset API to 'Add Custom Token' flow to fetch coingecko id and add icon to s3.
- Added a custom asset api to backend that allows for fetching and caching Coingecko icons and returning `coinGeckoId`
- Integrated api into frontend that sends data to backend api on submit of Add Token form
=> Integrate custom asset api to add custom token flow

.github/workflows/mycryptobuilds.yml, .github/workflows/storybook.yml
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
=> Fix CI environment variable deprecation issue

src/features/BroadcastTransaction/components/BroadcastTx.tsx, src/utils/transaction.spec.ts, src/utils/transaction.ts
This adds a function to verify signed transactions using Ethers.js, rather than ethereumjs.
=> Add function to verify signed transactions

src/assets/images/icn-more.svg, src/assets/images/icn-show-closed-eye-svg.svg, src/assets/images/icn-show-eye.svg, src/components/ActionsPanel/ActionPanel.tsx, src/components/ActionsPanel/components/ActionItem.tsx, src/components/ActionsPanel/components/ActionsList.tsx, src/components/Icon/Icon.tsx, src/features/Dashboard/components/RecentTransactionList.tsx, src/features/Dashboard/components/TokenPanel/TokenList.tsx, src/features/Dashboard/components/WalletBreakdown/WalletBreakdownView.tsx, src/translations/lang/en.json, src/types/userAction.ts
=> Add hiding of user actions

.env.example, .github/workflows/mycryptobuilds.yml, __tests__/dashboard-page.po.js, __tests__/dashboard.test.js, __tests__/ethereum-mock.js, __tests__/featureflag-utils.js, __tests__/fixtures.js, __tests__/helpers.js, __tests__/send.test.js, __tests__/settings-page.po.js, __tests__/website.test.js, package.json, yarn.lock
- Remove ref to E2E_MNEMONIC
- Remove dead code
- Upgrade testcafe and adapt to new api.
=> Remove ref to E2E_MNEMONIC

package.json, src/components/AccountList.tsx, src/components/CopyableCodeBlock.tsx, src/sass/mixins.scss, src/sass/styles.scss, src/sass/styles/buttons.scss, src/sass/styles/forms.scss, src/sass/styles/overrides/forms.scss, src/sass/styles/overrides/type.scss, src/sass/variables.scss, yarn.lock
Since it is a very old dependency with vulns and it doesn't seem like we use it, except for very few cases, we can remove.
=> Remove bootstrap-sass

src/config/constants.ts, src/utils/convert.spec.ts
To be changed with https://etherscan.io/tx/0x30741fd231884a8aa82b638d2f0d28d1efcfa632f4e61f8b5f8130913252a376
=> Change commission rate

src/features/RequestAssets/RequestAssets.tsx
Fix styling and logic issues as per bug report document
=> Request assets fixes

package.json, yarn.lock
Bump Elliptic per snyk recommendation
=> Bump Ethers & Elliptic per Snyk recommendation

src/config/features.ts
=> Remove unused feature flag

src/components/ActionsPanel/__tests__/ActionDetails.test.tsx, src/components/ActionsPanel/__tests__/ActionItem.test.tsx, src/components/ContactLookupField.tsx, src/components/EditableAccountLabel.tsx, src/components/__tests__/ContactLookupField.test.tsx, src/features/InteractWithContracts/stateFactory.tsx, src/features/Settings/components/AddressBook.tsx, src/services/Store/Contact/useContacts.spec.tsx, src/services/Store/Contact/useContacts.tsx, src/services/Store/Contract/useContracts.spec.tsx, src/services/Store/Contract/useContracts.tsx, src/services/Store/StoreProvider.tsx, src/services/Store/UserAction/useUserActions.spec.tsx, src/services/Store/UserAction/useUserActions.tsx, src/services/Store/store/contact.slice.test.ts, src/services/Store/store/contact.slice.ts, src/services/Store/store/contract.slice.test.ts, src/services/Store/store/contract.slice.ts, src/services/Store/store/index.ts, src/services/Store/store/legacy.reducer.ts, src/services/Store/store/userAction.slice.test.ts, src/services/Store/store/userAction.slice.ts
Migrates to use slices & dispatch instead of legacy usage
=> Migrate entities to slices

src/features/Settings/components/AddressBook.tsx
Complements https://github.com/MyCryptoHQ/MyCrypto/pull/3649
Steps to test:
Display Contacts table in setting on desktop and on mobile view and see that there are no React errors.
=> Remove unused key

src/config/features.ts
Hides zapper using the feature flag.
=> Hide zapper

.eslintrc.json, jest_config/__fixtures__/index.ts, jest_config/__fixtures__/membership.ts, jest_config/jest.config.json, package.json, src/features/AddAccount/AddAccountFlow.tsx, src/features/PurchaseMembership/config.ts, src/services/ApiService/MembershipApi.test.ts, src/services/ApiService/MembershipApi.ts, src/services/ApiService/index.ts, src/services/Store/BalanceService.tsx, src/services/Store/StoreProvider.tsx, src/services/Store/store/account.slice.ts, src/services/Store/store/index.ts, src/services/Store/store/membership.slice.test.ts, src/services/Store/store/membership.slice.ts, src/services/Store/store/network.slice.ts, src/services/Store/store/reducer.ts, src/services/Store/store/sagas.ts, src/services/Store/store/selectors.ts, src/services/Store/store/store.ts, src/utils/bigify.ts, src/vendor/ramda.ts, yarn.lock
- Create membership slice.
- Extract membership lookup into saga.
- Test!
- Allow `eslint` to recognise `expectSaga` as an assertion.
- Remove `shared` folder from jest config.
- Delete unneeded `nestedToBigNumberJS`.
- allow `bigify` to use convert ethersjs BigNumber to BigNumber (sic)
=> Membership slice and saga

src/features/Dashboard/Dashboard.scss, src/features/Dashboard/Dashboard.tsx, src/features/Dashboard/constants.ts, src/translations/lang/en.json
Fixes styling issues with dashboard as well as preps for changes introduced by nav updates.
~- [ ] Remove Membership CTA.~ _keeping this out until nav is ready_
=> Fix dashboard styling

src/components/WalletUnlock/Web3Provider.tsx, src/features/Settings/Settings.tsx, src/features/Settings/components/GeneralSettings.tsx, src/services/Rates/useRates.spec.tsx, src/services/Store/Settings/useSettings.spec.tsx, src/services/Store/Settings/useSettings.tsx, src/services/Store/store/index.ts, src/services/Store/store/legacy.reducer.ts, src/services/Store/store/reducer.ts, src/services/Store/store/settings.slice.ts, src/services/Store/store/setttings.slice.test.ts
Create settings slice. 
[[ch7006]](https://app.clubhouse.io/mycrypto/story/7006/move-all-store-model-to-redux)
=> Create settings slice

src/components/TransactionFlow/ConfirmTransaction.stories.tsx, src/components/TransactionFlow/MultiTxReceipt.stories.tsx, src/features/Settings/components/AddOrEditNetworkNode.stories.tsx, src/features/SwapAssets/components/ConfirmSwap.stories.tsx
Fixes CDep issues for stories so they can render.
=> Fix circular dependencies for stories

src/features/SwapAssets/SwapAssetsFlow.tsx, src/features/SwapAssets/components/SwapAssets.tsx, src/helpers/transaction.ts, src/hooks/useTxMulti/reducer.ts
=> Fix issue where Swap gets stuck if gas fails

src/translations/lang/en.json
=> Fix typo in ANT migration copy

src/helpers/index.ts, src/services/TxHistory/helpers.tsx
- Fixed an issue where approvals wouldn't be categorized correctly
- Fixed an issue where ERC20 transfers would have wrong amounts
=> Improve TX history parsing

src/services/Store/store/helpers.spec.ts, src/services/Store/store/helpers.ts, src/services/Store/store/persist.config.ts
- Fixes issues where asset icons wouldn't be populated before assets were loaded from API
=> Improve merging of assets in LS

src/features/DownloadApp/DownloadApp.tsx, src/features/ScreenLock/ScreenLockForgotPassword.tsx, src/features/ScreenLock/ScreenLockNew.tsx, src/features/Settings/Export/Export.tsx, src/features/Settings/Import/Import.tsx, src/utils/index.ts, src/utils/navigation.ts
- Fix an issue where the back button would be broken if you navigated directly to a page
=> Add better back navigation

src/features/Layout/Layout.tsx, src/translations/lang/en.json
[ch7438]
Updated beta announcement banner copy for launch
=> Updated beta announcement copy for launch

common/libs/nodes/web3/client.ts, common/libs/nodes/web3/index.ts, common/libs/nodes/web3/requests.ts, common/libs/nodes/web3/types.ts, common/libs/validators.ts
[CH7547]
Copied the app web3 implementation to get to a stable implementation to support MM v9
=> Copy app web3 implementation

common/config/tokens/etc.json, common/config/tokens/eth.json, common/features/transaction/selectors.spec.ts
- Updated tokens
- Updated test, it fetched the decimal value of another UNI token previously
=> Update tokens & decimal test

src/features/Faucet/components/Error.tsx, src/translations/lang/en.json
* Add error message for daily faucet limit
=> Add error message for daily faucet limit

src/components/WalletUnlock/DeterministicAccountTable.tsx
* Fix balance parsing bug for add account flow on Ledger
=> Fix balance parsing bug for add account flow on Ledger

package.json, yarn.lock
=> Bump Redux Toolkit

src/components/AnnouncementBanner.tsx, src/components/index.ts, src/features/Layout/Layout.tsx, src/features/Layout/Navigation/DesktopNav.tsx, src/features/Layout/Navigation/TopNav.test.tsx, src/features/Layout/Navigation/TopNav.tsx, src/features/Layout/Navigation/components/NavLink.tsx, src/features/Layout/Navigation/components/NavTray.tsx, src/features/Layout/Navigation/components/__tests__/NavTray.test.tsx
- Move Banner to TopNav on desktop to fit with Demo mode
- Reduce setTimeout on trays to reduce overlap
- Fix Nav links svg fadout taking too long
=> Navigation fixes

src/components/TokenMigration/components/TokenMigrationForm.tsx, src/features/BuyAssets/BuyAssetsForm.tsx, src/features/DeFiZap/components/ZapForm.tsx, src/features/PurchaseMembership/components/MembershipPurchaseForm.tsx, src/features/RequestAssets/RequestAssets.tsx, src/features/SendAssets/components/SendAssetsForm.tsx, src/features/SendAssets/components/validators/validators.ts, src/services/Store/StoreProvider.tsx
Fixed issues that occurred when browsing with only a view only account
=> Fix default account bugs

package.json, src/components/WalletUnlock/Web3Provider.tsx, yarn.lock
=> Fix web3 unlock button

.env.example
=> Use stats url as example

src/features/SendAssets/components/SendAssetsForm.tsx
Fixed SendAssets eth_estimateGas display bug
=> Fix SendAssets error

common/components/BalanceSidebar/TokenBalances/AddCustomTokenForm/AddCustomTokenForm.tsx, common/components/BalanceSidebar/TokenBalances/AddCustomTokenForm/AddressField.tsx
=> Fix address validation for RSK network in custom token form

jest_config/test-utils.ts, src/Root.tsx, src/services/Analytics/analytics.middleware.ts, src/services/Analytics/constants.ts, src/services/Analytics/saga.test.ts, src/services/Analytics/saga.ts, src/services/Store/store/index.ts, src/services/Store/store/persist.config.ts, src/services/Store/store/persistence.slice.ts, src/services/Store/store/root.reducer.ts, src/services/Store/store/sagas.ts
I added analytics event to track:
1) `Total Accounts Added` event.
2) `wallet` (wallet type) to `Add Account` event.
=> Add analytics events

jest_config/__mocks__/@blockstack/stats.ts, jest_config/jest.config.json, src/routing/PageVisitAnalytics.tsx, src/services/Analytics/Analytics.spec.ts
* Removed `moduleDirectories` from `jest.config.json` because this can cause issues with certain dependencies, and it didn't seem to provide any benefits.
* Removed `verbose` to reduce console spam.
* Fixed some issues with `PageVisitAnalytics` and `Analytics.spec.ts` to fix errors and reduce console spam.
=> Fix Jest issues

src/services/Analytics/analytics.middleware.ts, src/services/Analytics/constants.ts
[[ch7641]](https://app.clubhouse.io/mycrypto/story/7641/analytics-round-2)
=> Track custom asset and token creation

src/components/InlineMessage/InlineMessage.tsx, src/config/helpArticles.ts, src/features/PurchaseMembership/components/MembershipEducation.tsx, src/features/PurchaseMembership/components/MembershipPlanCard.tsx
=> Mobile membership fixes

src/services/EthService/contracts/ABIFunction.ts, src/services/WalletService/deterministic/deterministic.ts
https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/#variant-1
=> Use non-deprecated functions for constructing buffers

src/components/WalletUnlock/Ledger.tsx, src/components/WalletUnlock/NewTrezor.tsx, src/services/WalletService/deterministic/DeterministicWalletService.tsx, src/services/WalletService/deterministic/types.ts, src/services/WalletService/deterministic/useDeterministicWallet.ts, src/services/WalletService/wallets/HardwareWallet.ts, src/services/WalletService/wallets/Trezor.test.ts, src/services/WalletService/wallets/Trezor.ts, src/services/WalletService/wallets/Wallet.ts, src/services/WalletService/wallets/ledger/Ledger.test.ts, src/services/WalletService/wallets/ledger/Ledger.ts
=> Fix RSK DPath issues

.github/workflows/beta.yml, .github/workflows/mycryptobuilds.yml, src/features/Layout/Navigation/components/LinkSet.tsx, src/utils/environment.ts, src/utils/index.ts, webpack_config/production.js
[ch7992]
Added commit hash to menu. Commit hash is passed in in CI
=> Display commit hash in menu

src/components/AccountList.tsx, src/services/TxHistory/useTxHistory.tsx
Handle TxHistory in LS reference deprecated network:
https://mycryptohq.slack.com/archives/G8G1S4TG9/p1611702959190700
=> Check object existence

common/components/Banner/Banner.tsx
[CH7895]
🎉 🎉 🎉
* Updated banner copy for new release of mycrypto
* copy change
1. Steps
2. to
3. test
=> [LEGACY] Updated banner copy

src/services/Analytics/analytics.middleware.ts, src/services/Store/store/serialize.middleware.ts
Fix issue with not calling next middleware in middleware chain
https://redux.js.org/tutorials/fundamentals/part-4-store#writing-custom-middleware
=> Fix Analytics Middleware

src/App.tsx, src/index.html, src/index.tsx
A jsx change in TXreceipt would cause an infinite loop of persist/rehydrate dispatches.
This limits the change to a page refresh.
=> Hotfix react-refresh

yarn.lock
Bump Elliptic as per Snyk recommendation
=> Bump Elliptic

src/components/WalletUnlock/DeterministicWallets.tsx, src/config/ethScan.ts, src/services/Store/BalanceService.test.ts, src/services/Store/BalanceService.tsx, src/services/Store/store/tokenScanning.slice.test.ts, src/services/Store/store/tokenScanning.slice.ts, src/services/WalletService/deterministic/DeterministicWalletService.tsx
Refactors the token scan to not expect ethscan to support the network.
=> Stop expecting ethscan to be supported

package.json, yarn.lock
=> Bump Lodash

.github/workflows/beta.yml, .github/workflows/mycryptobuilds.yml
Need to test this on `master` - can't test further in this pr.
=> Updated to use github_sha

.github/workflows/beta.yml, .github/workflows/mycryptobuilds.yml
=> Attempt to fix commithash on master again

src/components/AccountList.tsx, src/services/Store/Account/useAccounts.spec.tsx, src/services/Store/Settings/useSettings.spec.tsx, src/services/Store/Settings/useSettings.tsx, src/theme/constants.ts, src/theme/theme.ts
Remove Favorite icon and associated hook calls.
=> Remove dead code

common/components/WalletDecrypt/components/ParitySigner.tsx, common/containers/Tabs/GenerateWallet/components/WalletTypes.tsx, common/libs/wallet/non-deterministic/parity.ts
=> Fix download link for Parity Signer

__tests__/fixtures.js, __tests__/fixtures/persisted.json, src/components/EditableText.tsx, src/components/__tests__/EditableText.test.tsx, src/config/demo.ts, src/database/data/contacts.ts, src/features/Settings/components/AddressBook.tsx, src/services/Store/store/persist.config.spec.tsx, src/services/Store/store/persist.config.ts
[[ch8126]](https://app.clubhouse.io/mycrypto/story/8126/address-book-identicon-squished-w-long-label-note-update-tip-jar-copy)
1. Update default contact label and description
2. Limit column size to avoid squish
3. Add migration to update existing contact addresses
=> Update donate contact label and desc

src/database/data/networks.ts, src/database/data/nodes.ts, src/database/generateDefaultValues.spec.ts, src/types/networkId.ts
Add Smartchain based on user feedback
Based on #3532
=> Add Smartchain

__tests__/dashboard.test.js, __tests__/export.test.js, __tests__/fixtures.js
Add e2e test for Dashboard load with accounts. 
[[ch8277]](https://app.clubhouse.io/mycrypto/story/8277/add-e2e-test-for-app-load-with-accounts)
=> Test that Dashboard is displayed when user has existing storage

jest_config/__fixtures__/contacts.ts, src/components/AccountList.tsx, src/components/EditableAccountLabel.test.tsx, src/components/EditableAccountLabel.tsx, src/components/TransactionFlow/displays/FromToAccount.tsx, src/components/WalletUnlock/DeterministicAccountTable.tsx, src/components/__tests__/ContactLookupField.test.tsx, src/features/Dashboard/components/RecentTransactionList.tsx, src/services/Store/store/contact.slice.test.ts, src/services/Store/store/contact.slice.ts, src/services/Store/store/index.ts, src/services/Store/store/userAction.slice.test.ts, src/services/Store/store/userAction.slice.ts
Remove hook order warning from console.
[[ch8291]](https://app.clubhouse.io/mycrypto/story/8291/remove-hook-order-error-from-recenttransactionlist)
=> Remove hook from EditableLabelAccount

src/services/Store/store/rates.slice.ts
Bump rates polling interval to 90000ms
=> Bump rates polling interval

.env.example, src/utils/environment.ts
Changed the env file config for the segment proxy
=> Segment proxy env file change

src/assets/icons/actions/remove.svg, src/assets/images/icn-address-book.svg, src/assets/images/icn-cross.svg, src/components/AccountSelector.stories.tsx, src/components/AddressLookupSelector.tsx, src/components/AssetSelector.tsx, src/components/GeneralLookupDropdown.tsx, src/components/GeneralLookupField.tsx, src/components/Icon/Icon.tsx, src/components/Selector.tsx, src/components/WalletUnlock/DeterministicWallets.tsx, src/components/index.ts
[[7846]](https://app.clubhouse.io/mycrypto/story/7846/mobile-send-assets-recipient-icons)
Before:
After:
=> ClearIndicator should replace DropdownIndicator

src/features/DeFiZap/components/ZapCard.tsx, src/features/SendAssets/components/SendAssetsForm.tsx, src/services/Store/Account/useAccounts.spec.tsx, src/services/Store/Account/useAccounts.tsx, src/services/Store/StoreProvider.tsx, src/types/account.tsx, src/types/index.ts
Remove multiple unused keys in `StoreProvider`
[[ch8342]](https://app.clubhouse.io/mycrypto/story/8342/remove-storeprovider)
=> Purge StoreProvider

common/components/BalanceSidebar/EquivalentValues.tsx
=> Check if number is in safe range

src/config/dpaths.ts, src/database/data/networks.ts, src/database/data/nodes.ts, src/database/generateDefaultValues.spec.ts, src/types/networkId.ts
Add Avalanche Platform's C-Chain network
Network added according to instructions found in: https://support.mycrypto.com/developers/adding-a-new-network
=> Add Avalanche Platform's C-Chain network

src/features/SendAssets/components/SendAssetsForm.tsx, src/features/SendAssets/components/fields/GasPriceSlider.tsx
[ch7069]
Changes to use a checkbox instead of a button for sendMax
=> Changed to use sendMax checkbox instead of button

src/config/constants.ts
Workaround to fix token loading issues.
=> Set `eth-scan` batch size to 100

src/services/FeatureFlag/FeatureFlagProvider.test.ts
Fix act usage to remove warnings in test
=> Remove act should not return object error

.storybook/__snapshots__/storyshots.test.js.snap, src/components/Account.tsx, src/components/AccountSummary.tsx, src/components/ActionsPanel/components/ActionTable.stories.tsx, src/components/ActionsPanel/components/ActionTable.tsx, src/components/Amount.stories.tsx, src/components/Amount.tsx, src/components/Currency.tsx, src/components/TimeCountdown.tsx, src/components/TransactionFlow/displays/FaucetReceiptBanner.tsx, src/components/WalletUnlock/DeterministicAccountTable.tsx, src/features/Dashboard/components/RecentTransactionList.stories.tsx, src/features/Dashboard/components/RecentTransactionList.tsx, src/features/ProtectTransaction/components/ProtectTxProtection.tsx, src/features/SwapAssets/components/SwapQuote.stories.tsx, src/features/SwapAssets/components/SwapQuote.tsx, src/services/Store/StoreProvider.tsx, src/services/Store/helpers.tsx, src/services/Store/index.tsx, src/services/Store/store/account.slice.test.ts, src/services/Store/store/account.slice.ts, src/services/Store/store/index.ts, src/services/TxHistory/helpers.tsx, src/services/TxHistory/useTxHistory.spec.tsx, src/services/TxHistory/useTxHistory.tsx, src/utils/date.ts
[[ch8439]](https://app.clubhouse.io/mycrypto/story/8439/harmonise-amount-usage)
Migrate callers to new api for `Amount` component.
Misc:
- to facilitate creating stories we created selectors to free `useTxHistory` from `StoreContext`
- harmonise icon sizes in `RecentTransactionList` and `AccountSummary`
=> Use new api for Amount

src/config/dpaths.ts, src/database/data/networks.ts, src/database/data/nodes.ts, src/database/generateDefaultValues.spec.ts, src/types/networkId.ts
Story details: https://app.clubhouse.io/mycrypto/story/8401
=> Remove Musicoin from networks list

src/config/dpaths.ts, src/database/data/networks.ts, src/database/data/nodes.ts, src/database/generateDefaultValues.spec.ts, src/types/networkId.ts
🎉 🎉 🎉
......
* High level
* changes that
* you made
1. Steps
2. to
3. test
=> Add EVRICE network

__tests__/demo.test.js, src/components/WalletList/WalletList.tsx, src/services/Store/store/import.slice.test.ts, src/services/Store/store/import.slice.ts, src/services/Store/store/index.ts, src/services/Store/store/root.reducer.test.ts, src/services/Store/store/root.reducer.ts
[[ch8531]](https://app.clubhouse.io/mycrypto/story/8531/demo-mode-route-to-dashboard-after-view-demo-mode)
=> Redirect to dashbaord after demo mode is activated

.storybook/__snapshots__/storyshots.test.js.snap, src/components/WalletUnlock/Hardware.tsx, src/services/WalletService/wallets/Trezor.ts
Fixes a bug noticed by Bowen with the new hardware scanner when using Trezor wallets.
=> Fixed Trezor Add-Account Bug

src/features/Settings/Export/Export.tsx, src/services/Analytics/analytics.middleware.ts, src/services/Analytics/constants.ts
=> Track analytics deactivation

src/database/data/networks.ts
Small update, fixes https://github.com/MyCryptoHQ/MyCrypto/issues/3950.
=> Update Atheios explorer url

package.json, yarn.lock
Fixes a bug with Ethers.js returning unexpected results.
=> Bump eth-scan version

src/components/AccountList.tsx, src/config/helpArticles.ts, src/translations/lang/en.json
<p float="left">
</p>
---
Story details: https://app.clubhouse.io/mycrypto/story/8273
=> Settings: Private label: add link in tooltip

.storybook/__snapshots__/storyshots.test.js.snap, jest_config/__fixtures__/assets.ts, jest_config/test-utils.ts, src/components/TokenMigration/__tests__/TokenMigrationForm.test.tsx, src/components/TokenMigration/__tests__/TokenMigrationStepper.test.tsx, src/components/TokenMigration/components/TokenMigrationForm.tsx, src/features/BuyAssets/BuyAssetsForm.test.tsx, src/features/BuyAssets/BuyAssetsForm.tsx, src/features/DeFiZap/components/ZapForm.tsx, src/features/DeployContracts/DeployContractsFlow.test.tsx, src/features/DeployContracts/DeployContractsFlow.tsx, src/features/InteractWithContracts/InteractWithContractsFlow.test.tsx, src/features/InteractWithContracts/InteractWithContractsFlow.tsx, src/features/PurchaseMembership/components/MembershipPurchaseForm.test.tsx, src/features/PurchaseMembership/components/MembershipPurchaseForm.tsx, src/features/RequestAssets/RequestAssets.test.tsx, src/features/RequestAssets/RequestAssets.tsx, src/features/SendAssets/__tests__/SendAssets.test.tsx, src/features/SendAssets/components/SendAssetsForm.tsx, src/features/SendAssets/components/index.ts, src/features/SwapAssets/SwapAssetsFlow.test.tsx, src/features/SwapAssets/SwapAssetsFlow.tsx, src/services/Store/StoreProvider.tsx, src/services/Store/store/account.slice.ts, src/services/Store/store/index.ts
Alternative implementation of #3981
=> Move default account to selector

src/features/BroadcastTransaction/components/BroadcastTx.tsx, src/features/BroadcastTransaction/components/index.ts, src/translations/lang/en.json
Add some validation to fix an issue reported by Chris
=> Add validation of chain id for BroadcastTx

.github/workflows/mycryptobuilds.yml, .gitignore, hardhat.config.ts, package.json, yarn.lock
This should reduce the time CI takes to run by a bit.
=> Enable caching for Hardhat network fork

__tests__/hardhat-utils.js, __tests__/membership.test.js, __tests__/swap.test.js, hardhat.config.ts
=> Improve E2E speed

src/config/constants.ts, src/features/Settings/components/GeneralSettings.tsx, src/translations/lang/en.json
I would additionally like to link "privacy policy" to the privacy policy, but I do not know how to utilize the $link function
link: https://mycrypto.com/privacy/
=> Update analytics tooltip

src/features/Dashboard/components/WalletBreakdown/AccountDropdown.tsx
[ch8539]
Added scrolling to account dropdown
=> Added scrolling to account dropdown

__tests__/swap.test.js, src/features/SwapAssets/SwapAssetsFlow.test.tsx, src/features/SwapAssets/SwapAssetsFlow.tsx, src/features/SwapAssets/stateFormFactory.tsx, src/services/ApiService/Dex/Dex.ts, src/services/Store/store/asset.slice.ts, src/services/Store/store/index.ts, src/types/asset.tsx
Unleash the full potential of MyCrypto Swaps 🔥
=> Use own token list for Swaps

__tests__/contracts-page.po.js, __tests__/contracts.test.js, __tests__/fixtures.js, src/features/DeployContracts/components/Deploy.tsx, src/features/InteractWithContracts/components/GeneratedInteractionForm.tsx, src/features/InteractWithContracts/components/Interact.tsx
Added in case something is broken by EIP 1559 changes
=> Add E2E tests for contract interaction and deployment

src/components/AssetIcon.tsx, src/services/Store/store/asset.slice.test.ts, src/services/Store/store/asset.slice.ts, src/services/Store/store/store.ts
A few small changes that improve load times significantly
=> Page load performance improvements

.github/workflows/beta.yml, .github/workflows/ci.yml, .github/workflows/mycryptobuilds.yml, .github/workflows/storybook.yml, yarn.lock
Fixes an issue with the lockfile, and runs CI with `--frozen-lockfile` which could prevent situations like these in the future.
=> Fix lockfile and add --frozen-lockfile to CI

package.json, yarn.lock
Updates a few dependencies, fixes a bug with nonce equal `0`
=> Bump Wallets Library

src/features/DeployContracts/DeployContractsFlow.test.tsx, src/features/InteractWithContracts/InteractWithContractsFlow.test.tsx, src/services/EthService/network/providerHandler.ts, src/utils/typedTx.ts
Hotfixes gas estimation failing sometimes due to a bug in Geth.
=> Hotfix gas estimation failing sometimes

hardhat.config.ts, jest_config/__fixtures__/sendFormFields.ts, src/components/GasSelector.test.tsx, src/components/SignTransactionWallets/Hardware.tsx, src/components/WalletUnlock/Hardware.tsx, src/database/data/networks.ts, src/features/DeployContracts/DeployContractsFlow.test.tsx, src/features/SendAssets/__tests__/SendAssets.test.tsx, src/features/SendAssets/components/SendAssetsForm.tsx, src/features/SendAssets/components/validators/validators.spec.ts, src/features/SendAssets/components/validators/validators.ts, src/features/Settings/components/GeneralSettings.tsx, src/helpers/eip1559.ts, src/services/ApiService/Dex/Dex.spec.ts, src/services/ApiService/Dex/Dex.ts, src/services/ApiService/Gas/gasPriceFunctions.test.ts, src/translations/lang/en.json, src/vendor/ethereumMock/ethereumMock.ts, yarn.lock
=> EIP 1559 release

__tests__/membership-page.po.js, src/components/Switch.test.tsx, src/components/Switch.tsx, src/features/AddAccount/components/HDWallet.tsx, src/features/Settings/components/GeneralSettings.tsx
=> Require id for Switch component

src/helpers/eip1559.ts
To merge when enough Web3 wallets have implemented support
=> Enable Web3 for EIP1559

package.json, src/services/WalletService/walletconnect/useWalletConnect.ts, yarn.lock
Bumping as of recommendation of Snyk and WalletConnect.
=> Bump WalletConnect & WS

yarn.lock
=> Bump misc dependencies

src/services/ApiService/Gas/eip1559.test.ts, src/services/ApiService/Gas/eip1559.ts, src/services/EthService/network/providerHandler.ts
Merge when Geth releases the next update and we update our nodes
=> Fix a few things for the upcoming Geth update

src/services/Store/store/account.slice.test.ts, src/services/Store/store/account.slice.ts
Fixed a bug with pending tx nonce / eth_getTransactionCount mismatch
=> Fixed probable bug with nonce == 0 pending tx overwrite

src/components/TransactionFlow/MultiTxReceipt.tsx, src/features/BroadcastTransaction/components/BroadcastTx.tsx, src/features/NotificationsPanel/components/WalletsAddedNotification.tsx, src/features/SendAssets/components/SendAssetsForm.tsx, src/translations/translate.tsx, src/translations/translateRaw.tsx
Applying same fix as here: https://github.com/MyCryptoHQ/signer/pull/142
Please wait with merging until the Signer PR has been vetted
=> Handle escaping special chars for translation

.env.example, .github/workflows/beta.yml, .github/workflows/mycryptobuilds.yml, __tests__/export.test.js, jest_config/__fixtures__/settings.ts, package.json, src/config/constants.ts, src/database/data/settings.ts, src/features/Layout/Navigation/components/LinkSet.tsx, src/features/Layout/Navigation/components/Subscribe.tsx, src/features/Layout/Navigation/components/SupportUsTray.tsx, src/features/Layout/Navigation/components/TrayLink.tsx, src/features/Settings/Export/Export.tsx, src/services/Analytics/Analytics.spec.ts, src/services/Analytics/Analytics.ts, src/services/Analytics/analytics.middleware.ts, src/services/Analytics/helpers.ts, src/services/Analytics/index.ts, src/services/Analytics/saga.test.ts, src/services/Analytics/saga.ts, src/services/Analytics/useAnalytics.test.tsx, src/services/Analytics/useAnalytics.ts, src/services/Store/store/index.ts, src/services/Store/store/settings.slice.ts, src/types/settings.ts, src/utils/environment.ts, src/utils/index.ts, webpack_config/production.js, yarn.lock
Migrate Segment analytics to Matomo
=> Matomo analytics

src/components/SignTransactionWallets/DesktopSigner.tsx, src/components/WalletUnlock/DesktopSigner.tsx, src/index.tsx, src/services/Store/store/index.ts, src/services/Store/store/signer.slice.ts, src/utils/signerProvider.ts
Need to figure out a better solution than importing the store, since it seems to cause circular dependency issues.
=> Add nonce for replay protection

src/services/ApiService/emails.ts
I made a bug when migrating infrastructure. Looked into it and realized that the data passed is unnecessary.
=> Removed unnecessary data from mailchimp call

src/services/EthService/web3/node.ts, src/types/web3Permissions.ts
=> Fix MetaMask breaking change

src/database/data/networks.ts, src/services/EthService/validators.ts
https://github.com/gochain/gips/issues/29
=> GO chain fixes

src/components/GasSelector.tsx, src/components/TransactionFlow/TxPendingState.tsx, src/components/TransactionFlow/helpers.ts, src/features/PurchaseMembership/components/MembershipPurchaseForm.tsx, src/features/SendAssets/components/SendAssetsForm.tsx, src/features/SendAssets/helpers.ts, src/features/TokenMigration/components/TokenMigrationForm.tsx, src/helpers/eip1559.ts, src/helpers/transaction.spec.ts, src/helpers/transaction.ts, src/hooks/useGasForm/useGasForm.test.tsx, src/hooks/useGasForm/useGasForm.ts, src/services/ApiService/Dex/Dex.ts, src/services/ApiService/Gas/gasPriceFunctions.test.ts, src/services/ApiService/Gas/gasPriceFunctions.tsx
To merge when all wallet types enabled
=> Enable all wallets for EIP1559
